// @generated by xtask expand_gen
use archmage::autoversion;
#[autoversion]
unsafe fn process(ptr: *const f32, len: usize) -> f32 {
let mut s = 0.0f32;
for i in 0..len { s += unsafe { *ptr.add(i) }; }
s
}
fn main() {}
