coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flag_management:
  individual_flags:
    - name: x86_64
      paths:
        - src/
        - magetypes/src/
      carryforward: true
    - name: aarch64
      paths:
        - src/
        - magetypes/src/
      carryforward: true

ignore:
  # Proc macro crate — coverage is measured at compile time during macro
  # expansion, not during test execution. Results are not meaningful.
  - "archmage-macros/**"
  # Build tool, not shipped code.
  - "xtask/**"
  # Generated cross-platform stubs (return None / return Err).
  # Only meaningful on foreign architectures where they're trivial.
  - "src/tokens/generated/*_stubs.rs"
