// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::{ScalarToken, rite};
#[cfg(target_arch = "x86_64")]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn compute_v3(_t: ScalarToken, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[cfg(target_arch = "aarch64")]
#[target_feature(enable = "neon")]
#[inline]
fn compute_neon(_t: ScalarToken, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[cfg(target_arch = "wasm32")]
#[target_feature(enable = "simd128")]
#[inline]
fn compute_wasm128(_t: ScalarToken, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[inline]
fn compute_scalar(_t: ScalarToken, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[inline]
fn compute_default(_t: ScalarToken, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
fn main() {}
