// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::rite;
#[cfg(all(target_arch = "x86_64", feature = "simd_opt"))]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn compute_v3(data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[cfg(all(target_arch = "aarch64", feature = "simd_opt"))]
#[target_feature(enable = "neon")]
#[inline]
fn compute_neon(data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
fn main() {}
