//! `impls/x86_v4_f32_delegated.rs`: the AVX-512 tokens' `F32x4Backend` /
//! `F32x8Backend` impls, forwarded to `X64V3Token`'s.
//!
//! Derived from the generated trait definitions, so every method the trait
//! declares is forwarded and a new trait method cannot silently fall back to
//! its scalar default body for the AVX-512 tokens (issue #60). The three
//! methods with a cheaper AVX-512VL form call the hand-written helpers in
//! `impls/x86_v4_f32_overrides.rs` instead.

use indoc::formatdoc;
use quote::{ToTokens, format_ident, quote};
use syn::{FnArg, Item, Pat, TraitItem};

/// The tokens that delegate, with the expression that yields the
/// `X64V4Token` the override helpers take as proof.
const TOKENS: &[(&str, &str)] = &[
    ("archmage::X64V4Token", "self"),
    ("archmage::X64V4xToken", "self.v4()"),
    ("archmage::Avx512Fp16Token", "self.v4()"),
];

/// Methods that take the AVX-512VL path: (trait, method, helper).
const OVERRIDES: &[(&str, &str, &str)] = &[
    ("F32x4Backend", "to_u8_bytes", "to_u8_bytes_x4_v4"),
    ("F32x4Backend", "store_rgba_bytes", "store_rgba_bytes_x4_v4"),
    ("F32x8Backend", "to_u8_bytes", "to_u8_bytes_x8_v4"),
];

/// Generate the delegation file from the two trait sources.
pub(crate) fn generate(f32x4_trait_src: &str, f32x8_trait_src: &str) -> String {
    let mut body = String::new();
    for (trait_name, src) in [
        ("F32x4Backend", f32x4_trait_src),
        ("F32x8Backend", f32x8_trait_src),
    ] {
        let trait_item = find_trait(src, trait_name);
        for (token, v4_expr) in TOKENS {
            body.push_str(&delegating_impl(trait_name, &trait_item, token, v4_expr));
        }
    }

    formatdoc! {r#"
        //! W128 / W256 f32 backend delegation for `X64V4Token` / `X64V4xToken` /
        //! `Avx512Fp16Token`. Generated by xtask from the `F32x4Backend` and
        //! `F32x8Backend` definitions; do not edit.
        //!
        //! ## Why this file exists
        //!
        //! The AVX-512 tokens advertise W512 support but have no implementations
        //! of their own for the narrower [`F32x4Backend`] / [`F32x8Backend`]
        //! traits. Without these, generic code parameterized on `T: F32x8Backend`
        //! cannot accept a V4 token, and the cross-width
        //! [`F32x16FromHalves`](crate::simd::generic::F32x16FromHalves) primitive
        //! cannot either, though V4's native `_mm512_insertf32x8` is its best path.
        //!
        //! ## Deductive safety proof
        //!
        //! `X64V3Token`'s feature set is a strict subset of `X64V4Token`'s (the
        //! registry adds AVX-512 F/BW/CD/DQ/VL, PCLMULQDQ and AES on top of V3), so
        //! every instruction that is safe to execute under V3's proof is safe under
        //! V4's. [`F32x4Backend`] / [`F32x8Backend`] for `X64V3Token` use only V3
        //! intrinsics, so forwarding V4's methods to them is sound; `Self::Repr`
        //! stays `__m128` / `__m256`, so callers see no representation change.
        //! Each method forwards with the `.v3()` extractor, so the proof chain is
        //! explicit at every call. `X64V4xToken` and `Avx512Fp16Token` are V4 plus
        //! further AVX-512 sub-features, supersets of V3 by the same argument.
        //!
        //! ## The exception: pixel packing
        //!
        //! `to_u8_bytes` (both widths) and `f32x4::store_rgba_bytes` call the
        //! hand-written AVX-512VL helpers in `x86_v4_f32_overrides.rs`, which take
        //! a concrete `X64V4Token` (`self` for V4, `self.v4()` for V4x and FP16).

        #![cfg(all(target_arch = "x86_64", feature = "avx512"))]

        use crate::simd::backends::{{F32x4Backend, F32x8Backend}};
        use super::x86_v4_f32_overrides as overrides;

        {body}
    "#}
}

fn find_trait(src: &str, name: &str) -> syn::ItemTrait {
    let file = syn::parse_file(src).expect("generated backend trait source must parse");
    file.items
        .into_iter()
        .find_map(|item| match item {
            Item::Trait(t) if t.ident == name => Some(t),
            _ => None,
        })
        .unwrap_or_else(|| panic!("trait {name} not found in generated source"))
}

fn delegating_impl(
    trait_name: &str,
    trait_item: &syn::ItemTrait,
    token: &str,
    v4_expr: &str,
) -> String {
    let trait_ident = format_ident!("{trait_name}");
    let token_path: syn::Path = syn::parse_str(token).expect("token path");
    let v4: syn::Expr = syn::parse_str(v4_expr).expect("v4 expression");
    let mut methods = Vec::new();
    for item in &trait_item.items {
        let TraitItem::Fn(method) = item else {
            continue;
        };
        let sig = &method.sig;
        let name = &sig.ident;
        assert!(
            matches!(sig.inputs.first(), Some(FnArg::Receiver(_))),
            "{trait_name}::{name} has no receiver; the delegation needs `self`"
        );
        let args: Vec<syn::Ident> = sig
            .inputs
            .iter()
            .skip(1)
            .map(|arg| match arg {
                FnArg::Typed(pat) => match pat.pat.as_ref() {
                    Pat::Ident(p) => p.ident.clone(),
                    other => panic!(
                        "{trait_name}::{name}: parameter pattern `{}` is not an identifier",
                        other.to_token_stream()
                    ),
                },
                FnArg::Receiver(_) => unreachable!("receiver after the first parameter"),
            })
            .collect();
        let turbofish = {
            let params: Vec<_> = sig
                .generics
                .params
                .iter()
                .map(|p| match p {
                    syn::GenericParam::Type(t) => t.ident.to_token_stream(),
                    syn::GenericParam::Const(c) => c.ident.to_token_stream(),
                    syn::GenericParam::Lifetime(l) => l.lifetime.to_token_stream(),
                })
                .collect();
            if params.is_empty() {
                quote! {}
            } else {
                quote! { ::<#(#params),*> }
            }
        };
        let override_helper = OVERRIDES
            .iter()
            .find(|(t, m, _)| *t == trait_name && name == m)
            .map(|(_, _, helper)| format_ident!("{helper}"));
        let body = match override_helper {
            Some(helper) => quote! { overrides::#helper(#v4, #(#args),*) },
            None => {
                quote! { <archmage::X64V3Token as #trait_ident>::#name #turbofish(self.v3(), #(#args),*) }
            }
        };
        methods.push(quote! {
            #[inline(always)]
            #sig { #body }
        });
    }
    let tokens = quote! {
        impl #trait_ident for #token_path {
            type Repr = <archmage::X64V3Token as #trait_ident>::Repr;
            #(#methods)*
        }
    };
    format!("{tokens}\n\n")
}
