// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::{arcane, X64V3Token};
#[cfg(target_arch = "x86_64")]
#[track_caller]
#[expect(unused_variables)]
#[allow(clippy::too_many_arguments)]
#[must_use]
#[inline(always)]
fn process(token: X64V3Token, unused: f32) -> f32 {
    #[target_feature(
        enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
    )]
    #[inline]
    #[track_caller]
    fn __simd_inner_process(token: X64V3Token, unused: f32) -> f32 {
        1.0
    }
    let _: () = <X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
    unsafe { __simd_inner_process(token, unused) }
}
fn main() {}
