// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::{arcane, X64V2Token};
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[target_feature(enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b")]
#[inline]
fn __arcane_process(token: X64V2Token, a: f32) -> f32 {
    a + 1.0
}
#[cfg(target_arch = "x86_64")]
#[inline(always)]
fn process(token: X64V2Token, a: f32) -> f32 {
    let _: () = <X64V2Token>::__ARCHMAGE_ASSERT_TIER_8CCD97C6;
    unsafe { __arcane_process(token, a) }
}
fn main() {}
