// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::{arcane, Wasm128Token};
#[cfg(target_arch = "wasm32")]
#[target_feature(enable = "simd128")]
#[inline]
fn process(token: Wasm128Token, a: f32) -> f32 {
    a + 1.0
}
fn main() {}
