// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::{arcane, NeonToken};
#[cfg(target_arch = "aarch64")]
#[doc(hidden)]
#[target_feature(enable = "neon")]
#[inline]
fn __arcane_process(token: NeonToken, a: f32) -> f32 {
    a + 1.0
}
#[cfg(target_arch = "aarch64")]
#[inline(always)]
fn process(token: NeonToken, a: f32) -> f32 {
    let _: () = <NeonToken>::__ARCHMAGE_ASSERT_TIER_72CB52B2;
    unsafe { __arcane_process(token, a) }
}
fn main() {}
