//! Token-gated SIMD types with natural operators.
//!
//! This module re-exports all generated SIMD types from `generated/`.
//! The actual implementations are auto-generated by `cargo xtask generate`.
//!
//! ## Usage
//!
//! ```ignore
//! use magetypes::simd::*;
//! use archmage::{SimdToken, X64V3Token};
//!
//! if let Some(token) = X64V3Token::summon() {
//!     let a = f32x8::splat(token, 1.0);
//!     let b = f32x8::splat(token, 2.0);
//!     let c = a + b;
//! }
//! ```

// All generated code lives in the generated/ subfolder
mod generated;

// Scalar polyfill types (f32x1, i32x1, etc.) for #[magetypes] fallback
pub mod scalar;

// Re-export everything from generated module
pub use generated::*;

// Re-export scalar types
pub use scalar::*;

// ============================================================================
// Strategy-pattern generic SIMD types (Phase 1)
//
// These coexist with the old per-platform types above. The generic types
// live in `backends`, `impls`, and `generic` submodules.
// ============================================================================

/// Backend traits that define SIMD operations per token type.
pub mod backends;

/// Backend trait implementations for each token type.
mod impls;

/// Generic SIMD types parameterized by backend (e.g., `generic::f32x8<x64v3>`).
pub mod generic;
