// @generated by xtask expand_gen
use archmage::{ScalarToken, rite};
#[rite(v3, neon, wasm128, scalar, default)]
fn compute(_t: ScalarToken, data: &[f32; 4]) -> f32 { data.iter().sum() }
fn main() {}
