// @generated by xtask expand_gen
use archmage::{arcane, incant, X64V3Token, X64V4Token, NeonToken, ScalarToken};
#[arcane] fn inner_v4(_t: X64V4Token, x: f32) -> f32 { x * 4.0 }
#[arcane] fn inner_v3(_t: X64V3Token, x: f32) -> f32 { x * 2.0 }
#[arcane] fn inner_neon(_t: NeonToken, x: f32) -> f32 { x * 2.0 }
fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }
fn dispatch(x: f32) -> f32 { incant!(inner(Token, x), [v3, scalar]) }
fn main() {}
