// @generated by xtask expand_gen
use archmage::{arcane, incant, X64V3Token, ScalarToken};
#[arcane] fn inner_v3(x: f32, _t: X64V3Token) -> f32 { x * 2.0 }
fn inner_scalar(x: f32, _t: ScalarToken) -> f32 { x }
fn dispatch(x: f32) -> f32 { incant!(inner(x, Token), [v3, scalar]) }
fn main() {}
