// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
struct S {
    k: f32,
}
impl S {
    fn probe(x: f32) -> f32 {
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V3Token::summon() {
                return probe_v3(__t, x);
            }
        }
        probe_scalar(archmage::ScalarToken, x)
    }
    #[cfg(target_arch = "x86_64")]
    #[allow(dead_code)]
    #[archmage::arcane]
    fn probe_v3(_token: archmage::X64V3Token, x: f32) -> f32 {
        Self::offset() + x
    }
    #[allow(dead_code)]
    fn probe_scalar(_token: archmage::ScalarToken, x: f32) -> f32 {
        Self::offset() + x
    }
    fn offset() -> f32 {
        1.0
    }
}
fn main() {}
