// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
struct Filter {
    cutoff: f32,
}
trait Process {
    fn process(&self, data: &[f32; 4]) -> f32;
}
impl Process for Filter {
    fn process(&self, data: &[f32; 4]) -> f32 {
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V4Token::summon() {
                return self.process_v4(__t, data);
            }
            if let Some(__t) = archmage::X64V3Token::summon() {
                return self.process_v3(__t, data);
            }
        }
        #[cfg(target_arch = "aarch64")]
        {
            if let Some(__t) = archmage::NeonToken::summon() {
                return self.process_neon(__t, data);
            }
        }
        #[cfg(target_arch = "wasm32")]
        {
            if let Some(__t) = archmage::Wasm128Token::summon() {
                return self.process_wasm128(__t, data);
            }
        }
        self.process_scalar(archmage::ScalarToken, data)
    }
    #[cfg(target_arch = "x86_64")]
    #[allow(dead_code)]
    #[inline(always)]
    fn process_v4(&self, _token: archmage::X64V4Token, data: &[f32; 4]) -> f32 {
        #[target_feature(
            enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe,pclmulqdq,aes,avx512f,avx512bw,avx512cd,avx512dq,avx512vl"
        )]
        #[inline]
        fn __simd_inner_process_v4(
            _self: &Filter,
            _token: archmage::X64V4Token,
            data: &[f32; 4],
        ) -> f32 {
            let mut sum = 0.0f32;
            for &x in data {
                if x > _self.cutoff {
                    sum += x;
                }
            }
            sum
        }
        let _: () = <archmage::X64V4Token>::__ARCHMAGE_ASSERT_TIER_FE1B900C;
        unsafe { __simd_inner_process_v4(self, _token, data) }
    }
    #[cfg(target_arch = "x86_64")]
    #[allow(dead_code)]
    #[inline(always)]
    fn process_v3(&self, _token: archmage::X64V3Token, data: &[f32; 4]) -> f32 {
        #[target_feature(
            enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
        )]
        #[inline]
        fn __simd_inner_process_v3(
            _self: &Filter,
            _token: archmage::X64V3Token,
            data: &[f32; 4],
        ) -> f32 {
            let mut sum = 0.0f32;
            for &x in data {
                if x > _self.cutoff {
                    sum += x;
                }
            }
            sum
        }
        let _: () = <archmage::X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
        unsafe { __simd_inner_process_v3(self, _token, data) }
    }
    #[cfg(target_arch = "aarch64")]
    #[allow(dead_code)]
    #[inline(always)]
    fn process_neon(&self, _token: archmage::NeonToken, data: &[f32; 4]) -> f32 {
        #[target_feature(enable = "neon")]
        #[inline]
        fn __simd_inner_process_neon(
            _self: &Filter,
            _token: archmage::NeonToken,
            data: &[f32; 4],
        ) -> f32 {
            let mut sum = 0.0f32;
            for &x in data {
                if x > _self.cutoff {
                    sum += x;
                }
            }
            sum
        }
        let _: () = <archmage::NeonToken>::__ARCHMAGE_ASSERT_TIER_72CB52B2;
        unsafe { __simd_inner_process_neon(self, _token, data) }
    }
    #[cfg(target_arch = "wasm32")]
    #[target_feature(enable = "simd128")]
    #[inline]
    #[allow(dead_code)]
    fn process_wasm128(&self, _token: archmage::Wasm128Token, data: &[f32; 4]) -> f32 {
        let _self = self;
        let mut sum = 0.0f32;
        for &x in data {
            if x > _self.cutoff {
                sum += x;
            }
        }
        sum
    }
    #[allow(dead_code)]
    fn process_scalar(&self, _token: archmage::ScalarToken, data: &[f32; 4]) -> f32 {
        let _self = self;
        let mut sum = 0.0f32;
        for &x in data {
            if x > _self.cutoff {
                sum += x;
            }
        }
        sum
    }
}
fn main() {}
