// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
struct Filter {
    cutoff: f32,
}
trait Process {
    fn process(&self, data: &[f32; 4]) -> f32;
}
impl Process for Filter {
    fn process(&self, data: &[f32; 4]) -> f32 {
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V4Token::summon() {
                return self.process_v4(__t, data);
            }
            if let Some(__t) = archmage::X64V3Token::summon() {
                return self.process_v3(__t, data);
            }
        }
        #[cfg(target_arch = "aarch64")]
        {
            if let Some(__t) = archmage::NeonToken::summon() {
                return self.process_neon(__t, data);
            }
        }
        #[cfg(target_arch = "wasm32")]
        {
            if let Some(__t) = archmage::Wasm128Token::summon() {
                return self.process_wasm128(__t, data);
            }
        }
        self.process_scalar(archmage::ScalarToken, data)
    }
    #[cfg(target_arch = "x86_64")]
    #[allow(dead_code)]
    #[archmage::arcane(_self = Filter)]
    fn process_v4(&self, _token: archmage::X64V4Token, data: &[f32; 4]) -> f32 {
        let mut sum = 0.0f32;
        for &x in data {
            if x > _self.cutoff {
                sum += x;
            }
        }
        sum
    }
    #[cfg(target_arch = "x86_64")]
    #[allow(dead_code)]
    #[archmage::arcane(_self = Filter)]
    fn process_v3(&self, _token: archmage::X64V3Token, data: &[f32; 4]) -> f32 {
        let mut sum = 0.0f32;
        for &x in data {
            if x > _self.cutoff {
                sum += x;
            }
        }
        sum
    }
    #[cfg(target_arch = "aarch64")]
    #[allow(dead_code)]
    #[archmage::arcane(_self = Filter)]
    fn process_neon(&self, _token: archmage::NeonToken, data: &[f32; 4]) -> f32 {
        let mut sum = 0.0f32;
        for &x in data {
            if x > _self.cutoff {
                sum += x;
            }
        }
        sum
    }
    #[cfg(target_arch = "wasm32")]
    #[allow(dead_code)]
    #[archmage::arcane(_self = Filter)]
    fn process_wasm128(&self, _token: archmage::Wasm128Token, data: &[f32; 4]) -> f32 {
        let mut sum = 0.0f32;
        for &x in data {
            if x > _self.cutoff {
                sum += x;
            }
        }
        sum
    }
    #[allow(dead_code)]
    fn process_scalar(&self, _token: archmage::ScalarToken, data: &[f32; 4]) -> f32 {
        let _self = self;
        let mut sum = 0.0f32;
        for &x in data {
            if x > _self.cutoff {
                sum += x;
            }
        }
        sum
    }
}
fn main() {}
