// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::prelude::*;
struct S {
    k: f32,
}
impl S {
    #[cfg(target_arch = "x86_64")]
    #[archmage::arcane]
    fn probe_v3(token: archmage::X64V3Token, x: f32) -> f32 {
        let _ = token;
        x
    }
    fn probe_scalar(token: archmage::ScalarToken, x: f32) -> f32 {
        let _ = token;
        x
    }
}
fn main() {}
