// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::prelude::*;
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn __arcane_inner_v3(__archmage_token: X64V3Token, x: u32) -> u32 {
    x + 1
}
#[cfg(target_arch = "x86_64")]
#[cfg(feature = "gated")]
#[inline(always)]
fn inner_v3(__archmage_arg_0: X64V3Token, x: u32) -> u32 {
    let _: () = <X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
    unsafe { __arcane_inner_v3(__archmage_arg_0, x) }
}
fn inner_scalar(_: ScalarToken, x: u32) -> u32 {
    x
}
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn __arcane_outer(t: X64V3Token, x: u32) -> u32 {
    '__incant_rewrite: {
        use archmage::SimdToken;
        #[cfg(feature = "gated")]
        {
            break '__incant_rewrite inner_v3(t, x);
        }
        inner_scalar(archmage::ScalarToken, x)
    }
}
#[cfg(target_arch = "x86_64")]
#[inline(always)]
fn outer(t: X64V3Token, x: u32) -> u32 {
    let _: () = <X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
    unsafe { __arcane_outer(t, x) }
}
fn main() {}
