// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::prelude::*;
struct S {
    k: f32,
}
trait Work {
    fn merge(&self, token: X64V3Token, other: &Self) -> f32;
}
impl Work for S {
    #[cfg(target_arch = "x86_64")]
    #[inline(always)]
    fn merge(&self, token: X64V3Token, other: &Self) -> f32 {
        #[target_feature(
            enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
        )]
        #[inline]
        fn __simd_inner_merge(_self: &S, token: X64V3Token, other: &S) -> f32 {
            let _ = token;
            _self.k + other.k
        }
        let _: () = <X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
        unsafe { __simd_inner_merge(self, token, other) }
    }
}
fn main() {
    if let Some(token) = X64V3Token::summon() {
        let (s, t) = (S { k: 1.0 }, S { k: 2.0 });
        let _: f32 = s.merge(token, &t);
    }
}
