// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
struct S {
    k: f32,
}
trait Work {
    fn run(&self, x: f32) -> f32;
}
impl Work for S {
    fn run(&self, x: f32) -> f32 {
        #[cfg(target_arch = "x86_64")]
        #[allow(dead_code)]
        #[archmage::arcane]
        fn run_v3(_self: &S, _token: archmage::X64V3Token, x: f32) -> f32 {
            _self.k + x
        }
        #[allow(dead_code)]
        fn run_scalar(_self: &S, _token: archmage::ScalarToken, x: f32) -> f32 {
            _self.k + x
        }
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V3Token::summon() {
                return run_v3(self, __t, x);
            }
        }
        run_scalar(self, archmage::ScalarToken, x)
    }
}
fn main() {
    let _ = S { k: 1.0 }.run(2.0);
}
