// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
struct S {
    k: f32,
}
trait Work {
    fn merge(&self, other: &Self) -> f32;
}
impl Work for S {
    fn merge(&self, other: &Self) -> f32 {
        #[cfg(target_arch = "x86_64")]
        #[allow(dead_code)]
        #[archmage::arcane]
        fn merge_v3(_self: &S, _token: archmage::X64V3Token, other: &S) -> f32 {
            _self.k + other.k
        }
        #[allow(dead_code)]
        fn merge_scalar(_self: &S, _token: archmage::ScalarToken, other: &S) -> f32 {
            _self.k + other.k
        }
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V3Token::summon() {
                return merge_v3(self, __t, other);
            }
        }
        merge_scalar(self, archmage::ScalarToken, other)
    }
}
fn main() {
    let (s, t) = (S { k: 1.0 }, S { k: 2.0 });
    let _: f32 = s.merge(&t);
}
