// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
struct S {
    k: f32,
}
trait Work {
    fn pick<'a>(&'a self, other: &'a f32) -> &'a f32;
}
impl Work for S {
    fn pick<'a>(&'a self, other: &'a f32) -> &'a f32 {
        #[cfg(target_arch = "x86_64")]
        #[allow(dead_code)]
        #[archmage::arcane]
        fn pick_v3<'a>(
            _self: &'a S,
            _token: archmage::X64V3Token,
            other: &'a f32,
        ) -> &'a f32 {
            if _self.k > *other { &_self.k } else { other }
        }
        #[allow(dead_code)]
        fn pick_scalar<'a>(
            _self: &'a S,
            _token: archmage::ScalarToken,
            other: &'a f32,
        ) -> &'a f32 {
            if _self.k > *other { &_self.k } else { other }
        }
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V3Token::summon() {
                return pick_v3(self, __t, other);
            }
        }
        pick_scalar(self, archmage::ScalarToken, other)
    }
}
fn main() {
    let (s, t) = (S { k: 1.0 }, S { k: 2.0 });
    let _: f32 = *s.pick(&t.k);
}
