// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
struct S {
    k: f32,
}
trait Work {
    fn run(&self, x: f32) -> f32;
}
impl Work for S {
    fn run(&self, x: f32) -> f32 {
        #[cfg(target_arch = "x86_64")]
        #[doc(hidden)]
        #[allow(dead_code)]
        #[target_feature(
            enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
        )]
        #[inline]
        fn __arcane_run_v3(_self: &S, _token: archmage::X64V3Token, x: f32) -> f32 {
            struct Inner(f32);
            impl Inner {
                fn value(&self) -> f32 {
                    self.0
                }
            }
            _self.k + Inner(x).value()
        }
        #[cfg(target_arch = "x86_64")]
        #[allow(dead_code)]
        #[inline(always)]
        fn run_v3(_self: &S, _token: archmage::X64V3Token, x: f32) -> f32 {
            let _: () = <archmage::X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
            unsafe { __arcane_run_v3(_self, _token, x) }
        }
        #[allow(dead_code)]
        fn run_scalar(_self: &S, _token: archmage::ScalarToken, x: f32) -> f32 {
            struct Inner(f32);
            impl Inner {
                fn value(&self) -> f32 {
                    self.0
                }
            }
            _self.k + Inner(x).value()
        }
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V3Token::summon() {
                return run_v3(self, __t, x);
            }
        }
        run_scalar(self, archmage::ScalarToken, x)
    }
}
fn main() {
    let (s, t) = (S { k: 1.0 }, S { k: 2.0 });
    let _: f32 = s.run(t.k);
}
