// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
struct S {
    k: f32,
}
trait Work {
    fn consume(self: Box<Self>) -> f32;
}
impl Work for S {
    fn consume(self: Box<Self>) -> f32 {
        #[cfg(target_arch = "x86_64")]
        #[allow(dead_code)]
        #[archmage::arcane]
        fn consume_v3(_self: Box<S>, _token: archmage::X64V3Token) -> f32 {
            _self.k
        }
        #[allow(dead_code)]
        fn consume_scalar(_self: Box<S>, _token: archmage::ScalarToken) -> f32 {
            _self.k
        }
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V3Token::summon() {
                return consume_v3(self, __t);
            }
        }
        consume_scalar(self, archmage::ScalarToken)
    }
}
fn main() {
    let (s, t) = (S { k: 1.0 }, S { k: 2.0 });
    let _: f32 = Box::new(s).consume();
}
