// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
struct S {
    k: f32,
}
trait Work {
    fn consume(self: Box<Self>) -> f32;
}
impl Work for S {
    fn consume(self: Box<Self>) -> f32 {
        #[cfg(target_arch = "x86_64")]
        #[doc(hidden)]
        #[allow(dead_code)]
        #[target_feature(
            enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
        )]
        #[inline]
        fn __arcane_consume_v3(_self: Box<S>, _token: archmage::X64V3Token) -> f32 {
            _self.k
        }
        #[cfg(target_arch = "x86_64")]
        #[allow(dead_code)]
        #[inline(always)]
        fn consume_v3(_self: Box<S>, _token: archmage::X64V3Token) -> f32 {
            let _: () = <archmage::X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
            unsafe { __arcane_consume_v3(_self, _token) }
        }
        #[allow(dead_code)]
        fn consume_scalar(_self: Box<S>, _token: archmage::ScalarToken) -> f32 {
            _self.k
        }
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V3Token::summon() {
                return consume_v3(self, __t);
            }
        }
        consume_scalar(self, archmage::ScalarToken)
    }
}
fn main() {
    let (s, t) = (S { k: 1.0 }, S { k: 2.0 });
    let _: f32 = Box::new(s).consume();
}
