// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
struct S {
    k: f32,
}
impl S {
    fn probe(x: f32) -> f32 {
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V3Token::summon() {
                return Self::probe_v3(__t, x);
            }
        }
        Self::probe_scalar(archmage::ScalarToken, x)
    }
    #[cfg(target_arch = "x86_64")]
    #[doc(hidden)]
    #[allow(dead_code)]
    #[target_feature(
        enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
    )]
    #[inline]
    fn __arcane_probe_v3(_token: archmage::X64V3Token, x: f32) -> f32 {
        Self::offset() + x
    }
    #[cfg(target_arch = "x86_64")]
    #[allow(dead_code)]
    #[inline(always)]
    fn probe_v3(_token: archmage::X64V3Token, x: f32) -> f32 {
        let _: () = <archmage::X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
        unsafe { Self::__arcane_probe_v3(_token, x) }
    }
    #[allow(dead_code)]
    fn probe_scalar(_token: archmage::ScalarToken, x: f32) -> f32 {
        Self::offset() + x
    }
    fn offset() -> f32 {
        1.0
    }
}
fn main() {}
