// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::prelude::*;
struct S {
    k: f32,
}
impl S {
    #[cfg(target_arch = "x86_64")]
    #[archmage::arcane(in_impl)]
    fn probe_v3(token: archmage::X64V3Token, x: f32) -> f32 {
        let _ = token;
        Self::offset() + x
    }
    fn probe_scalar(token: archmage::ScalarToken, x: f32) -> f32 {
        let _ = token;
        Self::offset() + x
    }
    fn offset() -> f32 {
        1.0
    }
}
fn main() {}
