// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::prelude::*;
#[cfg(target_arch = "x86_64")]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe,avx512f,avx512bw,avx512cd,avx512dq,avx512vl"
)]
#[inline]
fn probe<T>(token: T, x: f32) -> f32
where
    T: HasX64V4,
{
    {
        #[inline(always)]
        const fn __archmage_assert_tier_trait<__T: ?Sized + ::archmage::HasX64V4>(
            _: &__T,
        ) {}
        __archmage_assert_tier_trait(&token);
    }
    let _ = token;
    let _ = X64V3Token::from_context();
    x
}
fn main() {}
