// @generated by xtask expand_gen
use archmage::autoversion;
struct S { k: f32 }
impl S {
    #[autoversion(v3, scalar)]
    fn probe(x: f32) -> f32 { Self::offset() + x }
    fn offset() -> f32 { 1.0 }
}
fn main() {}
