// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
#[allow(deprecated)]
use archmage::{autoversion, SimdToken};
#[allow(deprecated)]
fn process(data: &[f32; 4]) -> f32 {
    {
        #[deprecated(
            note = "SimdToken parameter in #[autoversion] is deprecated — remove it (tokenless) or use ScalarToken for incant! nesting"
        )]
        #[allow(dead_code)]
        const SIMDTOKEN_DEPRECATED: () = ();
        let _ = SIMDTOKEN_DEPRECATED;
    }
    #[allow(unused_imports)]
    use archmage::SimdToken;
    #[cfg(target_arch = "x86_64")]
    {
        if let Some(__t) = archmage::X64V4Token::summon() {
            return process_v4(__t, data);
        }
        if let Some(__t) = archmage::X64V3Token::summon() {
            return process_v3(__t, data);
        }
    }
    #[cfg(target_arch = "aarch64")]
    {
        if let Some(__t) = archmage::NeonToken::summon() {
            return process_neon(__t, data);
        }
    }
    #[cfg(target_arch = "wasm32")]
    {
        if let Some(__t) = archmage::Wasm128Token::summon() {
            return process_wasm128(__t, data);
        }
    }
    process_scalar(archmage::ScalarToken, data)
}
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[allow(dead_code)]
#[allow(deprecated)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe,pclmulqdq,aes,avx512f,avx512bw,avx512cd,avx512dq,avx512vl"
)]
#[inline]
fn __arcane_process_v4(_token: archmage::X64V4Token, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[cfg(target_arch = "x86_64")]
#[allow(dead_code)]
#[allow(deprecated)]
#[inline(always)]
fn process_v4(_token: archmage::X64V4Token, data: &[f32; 4]) -> f32 {
    let _: () = <archmage::X64V4Token>::__ARCHMAGE_ASSERT_TIER_FE1B900C;
    unsafe { __arcane_process_v4(_token, data) }
}
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[allow(dead_code)]
#[allow(deprecated)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn __arcane_process_v3(_token: archmage::X64V3Token, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[cfg(target_arch = "x86_64")]
#[allow(dead_code)]
#[allow(deprecated)]
#[inline(always)]
fn process_v3(_token: archmage::X64V3Token, data: &[f32; 4]) -> f32 {
    let _: () = <archmage::X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
    unsafe { __arcane_process_v3(_token, data) }
}
#[cfg(target_arch = "aarch64")]
#[doc(hidden)]
#[allow(dead_code)]
#[allow(deprecated)]
#[target_feature(enable = "neon")]
#[inline]
fn __arcane_process_neon(_token: archmage::NeonToken, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[cfg(target_arch = "aarch64")]
#[allow(dead_code)]
#[allow(deprecated)]
#[inline(always)]
fn process_neon(_token: archmage::NeonToken, data: &[f32; 4]) -> f32 {
    let _: () = <archmage::NeonToken>::__ARCHMAGE_ASSERT_TIER_72CB52B2;
    unsafe { __arcane_process_neon(_token, data) }
}
#[cfg(target_arch = "wasm32")]
#[target_feature(enable = "simd128")]
#[inline]
#[allow(dead_code)]
#[allow(deprecated)]
fn process_wasm128(_token: archmage::Wasm128Token, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[allow(dead_code)]
#[allow(deprecated)]
fn process_scalar(_token: archmage::ScalarToken, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
fn main() {}
