// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::{autoversion, arcane, incant, X64V3Token, X64V4Token, ScalarToken};
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe,pclmulqdq,aes,avx512f,avx512bw,avx512cd,avx512dq,avx512vl"
)]
#[inline]
fn __arcane_inner_v4(_t: X64V4Token, x: f32) -> f32 {
    x * 4.0
}
#[cfg(target_arch = "x86_64")]
#[inline(always)]
fn inner_v4(_t: X64V4Token, x: f32) -> f32 {
    let _: () = <X64V4Token>::__ARCHMAGE_ASSERT_TIER_FE1B900C;
    unsafe { __arcane_inner_v4(_t, x) }
}
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn __arcane_inner_v3(_t: X64V3Token, x: f32) -> f32 {
    x * 2.0
}
#[cfg(target_arch = "x86_64")]
#[inline(always)]
fn inner_v3(_t: X64V3Token, x: f32) -> f32 {
    let _: () = <X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
    unsafe { __arcane_inner_v3(_t, x) }
}
fn inner_scalar(_t: ScalarToken, x: f32) -> f32 {
    x
}
fn outer(x: f32) -> f32 {
    #[allow(unused_imports)]
    use archmage::SimdToken;
    #[cfg(target_arch = "x86_64")]
    {
        if let Some(__t) = archmage::X64V3Token::summon() {
            return outer_v3(__t, x);
        }
    }
    outer_scalar(archmage::ScalarToken, x)
}
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[allow(dead_code)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn __arcane_outer_v3(_token: archmage::X64V3Token, x: f32) -> f32 {
    '__incant_rewrite: {
        use archmage::SimdToken;
        #[cfg(feature = "avx512")]
        {
            if let Some(__t) = archmage::X64V4Token::summon() {
                break '__incant_rewrite inner_v4(__t, x);
            }
        }
        inner_v3(_token, x)
    }
}
#[cfg(target_arch = "x86_64")]
#[allow(dead_code)]
#[inline(always)]
fn outer_v3(_token: archmage::X64V3Token, x: f32) -> f32 {
    let _: () = <archmage::X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
    unsafe { __arcane_outer_v3(_token, x) }
}
#[allow(dead_code)]
fn outer_scalar(_token: archmage::ScalarToken, x: f32) -> f32 {
    '__incant: {
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            #[cfg(feature = "avx512")]
            {
                if let Some(__t) = archmage::X64V4Token::summon() {
                    break '__incant inner_v4(__t, x);
                }
            }
            if let Some(__t) = archmage::X64V3Token::summon() {
                break '__incant inner_v3(__t, x);
            }
        }
        inner_scalar(archmage::ScalarToken, x)
    }
}
fn main() {}
