//! Every macro signature shape the local consumer crates use, one module per
//! shape, with placeholder types and stub bodies: the test is that the macros
//! still accept and expand each shape. Generated by `xtask/harvest_shapes.py`
//! from snapshots of 40 crates (2026-10-07); regenerate rather than edit.
//! Each module names the files the shape was harvested from.
#![allow(
    dead_code,
    unused_variables,
    unused_imports,
    unexpected_cfgs,
    clippy::all,
    deprecated
)]

use archmage::prelude::*;
use magetypes::simd::backends::*;
use magetypes::simd::*;

/// Placeholder for every consumer-defined type.
#[derive(Clone, Copy, Default, Debug, PartialEq)]
pub struct P;

mod h000 {
    use super::*;
    // fn(tok:NeonToken, p)
    // zen/zenmetrics/crates/vmaf/src/adm.rs
    // zen/zenmetrics/crates/vmaf/src/cambi.rs
    // zen/zenmetrics/crates/vmaf/src/speed.rs
    #[arcane(import_intrinsics)]
    fn shape(p0: NeonToken, p1: &P) {
        todo!()
    }
}

mod h001 {
    use super::*;
    // fn(tok:NeonToken, p) -> P
    // zen/zenmetrics/crates/vmaf/src/speed.rs
    #[arcane(import_intrinsics)]
    fn shape(
        p0: NeonToken,
        p1: &[f32],
        p2: f64,
        p3: f64,
        p4: usize,
        p5: usize,
        p6: usize,
        p7: usize,
        p8: usize,
        p9: usize,
        p10: usize,
    ) -> f64 {
        todo!()
    }
}

mod h002 {
    use super::*;
    // fn(tok:X64V3Token, p)
    // zen/zenmetrics/crates/vmaf/src/adm.rs
    // zen/zenmetrics/crates/vmaf/src/cambi.rs
    // zen/zenmetrics/crates/vmaf/src/lib.rs
    // zen/zenmetrics/crates/vmaf/src/speed.rs
    // zen/zenmetrics/crates/vmaf/src/vif.rs
    #[arcane(import_intrinsics)]
    fn shape(p0: X64V3Token, p1: &mut [u16], p2: bool) {
        todo!()
    }
}

mod h003 {
    use super::*;
    // fn(tok:X64V3Token, p) -> P
    // zen/zenmetrics/crates/vmaf/src/lib.rs
    // zen/zenmetrics/crates/vmaf/src/speed.rs
    // zen/zenmetrics/crates/vmaf/src/vif.rs
    #[arcane(import_intrinsics)]
    fn shape(p0: X64V3Token, p1: &[i32], p2: usize) -> u64 {
        todo!()
    }
}

#[cfg(feature = "avx512")]
mod h004 {
    use super::*;
    // fn(tok:X64V4Token, p)
    // zen/zenmetrics/crates/vmaf/src/adm.rs
    // zen/zenmetrics/crates/vmaf/src/lib.rs
    // zen/zenmetrics/crates/vmaf/src/vif.rs
    #[arcane(import_intrinsics)]
    fn shape(p0: X64V4Token, p1: &[&[u16]; 5], p2: &[&[u16]; 5], p3: &mut [i32; 32]) {
        todo!()
    }
}

#[cfg(feature = "avx512")]
mod h005 {
    use super::*;
    // fn(tok:X64V4Token, p) -> P
    // zen/zenmetrics/crates/vmaf/src/adm.rs
    // zen/zenmetrics/crates/vmaf/src/lib.rs
    // zen/zenmetrics/crates/vmaf/src/speed.rs
    // zen/zenmetrics/crates/vmaf/src/vif.rs
    #[arcane(import_intrinsics)]
    fn shape(p0: X64V4Token, p1: &[i32], p2: usize) -> u64 {
        todo!()
    }
}

#[cfg(feature = "avx512")]
mod h006 {
    use super::*;
    // fn<const>(tok:X64V4Token, p)
    // zen/zenmetrics/crates/vmaf/src/adm.rs
    #[arcane(import_intrinsics)]
    fn shape<const SHIFT: u32>(
        p0: X64V4Token,
        p1: &[i32; 8],
        p2: &[i32; 8],
        p3: &[i32; 8],
        p4: &[i32; 8],
        p5: &[i64; 4],
        p6: &[i64; 4],
        p7: i64,
        p8: &mut [i32; 8],
        p9: &mut [i32; 8],
    ) {
        todo!()
    }
}

mod h007 {
    use super::*;
    // pub fn(tok:NeonToken, p)
    // zen/zenpixels/zenpixels-convert/src/orient/pxn_neon.rs
    #[arcane(import_intrinsics)]
    pub fn shape(p0: NeonToken, p1: &P, p2: &mut P, p3: P, p4: u32, p5: u32) {
        todo!()
    }
}

mod h008 {
    use super::*;
    // pub fn(tok:NeonToken, p) -> P
    // zen/zenjpeg/zenyuv/src/neon_encode.rs
    #[arcane(import_intrinsics)]
    pub fn shape(
        p0: NeonToken,
        p1: &[u8],
        p2: &mut [u8],
        p3: &mut [u8],
        p4: &mut [u8],
        p5: usize,
        p6: &P,
    ) -> usize {
        todo!()
    }
}

mod h009 {
    use super::*;
    // pub fn(tok:Wasm128Token, p)
    // zen/zenjpeg/zenyuv/src/wasm_encode.rs
    #[arcane(import_intrinsics)]
    pub fn shape(
        p0: Wasm128Token,
        p1: &[u8],
        p2: &mut [u8],
        p3: &mut [u8],
        p4: &mut [u8],
        p5: usize,
        p6: usize,
        p7: usize,
        p8: &P,
    ) {
        todo!()
    }
}

mod h010 {
    use super::*;
    // pub fn(tok:Wasm128Token, p) -> P
    // zen/zenjpeg/zenyuv/src/wasm_encode.rs
    #[arcane(import_intrinsics)]
    pub fn shape(
        p0: Wasm128Token,
        p1: &[u8],
        p2: &mut [u8],
        p3: &mut [u8],
        p4: &mut [u8],
        p5: usize,
        p6: &P,
    ) -> usize {
        todo!()
    }
}

mod h011 {
    use super::*;
    // pub fn(tok:X64V3Token, p)
    // zen/zenpixels/zenpixels-convert/src/orient/pxn_x86.rs
    // zen/zenpixels/zenpixels-convert/src/orient/rgb3_x86.rs
    #[arcane(import_intrinsics)]
    pub fn shape(p0: X64V3Token, p1: &P, p2: &mut P, p3: P, p4: u32, p5: u32) {
        todo!()
    }
}

mod h012 {
    use super::*;
    // fn(tok:X64V3Token, p)
    // zen/mozjpeg-rs/src/simd/x86_64/entropy.rs
    #[arcane(nested)]
    fn shape(p0: X64V3Token, p1: &mut P, p2: &[i16; 8], p3: usize, p4: &P, p5: &P) {
        todo!()
    }
}

mod h013 {
    use super::*;
    // fn(tok:X64V3Token, p) -> P
    // zen/mozjpeg-rs/src/simd/x86_64/entropy.rs
    #[arcane(nested)]
    fn shape(p0: X64V3Token, p1: &[i16; 8], p2: &mut [i16; 8]) -> u64 {
        todo!()
    }
}

mod h014 {
    use super::*;
    // fn(tok:Arm64, p)
    // zen/rav1d-safe/src/safe_simd/filmgrain_arm.rs
    // zen/rav1d-safe/src/safe_simd/ipred_arm.rs
    // zen/rav1d-safe/src/safe_simd/loopfilter_arm.rs
    // zen/rav1d-safe/src/safe_simd/looprestoration_arm.rs
    // zen/rav1d-safe/src/safe_simd/mc_arm.rs
    #[arcane]
    fn shape(p0: Arm64, p1: &mut [i16], p2: i32, p3: u32) {
        todo!()
    }
}

mod h015 {
    use super::*;
    // fn(tok:Arm64, p) -> P
    // zen/rav1d-safe/src/safe_simd/cdef_arm.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_8x8.rs
    // zen/rav1d-safe/src/safe_simd/loopfilter_arm.rs
    #[arcane]
    fn shape(p0: Arm64, p1: P, p2: &mut P) -> P {
        todo!()
    }
}

mod h016 {
    use super::*;
    // fn(tok:Arm64V2Token, p)
    // imageflow-zencodecs-v2/imageflow_core/src/graphics/transpose.rs
    // imageflow/imageflow_core/src/graphics/transpose.rs
    // zen/rav1d-safe/src/safe_simd/mc_arm.rs
    #[arcane]
    fn shape(p0: Arm64V2Token, p1: &mut [i16], p2: &[u8], p3: usize, p4: &[i8; 8], p5: u8) {
        todo!()
    }
}

mod h017 {
    use super::*;
    // fn(tok:Arm64V3Token, p)
    // zen/rav1d-safe/src/safe_simd/mc_arm.rs
    #[arcane]
    fn shape(p0: Arm64V3Token, p1: &mut [i16], p2: &[u8], p3: usize, p4: &[i8; 8], p5: u8) {
        todo!()
    }
}

mod h018 {
    use super::*;
    // fn(tok:Desktop64, impl:Copy, p)
    // zen/rav1d-safe/src/safe_simd/filmgrain.rs
    #[arcane]
    fn shape(
        p0: Desktop64,
        p1: &mut impl Copy,
        p2: &P,
        p3: usize,
        p4: &[u8],
        p5: &[[i8; 8]; 4],
        p6: usize,
        p7: usize,
    ) {
        todo!()
    }
}

mod h019 {
    use super::*;
    // fn(tok:Desktop64, p)
    // zen/rav1d-safe/src/safe_simd/cdef.rs
    // zen/rav1d-safe/src/safe_simd/filmgrain.rs
    // zen/rav1d-safe/src/safe_simd/ipred.rs
    // zen/rav1d-safe/src/safe_simd/itx/part01_macros_and_2d_transforms.rs
    // zen/rav1d-safe/src/safe_simd/itx/part03_adst16_and_small_rect.rs
    // zen/rav1d-safe/src/safe_simd/itx/part04_rect_idtx_aspect.rs
    // ... and 11 more
    #[arcane]
    fn shape(p0: Desktop64, p1: &[i32; 256]) {
        todo!()
    }
}

mod h020 {
    use super::*;
    // fn(tok:Desktop64, p) -> P
    // zen/rav1d-safe/src/safe_simd/cdef.rs
    // zen/rav1d-safe/src/safe_simd/itx/part04_rect_idtx_aspect.rs
    // zen/rav1d-safe/src/safe_simd/itx/part05_tests.rs
    // zen/zenflate/src/checksum/adler32.rs
    // zen/zenjpeg/zenjpeg/src/encode/mage_simd.rs
    #[arcane]
    fn shape(p0: Desktop64, p1: P) -> f32 {
        todo!()
    }
}

mod h021 {
    use super::*;
    // fn(tok:NeonAesToken, p) -> P
    // zen/zenflate/src/checksum/crc32.rs
    #[arcane]
    fn shape(p0: NeonAesToken, p1: u32, p2: &[u8]) -> u32 {
        todo!()
    }
}

mod h022 {
    use super::*;
    // fn(tok:NeonToken, p)
    // zen/jxl-encoder/jxl-encoder/src/vardct/ac_strategy_search.rs
    // zen/jxl-encoder/jxl-encoder/src/vardct/reconstruct.rs
    // zen/linear-srgb/src/tokens/x4.rs
    // zen/ultrahdr/ultrahdr-core/benches/simd_xplat.rs
    // zen/zenjpegai/src/nn/fast/conv.rs
    // zen/zenjpegai/src/nn/fast/depthwise.rs
    // ... and 6 more
    #[arcane]
    fn shape(p0: NeonToken, p1: &mut P) {
        todo!()
    }
}

mod h023 {
    use super::*;
    // fn(tok:NeonToken, p) -> P
    // butteraugli/butteraugli/src/blur.rs
    // butteraugli/butteraugli/src/malta.rs
    // libimagequant/src/simd.rs
    // zen/butteraugli/butteraugli/src/blur.rs
    // zen/butteraugli/butteraugli/src/malta.rs
    // zen/jxl-encoder/jxl-encoder/src/vardct/ac_strategy_search.rs
    // ... and 9 more
    #[arcane]
    fn shape(p0: NeonToken, p1: &P, p2: P) -> u8 {
        todo!()
    }
}

mod h024 {
    use super::*;
    // fn(tok:Server64, p)
    // zen/rav1d-safe/src/safe_simd/cdef.rs
    // zen/rav1d-safe/src/safe_simd/ipred.rs
    // zen/rav1d-safe/src/safe_simd/itx/part02_col_1d_avx512_pmaddwd.rs
    // zen/rav1d-safe/src/safe_simd/itx/part07_32x32_64x64_dct.rs
    // zen/rav1d-safe/src/safe_simd/loopfilter.rs
    // zen/rav1d-safe/src/safe_simd/looprestoration.rs
    // ... and 1 more
    #[arcane]
    fn shape(p0: Server64, p1: &mut [i32], p2: usize, p3: usize) {
        todo!()
    }
}

mod h025 {
    use super::*;
    // fn(tok:Server64, p) -> P
    // zen/rav1d-safe/src/safe_simd/cdef.rs
    #[arcane]
    fn shape(p0: Server64, p1: &[i16; 32], p2: i16, p3: i32) -> [i16; 32] {
        todo!()
    }
}

mod h026 {
    use super::*;
    // fn(tok:Sse2Token, p) -> P
    // libimagequant/src/simd.rs
    #[arcane]
    fn shape(p0: Sse2Token, p1: &P, p2: &P) -> f32 {
        todo!()
    }
}

mod h027 {
    use super::*;
    // fn(tok:Wasm128Token, p)
    // imageflow-zencodecs-v2/imageflow_core/src/graphics/transpose.rs
    // imageflow/imageflow_core/src/graphics/transpose.rs
    // zen/jxl-encoder/jxl-encoder/src/vardct/ac_strategy_search.rs
    // zen/jxl-encoder/jxl-encoder/src/vardct/reconstruct.rs
    // zen/rav1d-safe/src/safe_simd/cdef_wasm.rs
    // zen/rav1d-safe/src/safe_simd/mc_wasm.rs
    // ... and 11 more
    #[arcane]
    fn shape(p0: Wasm128Token, p1: &mut P) {
        todo!()
    }
}

mod h028 {
    use super::*;
    // fn(tok:Wasm128Token, p) -> P
    // butteraugli/butteraugli/src/blur.rs
    // butteraugli/butteraugli/src/malta.rs
    // libimagequant/src/simd.rs
    // zen/butteraugli/butteraugli/src/blur.rs
    // zen/butteraugli/butteraugli/src/malta.rs
    // zen/jxl-encoder/jxl-encoder/src/vardct/ac_strategy_search.rs
    // ... and 6 more
    #[arcane]
    fn shape(p0: Wasm128Token, p1: &P, p2: P) -> u8 {
        todo!()
    }
}

mod h029 {
    use super::*;
    // fn(tok:X64CryptoToken, p) -> P
    // zen/zenflate/src/checksum/crc32.rs
    #[arcane]
    fn shape(p0: X64CryptoToken, p1: u64, p2: u64) -> u64 {
        todo!()
    }
}

mod h030 {
    use super::*;
    // fn(tok:X64V1Token, p)
    // zen/rav1d-safe/src/msac.rs
    // zen/zenpng/src/simd/avg.rs
    // zen/zenpng/src/simd/sub.rs
    // zen/zenpng/src/simd/up.rs
    // zen/zenwebp/src/encoder/vp8l/transforms.rs
    #[arcane]
    fn shape(p0: X64V1Token, p1: &mut [u8]) {
        todo!()
    }
}

mod h031 {
    use super::*;
    // fn(tok:X64V1Token, p) -> P
    // zen/zenwebp/src/encoder/vp8l/transforms.rs
    #[arcane]
    fn shape(p0: X64V1Token, p1: &[u32; 256], p2: &[u32; 256]) -> u64 {
        todo!()
    }
}

mod h032 {
    use super::*;
    // fn(tok:X64V2Token, p)
    // zen/zenpng/src/simd/paeth.rs
    #[arcane]
    fn shape(p0: X64V2Token, p1: &mut [u8], p2: &[u8]) {
        todo!()
    }
}

mod h033 {
    use super::*;
    // fn(tok:X64V3Token, p)
    // garb/benches/deinterleave.rs
    // hdr-research/planar-bench/src/lib.rs
    // imageflow-zencodecs-v2/imageflow_core/src/graphics/transpose.rs
    // imageflow/imageflow_core/src/graphics/transpose.rs
    // zen/heic/heic-core/src/color_convert.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct16.rs
    // ... and 40 more
    #[arcane]
    fn shape(p0: X64V3Token, p1: &P) {
        todo!()
    }
}

mod h034 {
    use super::*;
    // fn(tok:X64V3Token, p) -> P
    // butteraugli/butteraugli/src/blur.rs
    // butteraugli/butteraugli/src/malta.rs
    // zen/butteraugli/butteraugli/src/blur.rs
    // zen/butteraugli/butteraugli/src/malta.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct16.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dequant.rs
    // ... and 25 more
    #[arcane]
    fn shape(p0: X64V3Token, p1: P) -> P {
        todo!()
    }
}

mod h035 {
    use super::*;
    // fn(tok:X64V4Token, p)
    // butteraugli/butteraugli/src/blur_iir.rs
    // zen/butteraugli/butteraugli/src/blur_iir.rs
    // zen/linear-srgb/benches/tf_bench.rs
    // zen/linear-srgb/src/tokens/x16.rs
    // zen/zenjpeg/zenjpeg/src/encode/mage_simd.rs
    // zen/zenjpeg/zenjpeg/src/quant/aq/simd.rs
    // ... and 9 more
    #[arcane]
    fn shape(p0: X64V4Token, p1: &mut P) {
        todo!()
    }
}

mod h036 {
    use super::*;
    // fn(tok:X64V4Token, p) -> P
    // butteraugli/butteraugli/src/blur.rs
    // butteraugli/butteraugli/src/malta.rs
    // zen/butteraugli/butteraugli/src/blur.rs
    // zen/butteraugli/butteraugli/src/malta.rs
    // zen/linear-srgb/src/tokens/x16.rs
    // zen/zenflate/src/checksum/adler32.rs
    // ... and 6 more
    #[arcane]
    fn shape(p0: X64V4Token, p1: u32, p2: &[u8]) -> u32 {
        todo!()
    }
}

mod h037 {
    use super::*;
    // fn(tok:X64V4xToken, p)
    // zen/rav1d-safe/src/safe_simd/ipred.rs
    // zen/zensim/zensim/src/blur.rs
    // zen/zensim/zensim/src/color.rs
    // zen/zensr/crates/zensr-micro/src/simd.rs
    #[arcane]
    fn shape(p0: X64V4xToken, p1: &mut [f32]) {
        todo!()
    }
}

mod h038 {
    use super::*;
    // fn(tok:X64V4xToken, p) -> P
    // zen/zenflate/src/checksum/adler32.rs
    // zen/zenflate/src/checksum/crc32.rs
    // zen/zensim/zensim/src/fused.rs
    #[arcane]
    fn shape(p0: X64V4xToken, p1: u32, p2: &[u8]) -> u32 {
        todo!()
    }
}

mod h039 {
    use super::*;
    // fn(wild:tok:NeonToken) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/aarch64/neon.rs
    #[arcane]
    fn shape(_: NeonToken) -> P {
        todo!()
    }
}

mod h040 {
    use super::*;
    // fn(wild:tok:NeonToken, p)
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/aarch64/neon.rs
    #[arcane]
    fn shape(_: NeonToken, p1: &P) {
        todo!()
    }
}

mod h041 {
    use super::*;
    // fn(wild:tok:NeonToken, p) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/aarch64/neon.rs
    #[arcane]
    fn shape(_: NeonToken, p1: u8) -> P {
        todo!()
    }
}

mod h042 {
    use super::*;
    // fn(wild:tok:X64V2Token) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/sse42.rs
    #[arcane]
    fn shape(_: X64V2Token) -> P {
        todo!()
    }
}

mod h043 {
    use super::*;
    // fn(wild:tok:X64V2Token, p)
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/sse42.rs
    #[arcane]
    fn shape(_: X64V2Token, p1: &P) {
        todo!()
    }
}

mod h044 {
    use super::*;
    // fn(wild:tok:X64V2Token, p) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/sse42.rs
    #[arcane]
    fn shape(_: X64V2Token, p1: u8) -> P {
        todo!()
    }
}

mod h045 {
    use super::*;
    // fn(wild:tok:X64V3Token) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/avx.rs
    #[arcane]
    fn shape(_: X64V3Token) -> P {
        todo!()
    }
}

mod h046 {
    use super::*;
    // fn(wild:tok:X64V3Token, p)
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/avx.rs
    #[arcane]
    fn shape(_: X64V3Token, p1: &P) {
        todo!()
    }
}

mod h047 {
    use super::*;
    // fn(wild:tok:X64V3Token, p) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/avx.rs
    #[arcane]
    fn shape(_: X64V3Token, p1: u8) -> P {
        todo!()
    }
}

mod h048 {
    use super::*;
    // fn(wild:tok:X64V4Token) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/avx512.rs
    #[arcane]
    fn shape(_: X64V4Token) -> P {
        todo!()
    }
}

mod h049 {
    use super::*;
    // fn(wild:tok:X64V4Token, p)
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/avx512.rs
    #[arcane]
    fn shape(_: X64V4Token, p1: &P) {
        todo!()
    }
}

mod h050 {
    use super::*;
    // fn(wild:tok:X64V4Token, p) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/avx512.rs
    #[arcane]
    fn shape(_: X64V4Token, p1: u8) -> P {
        todo!()
    }
}

mod h051 {
    use super::*;
    // fn<T,const,const>(tok:NeonToken, gen:U, gen:U, gen:U, p) -> P
    // moxcms-safe/src/conversions/neon/interpolator.rs
    // moxcms-safe/src/conversions/neon/interpolator_q0_15.rs
    #[arcane]
    fn shape<U, const GRID_SIZE: usize, const BINS: usize>(
        p0: NeonToken,
        p1: U,
        p2: U,
        p3: U,
        p4: &[P; 8],
        p5: &[P],
    ) -> P {
        todo!()
    }
}

mod h052 {
    use super::*;
    // fn<T,const,const>(tok:X64V3Token, gen:U, gen:U, gen:U, p) -> P
    // moxcms-safe/src/conversions/avx/interpolator.rs
    // moxcms-safe/src/conversions/avx/interpolator_q0_15.rs
    #[arcane]
    fn shape<U, const GRID_SIZE: usize, const BINS: usize>(
        p0: X64V3Token,
        p1: U,
        p2: U,
        p3: U,
        p4: &[P; 8],
        p5: &[P],
    ) -> P {
        todo!()
    }
}

mod h053 {
    use super::*;
    // fn<T:Clone + Copy + Default,const,const>(tok:NeonToken, p, gen:T)
    // moxcms-archmage/src/conversions/archmage_shaper_opt.rs
    #[arcane]
    fn shape<T: Clone + Copy + Default, const SRC_LAYOUT: u8, const DST_LAYOUT: u8>(
        p0: NeonToken,
        p1: &[T],
        p2: &mut [T],
        p3: &[f32],
        p4: &[T],
        p5: [[f32; 3]; 3],
        p6: f32,
        p7: T,
    ) {
        todo!()
    }
}

mod h054 {
    use super::*;
    // fn<T:Clone + Copy + Default,const,const>(tok:X64V3Token, p, gen:T)
    // moxcms-archmage/src/conversions/archmage_shaper_opt.rs
    #[arcane]
    fn shape<T: Clone + Copy + Default, const SRC_LAYOUT: u8, const DST_LAYOUT: u8>(
        p0: X64V3Token,
        p1: &[T],
        p2: &mut [T],
        p3: &[f32],
        p4: &[T],
        p5: [[f32; 3]; 3],
        p6: f32,
        p7: T,
    ) {
        todo!()
    }
}

mod h055 {
    use super::*;
    // fn<T:Clone + Copy + Default,const,const>(tok:X64V4Token, p, gen:T)
    // moxcms-archmage/src/conversions/archmage_shaper_opt.rs
    #[arcane]
    fn shape<T: Clone + Copy + Default, const SRC_LAYOUT: u8, const DST_LAYOUT: u8>(
        p0: X64V4Token,
        p1: &[T],
        p2: &mut [T],
        p3: &[f32],
        p4: &[T],
        p5: [[f32; 3]; 3],
        p6: f32,
        p7: T,
    ) {
        todo!()
    }
}

mod h056 {
    use super::*;
    // fn<T>(wild:tok:NeonToken, p, impl:FnOnce(P) -> P) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/aarch64/neon.rs
    #[arcane]
    fn shape<R>(_: NeonToken, p1: P, p2: impl FnOnce(P) -> P) -> R {
        todo!()
    }
}

mod h057 {
    use super::*;
    // fn<T>(wild:tok:X64V2Token, p, impl:FnOnce(P) -> P) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/sse42.rs
    #[arcane]
    fn shape<R>(_: X64V2Token, p1: P, p2: impl FnOnce(P) -> P) -> R {
        todo!()
    }
}

mod h058 {
    use super::*;
    // fn<T>(wild:tok:X64V3Token, p, impl:FnOnce(P) -> P) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/avx.rs
    #[arcane]
    fn shape<R>(_: X64V3Token, p1: P, p2: impl FnOnce(P) -> P) -> R {
        todo!()
    }
}

mod h059 {
    use super::*;
    // fn<T>(wild:tok:X64V4Token, p, impl:FnOnce(P) -> P) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/avx512.rs
    #[arcane]
    fn shape<R>(_: X64V4Token, p1: P, p2: impl FnOnce(P) -> P) -> R {
        todo!()
    }
}

mod h060 {
    use super::*;
    // fn<const,const,const,const>(tok:Arm64, p)
    // zen/rav1d-safe/src/safe_simd/cdef_arm.rs
    #[arcane]
    fn shape<const W: usize, const H: usize, const PRI: bool, const SEC: bool>(
        p0: Arm64,
        p1: P,
        p2: &[u16; 8],
        p3: usize,
        p4: &P,
    ) {
        todo!()
    }
}

mod h061 {
    use super::*;
    // fn<const>(tok:Server64, p)
    // zen/rav1d-safe/src/safe_simd/itx/part02_col_1d_avx512_pmaddwd.rs
    #[arcane]
    fn shape<const SHIFT: u32>(p0: Server64, p1: &mut [i32], p2: usize, p3: usize) {
        todo!()
    }
}

mod h062 {
    use super::*;
    // fn<const>(tok:X64V3Token, p)
    // zen/zenjpeg/zenjpeg/src/color/ycbcr.rs
    #[arcane]
    fn shape<const TURBO: bool>(p0: X64V3Token, p1: &[i16], p2: &[i16], p3: &[i16], p4: &mut [u8]) {
        todo!()
    }
}

mod h063 {
    use super::*;
    // fn<const>(tok:X64V4Token, p)
    // zen/zenjpeg/zenjpeg/src/color/ycbcr.rs
    #[arcane]
    fn shape<const TURBO: bool>(p0: X64V4Token, p1: &[i16], p2: &[i16], p3: &[i16], p4: &mut [u8]) {
        todo!()
    }
}

mod h064 {
    use super::*;
    // fn<const>(wild:tok:NeonToken, p) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/aarch64/neon.rs
    #[arcane]
    fn shape<const AMOUNT_I: i32>(_: NeonToken, p1: P) -> P {
        todo!()
    }
}

mod h065 {
    use super::*;
    // fn<const>(wild:tok:X64V2Token, p) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/sse42.rs
    #[arcane]
    fn shape<const AMOUNT_I: i32>(_: X64V2Token, p1: P) -> P {
        todo!()
    }
}

mod h066 {
    use super::*;
    // fn<const>(wild:tok:X64V3Token, p) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/avx.rs
    #[arcane]
    fn shape<const AMOUNT_I: i32>(_: X64V3Token, p1: P) -> P {
        todo!()
    }
}

mod h067 {
    use super::*;
    // fn<const>(wild:tok:X64V4Token, p) -> P
    // zen/zenjxl-decoder/zenjxl-decoder-simd/src/x86_64/avx512.rs
    #[arcane]
    fn shape<const AMOUNT_U: u32>(_: X64V4Token, p1: P) -> P {
        todo!()
    }
}

mod h068 {
    use super::*;
    // pub fn(tok:Arm64, p)
    // zen/rav1d-safe/src/safe_simd/itx_arm_hbd.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_16x16.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_32.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_4x4.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_64.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_8x8.rs
    // ... and 4 more
    #[arcane]
    pub fn shape(p0: Arm64, p1: &mut [u16], p2: usize, p3: i32, p4: i32) {
        todo!()
    }
}

mod h069 {
    use super::*;
    // pub fn(tok:Desktop64, p)
    // zen/rav1d-safe/src/safe_simd/itx/part01_macros_and_2d_transforms.rs
    // zen/rav1d-safe/src/safe_simd/itx/part09_identity_hybrid_16bpc.rs
    // zen/rav1d-safe/src/safe_simd/loopfilter_packed16.rs
    // zen/zenavif/src/simd/avg.rs
    // zen/zenavif/src/simd/unpremul.rs
    #[arcane]
    pub fn shape(p0: Desktop64, p1: &mut [P]) {
        todo!()
    }
}

mod h070 {
    use super::*;
    // pub fn(tok:Desktop64, p) -> P
    // zen/zenavif/src/yuv_convert_fast.rs
    // zen/zenavif/src/yuv_convert_libyuv_simd.rs
    #[arcane]
    pub fn shape(
        p0: Desktop64,
        p1: &[u8],
        p2: usize,
        p3: &[u8],
        p4: usize,
        p5: &[u8],
        p6: usize,
        p7: usize,
        p8: usize,
    ) -> P {
        todo!()
    }
}

mod h071 {
    use super::*;
    // pub fn(tok:NeonToken, p)
    // garb/src/bytes/neon.rs
    // garb/src/deinterleave.rs
    // zen/BRAG/brag-art/src/neon.rs
    // zen/BRAG/src/swizzle/neon.rs
    // zen/heic/heic-core/src/color_convert_neon.rs
    // zen/heic/src/hevc/transform_simd_neon.rs
    // ... and 41 more
    #[arcane]
    pub fn shape(p0: NeonToken, p1: P) {
        todo!()
    }
}

mod h072 {
    use super::*;
    // pub fn(tok:NeonToken, p) -> P
    // zen/jxl-encoder/jxl-encoder-simd/src/block_l2.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/cfl.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/sanitize.rs
    // zen/zenavif/src/yuv_convert_fast.rs
    // zen/zenavif/src/yuv_convert_libyuv_simd.rs
    // zen/zenjpeg/zenjpeg/src/encode/linear_lut.rs
    // ... and 7 more
    #[arcane]
    pub fn shape(p0: NeonToken, p1: P) -> f64 {
        todo!()
    }
}

mod h073 {
    use super::*;
    // pub fn(tok:Wasm128Token, p)
    // garb/src/bytes/wasm.rs
    // zen/BRAG/brag-art/src/wasm.rs
    // zen/BRAG/src/swizzle/wasm.rs
    // zen/heic/heic-core/src/color_convert_wasm.rs
    // zen/heic/src/hevc/transform_simd.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/adaptive_quant.rs
    // ... and 27 more
    #[arcane]
    pub fn shape(p0: Wasm128Token, p1: P) {
        todo!()
    }
}

mod h074 {
    use super::*;
    // pub fn(tok:Wasm128Token, p) -> P
    // zen/jxl-encoder/jxl-encoder-simd/src/block_l2.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/cfl.rs
    // zen/zenmetrics/crates/cvvdp/src/simd_math.rs
    // zen/zenmetrics/crates/haarpsi/src/kernel.rs
    // zen/zenmetrics/crates/msssim/src/kernel.rs
    // zen/zenmetrics/crates/vif/src/kernel.rs
    // ... and 2 more
    #[arcane]
    pub fn shape(p0: Wasm128Token, p1: P) -> f64 {
        todo!()
    }
}

mod h075 {
    use super::*;
    // pub fn(tok:X64V1Token, p)
    // zen/zenwebp/src/decoder/lossless_transform_simd.rs
    #[arcane]
    pub fn shape(p0: X64V1Token, p1: &mut [u8]) {
        todo!()
    }
}

mod h076 {
    use super::*;
    // pub fn(tok:X64V2Token, p) -> P
    // highway-rs-port/hwy/src/targets/x86.rs
    #[arcane]
    pub fn shape(p0: X64V2Token, p1: P) -> P {
        todo!()
    }
}

mod h077 {
    use super::*;
    // pub fn(tok:X64V3Token) -> P
    // highway-rs-port/hwy/src/targets/x86.rs
    #[arcane]
    pub fn shape(p0: X64V3Token) -> P {
        todo!()
    }
}

mod h078 {
    use super::*;
    // pub fn(tok:X64V3Token, p)
    // garb/src/bytes/avx2.rs
    // garb/src/deinterleave.rs
    // zen/BRAG/brag-art/src/x86.rs
    // zen/BRAG/src/swizzle/x86.rs
    // zen/heic/src/hevc/transform_simd.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/adaptive_quant.rs
    // ... and 41 more
    #[arcane]
    pub fn shape(p0: X64V3Token, p1: P) {
        todo!()
    }
}

mod h079 {
    use super::*;
    // pub fn(tok:X64V3Token, p) -> P
    // highway-rs-port/hwy/src/targets/x86.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/block_l2.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/cfl.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/fused_dct8.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/sanitize.rs
    // zen/zenjpeg/zenjpeg/src/decode/idct_int.rs
    // ... and 10 more
    #[arcane]
    pub fn shape(p0: X64V3Token, p1: P) -> P {
        todo!()
    }
}

mod h080 {
    use super::*;
    // pub fn(tok:X64V4Token, p)
    // zen/zenjpeg/zenjpeg/src/encode/mage_simd.rs
    // zen/zenmetrics/crates/fsim/src/kernel.rs
    // zen/zenmetrics/crates/gmsd/src/kernel.rs
    // zen/zenmetrics/crates/mad-iqa/src/kernel.rs
    // zen/zenmetrics/crates/psnrhvs/src/kernel.rs
    // zen/zenresize/src/simd/x86.rs
    // ... and 1 more
    #[arcane]
    pub fn shape(p0: X64V4Token, p1: P) {
        todo!()
    }
}

mod h081 {
    use super::*;
    // pub fn(tok:X64V4Token, p) -> P
    // zen/zenmetrics/crates/haarpsi/src/kernel.rs
    // zen/zenmetrics/crates/msssim/src/kernel.rs
    // zen/zenmetrics/crates/vif/src/kernel.rs
    // zen/zenmetrics/crates/vsi/src/kernel.rs
    #[arcane]
    pub fn shape(p0: X64V4Token, p1: P) -> f64 {
        todo!()
    }
}

mod h082 {
    use super::*;
    // pub fn<const>(tok:Desktop64, p)
    // zen/rav1d-safe/src/safe_simd/loopfilter_packed6.rs
    #[arcane]
    pub fn shape<const H: bool>(p0: Desktop64, p1: &mut [u8], p2: usize, p3: isize, p4: [u8; 3]) {
        todo!()
    }
}

mod h083 {
    use super::*;
    // pub unsafe fn(tok:X64V2Token, p)
    // highway-rs-port/hwy/src/targets/x86.rs
    #[arcane]
    pub unsafe fn shape(p0: X64V2Token, p1: *mut f32, p2: P) {
        todo!()
    }
}

mod h084 {
    use super::*;
    // pub unsafe fn(tok:X64V2Token, p) -> P
    // highway-rs-port/hwy/src/targets/x86.rs
    #[arcane]
    pub unsafe fn shape(p0: X64V2Token, p1: *const f32) -> P {
        todo!()
    }
}

mod h085 {
    use super::*;
    // pub unsafe fn(tok:X64V3Token, p)
    // highway-rs-port/hwy/src/targets/x86.rs
    #[arcane]
    pub unsafe fn shape(p0: X64V3Token, p1: *mut P, p2: P) {
        todo!()
    }
}

mod h086 {
    use super::*;
    // pub unsafe fn(tok:X64V3Token, p) -> P
    // highway-rs-port/hwy/src/targets/x86.rs
    #[arcane]
    pub unsafe fn shape(p0: X64V3Token, p1: *const P) -> P {
        todo!()
    }
}

mod h087 {
    use super::*;
    // unsafe fn(tok:Desktop64, p)
    // zen/rav1d-safe/src/safe_simd/mc.rs
    #[arcane]
    unsafe fn shape(
        p0: Desktop64,
        p1: *mut i16,
        p2: *const P,
        p3: isize,
        p4: i32,
        p5: i32,
        p6: i32,
        p7: i32,
    ) {
        todo!()
    }
}

mod h088 {
    use super::*;
    // pub fn(p)
    // zen/zenwebp/src/common/transform.rs
    #[autoversion(cfg(simd))]
    pub fn shape(p0: &mut [i32; 16]) {
        todo!()
    }
}

mod h089 {
    use super::*;
    // fn(p)
    // dvifmish/src/color.rs
    // dvifmish/src/int.rs
    // garb/src/bytes/packed.rs
    // garb/src/bytes/packed_1010102.rs
    #[autoversion(v3, neon, wasm128)]
    fn shape(p0: &[u8], p1: &mut [u8]) {
        todo!()
    }
}

mod h090 {
    use super::*;
    // fn(p) -> P
    // dvifmish/src/blocks.rs
    // dvifmish/src/pyramid.rs
    #[autoversion(v3, neon, wasm128)]
    fn shape(p0: &[f64]) -> bool {
        todo!()
    }
}

mod h091 {
    use super::*;
    // fn<const,const,const,const>(p)
    // dvifmish/src/pyramid.rs
    #[autoversion(v3, neon, wasm128)]
    fn shape<const FOUR: bool, const STEP: usize, const SUBTRACT: bool, const EXPAND: bool>(
        p0: &P,
        p1: &mut P,
        p2: &mut P,
    ) {
        todo!()
    }
}

mod h092 {
    use super::*;
    // fn<const,const>(p)
    // dvifmish/src/pyramid.rs
    #[autoversion(v3, neon, wasm128)]
    fn shape<const FOUR: bool, const LOCAL: bool>(p0: P, p1: &mut P) {
        todo!()
    }
}

mod h093 {
    use super::*;
    // fn<const,const>(self:&mutself, p) -> P
    // dvifmish/src/stream.rs
    impl P {
        #[autoversion(v3, neon, wasm128)]
        fn shape<const FOUR: bool, const LOCAL: bool>(&mut self, p1: usize, p2: usize) -> Vec<i16> {
            todo!()
        }
    }
}

mod h094 {
    use super::*;
    // fn<const>(p)
    // dvifmish/src/blocks.rs
    // dvifmish/src/int.rs
    #[autoversion(v3, neon, wasm128)]
    fn shape<const PEAK: bool>(p0: &P, p1: &P, p2: usize) {
        todo!()
    }
}

mod h095 {
    use super::*;
    // fn<lt,const>(impl:Fn(isize) -> &'a [P])
    // dvifmish/src/stream.rs
    #[autoversion(v3, neon, wasm128)]
    fn shape<'a, const FOUR: bool>(p0: impl Fn(isize) -> &'a [P]) {
        todo!()
    }
}

mod h096 {
    use super::*;
    // pub fn(p)
    // dvifmish/src/int.rs
    // garb/src/bytes/scalar.rs
    // zen/BRAG/brag-art/src/scalar.rs
    #[autoversion(v3, neon, wasm128)]
    pub fn shape(p0: &mut [u8]) {
        todo!()
    }
}

mod h097 {
    use super::*;
    // pub fn(p) -> P
    // garb/src/deinterleave.rs
    #[autoversion(v3, neon, wasm128)]
    pub fn shape(p0: &[f32], p1: &[f32], p2: &[f32], p3: &mut [f32]) -> Result<(), P> {
        todo!()
    }
}

mod h098 {
    use super::*;
    // pub fn<const>(p)
    // dvifmish/src/int.rs
    #[autoversion(v3, neon, wasm128)]
    pub fn shape<const FOUR: bool>(p0: &[i16], p1: &mut [i16]) {
        todo!()
    }
}

mod h099 {
    use super::*;
    // pub fn<const>(p) -> P
    // dvifmish/src/int.rs
    #[autoversion(v3, neon, wasm128)]
    pub fn shape<const FOUR: bool>(p0: &P) -> P {
        todo!()
    }
}

mod h100 {
    use super::*;
    // fn(p)
    // zen/zenanalyze/src/palette.rs
    // zen/zenanalyze/src/tier1.rs
    #[autoversion(v4x, v4, v3, neon, scalar)]
    fn shape(p0: &mut P, p1: &mut P) {
        todo!()
    }
}

mod h101 {
    use super::*;
    // fn(p) -> P
    // zen/zenanalyze/src/grayscale.rs
    // zen/zenanalyze/src/palette.rs
    // zen/zenanalyze/src/tier1.rs
    #[autoversion(v4x, v4, v3, neon, scalar)]
    fn shape(p0: &[u8]) -> u64 {
        todo!()
    }
}

mod h102 {
    use super::*;
    // fn(p)
    // butteraugli/butteraugli/src/blur_iir.rs
    // zen/aom-rs/crates/aom-dsp/src/intra/mod.rs
    // zen/butteraugli/butteraugli/src/blur_iir.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm.rs
    // zen/zenav1-aom/crates/aom-dsp/src/intra/mod.rs
    // zen/zenjpeg/zenjpeg/src/color/ycbcr.rs
    // ... and 13 more
    #[autoversion]
    fn shape(p0: &mut [f32]) {
        todo!()
    }
}

mod h103 {
    use super::*;
    // fn(p) -> P
    // coefficient/src/analysis/feature_extract.rs
    // zen/zenjpegai/src/nn/fast/math.rs
    // zen/zenpng/src/encoder/filter.rs
    // zen/zenraw/src/color.rs
    // zen/zensim/zensim/src/attribution.rs
    #[autoversion]
    fn shape(p0: &[u8]) -> f64 {
        todo!()
    }
}

mod h104 {
    use super::*;
    // fn(tok:SimdToken, p)
    // butteraugli/butteraugli/src/diff.rs
    // butteraugli/butteraugli/src/malta.rs
    // butteraugli/butteraugli/src/mask.rs
    // butteraugli/butteraugli/src/precompute.rs
    // butteraugli/butteraugli/src/psycho.rs
    // zen/butteraugli/butteraugli/src/diff.rs
    // ... and 15 more
    #[autoversion]
    fn shape(p0: SimdToken, p1: &P) {
        todo!()
    }
}

mod h105 {
    use super::*;
    // fn(tok:SimdToken, p) -> P
    // butteraugli/butteraugli/src/diff.rs
    // butteraugli/butteraugli/src/precompute.rs
    // zen/butteraugli/butteraugli/src/diff.rs
    // zen/butteraugli/butteraugli/src/precompute.rs
    // zen/zenmetrics/crates/margarine/box_blur.rs
    // zen/zenmetrics/crates/margarine/multirate_blur.rs
    #[autoversion]
    fn shape(p0: SimdToken, p1: &P, p2: usize, p3: &P) -> P {
        todo!()
    }
}

mod h106 {
    use super::*;
    // fn<const,const>(p)
    // zen/rav1d-safe/src/safe_simd/itx_arm.rs
    #[autoversion]
    fn shape<const W: usize, const H: usize>(
        p0: &mut [u8],
        p1: usize,
        p2: isize,
        p3: &mut [i16],
        p4: i32,
        p5: i32,
        p6: P,
        p7: P,
        p8: bool,
    ) {
        todo!()
    }
}

mod h107 {
    use super::*;
    // fn<const>(p)
    // zen/zensim/zensim/src/attribution.rs
    #[autoversion]
    fn shape<const L8: bool>(
        p0: &[f32],
        p1: &[f32],
        p2: &[f32],
        p3: &[f32],
        p4: &[f32],
        p5: [f32; 12],
        p6: [f64; 3],
        p7: &mut [f32],
        p8: &mut [f32],
    ) {
        todo!()
    }
}

mod h108 {
    use super::*;
    // pub fn(p)
    // zen/aom-rs/crates/aom-dsp/src/dist/simd.rs
    // zen/linear-srgb/benches/tf_bench.rs
    // zen/mozjpeg-rs/src/dct.rs
    // zen/mozjpeg-rs/src/simd/scalar.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm.rs
    // zen/zenjpeg/zenjpeg/examples/autovec_transpose.rs
    // ... and 5 more
    #[autoversion]
    pub fn shape(p0: &mut [f32]) {
        todo!()
    }
}

mod h109 {
    use super::*;
    // pub fn(p) -> P
    // zen/aom-rs/crates/aom-dsp/src/dist/simd.rs
    // zen/zenav1-aom/crates/aom-dsp/src/dist/simd.rs
    // zen/zenjpeg/zenjpeg/src/quant/aq/autovec.rs
    #[autoversion]
    pub fn shape(p0: &[f32], p1: usize, p2: usize, p3: usize) -> f32 {
        todo!()
    }
}

mod h110 {
    use super::*;
    // pub fn(tok:SimdToken, p)
    // butteraugli/butteraugli/src/mask.rs
    // zen/butteraugli/butteraugli/src/mask.rs
    // zen/zenmetrics/crates/margarine/sparse_malta.rs
    // zen/zenmetrics/crates/margarine/stream_blur.rs
    // zen/zenmetrics/crates/margarine/vendor/butteraugli/diff.rs
    // zen/zenmetrics/crates/margarine/vendor/butteraugli/mask.rs
    // ... and 1 more
    #[autoversion]
    pub fn shape(p0: SimdToken, p1: &P) {
        todo!()
    }
}

mod h111 {
    use super::*;
    // pub fn(tok:SimdToken, p) -> P
    // butteraugli/butteraugli/src/opsin.rs
    // zen/butteraugli/butteraugli/src/opsin.rs
    // zen/zenmetrics/crates/margarine/multirate_blur.rs
    // zen/zenmetrics/crates/margarine/vendor/butteraugli/diff.rs
    // zen/zenmetrics/crates/margarine/vendor/butteraugli/opsin.rs
    #[autoversion]
    pub fn shape(p0: SimdToken, p1: &P, p2: f32, p3: &P) -> P {
        todo!()
    }
}

mod h112 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/zensim/zensim/src/feature_v2.rs
    #[magetypes(+v4x, -v4, -v3, -neon, -wasm128, -scalar)]
    fn shape(
        p0: Token,
        p1: &[f32],
        p2: &[f32],
        p3: &[f32],
        p4: &[f32],
        p5: &[f32],
        p6: &[f32],
        p7: &[f32],
        p8: usize,
        p9: usize,
        p10: bool,
    ) -> P {
        todo!()
    }
}

mod h113 {
    use super::*;
    // pub fn(tok:Token, p)
    // zen/zenmetrics/crates/iwssim/src/simd_kernels.rs
    #[magetypes(define(f32x8), +v3, +neon, +wasm128, +scalar)]
    pub fn shape(
        p0: Token,
        p1: &[f32],
        p2: Option<&[f32]>,
        p3: usize,
        p4: usize,
        p5: usize,
        p6: usize,
        p7: usize,
        p8: &[(i32, i32)],
        p9: &mut [f64],
    ) {
        todo!()
    }
}

mod h114 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zenmetrics/crates/fsim/src/fft.rs
    // zen/zenmetrics/crates/hdrvdp/src/fft.rs
    // zen/zenmetrics/crates/iwssim/src/simd_kernels.rs
    // zen/zenmetrics/crates/mad-iqa/src/fft.rs
    // zen/zenmetrics/crates/nlpd/src/simd.rs
    // zen/zenmetrics/crates/vsi/src/fft.rs
    #[magetypes(define(f32x8), +v4, +v4x, +v3, +neon, +wasm128, +scalar)]
    fn shape(p0: Token, p1: &[f32], p2: &P) {
        todo!()
    }
}

mod h115 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/zenmetrics/crates/hdrvdp/src/simd_kernels.rs
    // zen/zenmetrics/crates/nlpd/src/simd.rs
    #[magetypes(define(f32x8), +v4, +v4x, +v3, +neon, +wasm128, +scalar)]
    fn shape(p0: Token, p1: &[f32], p2: &[f32]) -> f64 {
        todo!()
    }
}

mod h116 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zenmetrics/crates/cvvdp/src/simd_pyramid.rs
    // zen/zensim/zensim/src/blur.rs
    #[magetypes(define(f32x8), +v4, +v4x, -v3, -neon, -wasm128, -scalar)]
    fn shape(p0: Token, p1: &[f32], p2: usize, p3: usize, p4: &mut [f32]) {
        todo!()
    }
}

mod h117 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/aom-rs/crates/aom-dsp/src/dist/hadamard.rs
    // zen/aom-rs/crates/aom-dsp/src/restore/wiener.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/mod.rs
    #[magetypes(define(f32x8), v3, -scalar)]
    fn shape(p0: Token, p1: &[i16], p2: usize) -> Option<[i32; 64]> {
        todo!()
    }
}

mod h118 {
    use super::*;
    // fn(tok:Token, gen:K, p)
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/mod.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/mod.rs
    #[magetypes(define(f32x8), v3, neon, -scalar)]
    fn shape<K>(p0: Token, p1: K, p2: &[P], p3: &mut [P], p4: i32, p5: &[i8]) {
        todo!()
    }
}

mod h119 {
    use super::*;
    // fn(tok:Token, p)
    // zen/aom-rs/crates/aom-dsp/src/intra/dir_simd.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/lowbd16.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/lowbd16_fwd.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/mod.rs
    // zen/zenav1-aom/crates/aom-dsp/src/intra/dir_simd.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/lowbd16.rs
    // ... and 2 more
    #[magetypes(define(f32x8), v3, neon, -scalar)]
    fn shape(p0: Token, p1: P, p2: &[P], p3: &mut [P]) {
        todo!()
    }
}

mod h120 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/lowbd16.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/lowbd16_fwd.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/mod.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/lowbd16.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/lowbd16_fwd.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/mod.rs
    #[magetypes(define(f32x8), v3, neon, -scalar)]
    fn shape(p0: Token, p1: &P) -> bool {
        todo!()
    }
}

mod h121 {
    use super::*;
    // pub fn(tok:Token, p)
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/fwd1d_v3_i16_gen.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/hand_v3.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/inv1d_v3_gen.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/inv1d_v3_i16_gen.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/lowbd16.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/lowbd16_fwd.rs
    // ... and 8 more
    #[magetypes(define(f32x8), v3, neon, -scalar)]
    pub fn shape(p0: Token, p1: &[P], p2: &mut [P]) {
        todo!()
    }
}

mod h122 {
    use super::*;
    // pub fn(tok:Token, p) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/lowbd16.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/lowbd16_fwd.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/lowbd16.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/lowbd16_fwd.rs
    #[magetypes(define(f32x8), v3, neon, -scalar)]
    pub fn shape(
        p0: Token,
        p1: P,
        p2: &[i32],
        p3: &mut [i32],
        p4: usize,
        p5: usize,
        p6: bool,
        p7: i32,
    ) -> bool {
        todo!()
    }
}

mod h123 {
    use super::*;
    // fn(tok:Token, p)
    // zen/aom-rs/crates/aom-dsp/src/cdef/simd.rs
    // zen/aom-rs/crates/aom-dsp/src/intra/simd.rs
    // zen/aom-rs/crates/aom-dsp/src/intra/simd16.rs
    // zen/aom-rs/crates/aom-dsp/src/loopfilter/simd.rs
    // zen/aom-rs/crates/aom-dsp/src/restore/pick.rs
    // zen/aom-rs/crates/aom-dsp/src/restore/sgr.rs
    // ... and 6 more
    #[magetypes(define(f32x8), v3, neon, wasm128, -scalar)]
    fn shape(
        p0: Token,
        p1: &mut [i32],
        p2: &mut [i32],
        p3: u32,
        p4: u32,
        p5: u32,
        p6: u32,
        p7: u32,
    ) {
        todo!()
    }
}

mod h124 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/aom-rs/crates/aom-dsp/src/cdef/simd.rs
    // zen/aom-rs/crates/aom-dsp/src/quant/simd.rs
    // zen/aom-rs/crates/aom-dsp/src/restore/pick.rs
    // zen/zenav1-aom/crates/aom-dsp/src/cdef/simd.rs
    // zen/zenav1-aom/crates/aom-dsp/src/quant/simd.rs
    #[magetypes(define(f32x8), v3, neon, wasm128, -scalar)]
    fn shape(p0: Token, p1: &[u16], p2: usize, p3: i32, p4: &mut [[i16; 16]; 8]) -> bool {
        todo!()
    }
}

mod h125 {
    use super::*;
    // pub fn(tok:Token, p)
    // zen/aom-rs/crates/aom-dsp/src/dist/simd_variance.rs
    // zen/aom-rs/crates/aom-dsp/src/txb/simd.rs
    // zen/zenav1-aom/crates/aom-dsp/src/dist/simd_variance.rs
    // zen/zenav1-aom/crates/aom-dsp/src/txb/simd.rs
    #[magetypes(define(f32x8), v3, neon, wasm128, -scalar)]
    pub fn shape(p0: Token, p1: &[i32], p2: usize, p3: usize, p4: &mut [u8]) {
        todo!()
    }
}

mod h126 {
    use super::*;
    // pub fn(tok:Token, p) -> P
    // zen/aom-rs/crates/aom-dsp/src/intra/filter_simd.rs
    #[magetypes(define(f32x8), v3, neon, wasm128, -scalar)]
    pub fn shape(
        p0: Token,
        p1: &mut [u16],
        p2: usize,
        p3: usize,
        p4: &[u16],
        p5: &[u16],
        p6: usize,
        p7: i32,
    ) -> bool {
        todo!()
    }
}

mod h127 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zenmetrics/crates/cvvdp/src/simd_pyramid.rs
    // zen/zenmetrics/crates/gmsd/src/kernel.rs
    // zen/zenmetrics/crates/hdrvdp/src/simd_kernels.rs
    // zen/zenmetrics/crates/margarine/opsin_rows.rs
    // zen/zenmetrics/crates/vmaf/src/adm.rs
    // zen/zenmetrics/crates/vmaf/src/lib.rs
    // ... and 3 more
    #[magetypes(define(f32x8), v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &[f32], p2: f32, p3: f32, p4: &mut [f32]) {
        todo!()
    }
}

mod h128 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/zenmetrics/crates/vmaf/src/vif.rs
    // zen/zenpixels/zenpixels-convert/src/scan.rs
    #[magetypes(define(f32x8), v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &[u8]) -> bool {
        todo!()
    }
}

mod h129 {
    use super::*;
    // fn<const,const>(tok:Token, p) -> P
    // zen/zenpixels/zenpixels-convert/src/scan.rs
    #[magetypes(define(f32x8), v3, neon, wasm128, scalar)]
    fn shape<const A: bool, const B: bool>(p0: Token, p1: &[u8]) -> P {
        todo!()
    }
}

mod h130 {
    use super::*;
    // pub fn(tok:Token, p)
    // zen/jxl-encoder/jxl-encoder-simd/src/bench_cbrt.rs
    // zen/zentone/src/experimental/aces2_simd.rs
    // zen/zentone/src/simd/blocks.rs
    // zen/zentone/src/simd/curves.rs
    #[magetypes(define(f32x8), v3, neon, wasm128, scalar)]
    pub fn shape(p0: Token, p1: &mut [P; 4], p2: &P) {
        todo!()
    }
}

mod h131 {
    use super::*;
    // pub fn<const>(tok:Token, p)
    // zen/zenpixels/zenpixels-convert/src/hdr/measure.rs
    #[magetypes(define(f32x8), v3, neon, wasm128, scalar)]
    pub fn shape<const N: usize>(p0: Token, p1: &[f32], p2: &mut f32, p3: &mut f64) {
        todo!()
    }
}

mod h132 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/linear-srgb/src/simd.rs
    #[magetypes(define(f32x8), v4(cfg(avx512)), v3, neon, wasm128)]
    fn shape(p0: Token, p1: [f32; 16]) -> [f32; 16] {
        todo!()
    }
}

mod h133 {
    use super::*;
    // fn(tok:Token, p)
    // zen/linear-srgb/src/simd.rs
    // zen/zenpixels/zenpixels-convert/src/convert_kernels.rs
    // zen/zentone/src/simd/mod.rs
    #[magetypes(define(f32x8), v4(cfg(avx512)), v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &mut [f32]) {
        todo!()
    }
}

mod h134 {
    use super::*;
    // fn<const>(tok:Token, p)
    // zen/zenpixels/zenpixels-convert/src/convert_kernels.rs
    #[magetypes(define(f32x8), v4(cfg(avx512)), v3, neon, wasm128, scalar)]
    fn shape<const CHANNELS: usize>(
        p0: Token,
        p1: &[f32],
        p2: &mut [f32],
        p3: usize,
        p4: &[f32; 9],
    ) {
        todo!()
    }
}

mod h135 {
    use super::*;
    // pub fn(tok:Token, p)
    // zen/zenpixels/zenpixels-convert/src/hdr/bt2446a.rs
    // zen/zentone/src/simd/blocks.rs
    #[magetypes(define(f32x8), v4(cfg(avx512)), v3, neon, wasm128, scalar)]
    pub fn shape(p0: Token, p1: &mut [P; 4]) {
        todo!()
    }
}

mod h136 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zenmetrics/crates/gmsd/src/kernel.rs
    #[magetypes(define(f32x8), v4, -scalar)]
    fn shape(p0: Token, p1: &[u8], p2: usize, p3: usize, p4: usize, p5: &mut [f32]) {
        todo!()
    }
}

mod h137 {
    use super::*;
    // pub fn(tok:Token, p)
    // zen/jxl-encoder/jxl-encoder-simd/src/xyb.rs
    #[magetypes(define(f32x8), v4, v3, -neon, wasm128, -scalar)]
    pub fn shape(
        p0: Token,
        p1: P,
        p2: &[f32],
        p3: &[f32],
        p4: &[f32],
        p5: &mut [f32],
        p6: &mut [f32],
        p7: &mut [f32],
        p8: usize,
    ) {
        todo!()
    }
}

mod h138 {
    use super::*;
    // pub fn(tok:Token, p)
    // zen/jxl-encoder/jxl-encoder-simd/src/gaborish5x5.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/xyb.rs
    #[magetypes(define(f32x8), v4, v3, neon, wasm128, -scalar)]
    pub fn shape(
        p0: Token,
        p1: &[f32],
        p2: &[f32],
        p3: &[f32],
        p4: &mut [f32],
        p5: &mut [f32],
        p6: &mut [f32],
        p7: usize,
    ) {
        todo!()
    }
}

mod h139 {
    use super::*;
    // pub fn(tok:Token, p) -> P
    // zen/jxl-encoder/jxl-encoder-simd/src/entropy.rs
    #[magetypes(define(f32x8), v4, v3, neon, wasm128, -scalar)]
    pub fn shape(
        p0: Token,
        p1: &[f32],
        p2: &[f32],
        p3: &[f32],
        p4: &[f32],
        p5: usize,
        p6: f32,
        p7: f32,
        p8: f32,
        p9: f32,
        p10: bool,
        p11: &mut [f32],
    ) -> P {
        todo!()
    }
}

mod h140 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zenanalyze/src/tier3.rs
    // zen/zenanalyze/src/tier_depth.rs
    #[magetypes(define(f32x8), v4, v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &P) {
        todo!()
    }
}

mod h141 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/zenanalyze/examples/bench_repr_simd.rs
    // zen/zenanalyze/src/tier3.rs
    #[magetypes(define(f32x8), v4, v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &[f32]) -> f64 {
        todo!()
    }
}

mod h142 {
    use super::*;
    // fn<T>(tok:Token, p) -> P
    // zen/zenanalyze/src/tier1.rs
    // zen/zenanalyze/src/tier2_chroma.rs
    #[magetypes(define(f32x8), v4, v3, neon, wasm128, scalar)]
    fn shape<R>(p0: Token, p1: &[R], p2: usize, p3: usize, p4: usize) -> P {
        todo!()
    }
}

mod h143 {
    use super::*;
    // fn<const,T>(tok:Token, p)
    // zen/zenanalyze/src/tier1.rs
    #[magetypes(define(f32x8), v4, v3, neon, wasm128, scalar)]
    fn shape<const BT601: bool, R>(
        p0: Token,
        p1: &[R],
        p2: &[R],
        p3: &[R],
        p4: usize,
        p5: f32,
        p6: f32,
        p7: f32,
        p8: &mut [f32],
        p9: &mut [f32],
        p10: &mut [f32],
        p11: &mut [u32; 256],
    ) {
        todo!()
    }
}

mod h144 {
    use super::*;
    // fn<const,const,const,T>(tok:Token, p) -> P
    // zen/zenanalyze/src/tier1.rs
    #[magetypes(define(f32x8), v4, v3, neon, wasm128, scalar)]
    fn shape<const BT601: bool, const FULL: bool, const SKIN: bool, R>(
        p0: Token,
        p1: &[R],
        p2: usize,
        p3: Option<usize>,
        p4: usize,
        p5: f32,
        p6: f32,
        p7: f32,
    ) -> P {
        todo!()
    }
}

mod h145 {
    use super::*;
    // fn<const>(tok:Token, p)
    // zen/zenmetrics/crates/margarine/multirate_blur.rs
    #[magetypes(define(f32x8), v4, v3, neon, wasm128, scalar)]
    fn shape<const F: usize>(p0: Token, p1: &[f32], p2: &[f32], p3: f32, p4: &mut [f32]) {
        todo!()
    }
}

mod h146 {
    use super::*;
    // pub fn(tok:Token, p)
    // zen/zenanalyze/src/simd_math.rs
    #[magetypes(define(f32x8), v4, v3, neon, wasm128, scalar)]
    pub fn shape(p0: Token, p1: &[f32], p2: &mut [f32]) {
        todo!()
    }
}

mod h147 {
    use super::*;
    // pub fn(tok:Token, p) -> P
    // zen/jxl-encoder/jxl-encoder-simd/src/entropy.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/pixel_loss.rs
    #[magetypes(define(f32x8), v4, v3, neon, wasm128, scalar)]
    pub fn shape(p0: Token, p1: &[u32], p2: u32) -> f64 {
        todo!()
    }
}

mod h148 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/zenpng/src/simd/scan.rs
    #[magetypes(define(f32x8), v4x, v4, v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &[u8]) -> bool {
        todo!()
    }
}

mod h149 {
    use super::*;
    // fn<const,const,const>(tok:Token, p) -> P
    // zen/zenpng/src/simd/scan.rs
    #[magetypes(define(f32x8), v4x, v4, v3, neon, wasm128, scalar)]
    fn shape<const A: bool, const B: bool, const C: bool>(p0: Token, p1: &[u8]) -> P {
        todo!()
    }
}

mod h150 {
    use super::*;
    // pub fn(tok:Token, p)
    // zen/zenpipe/zenfilters/src/simd/wide_simd.rs
    // zen/zenresize/src/simd/wide_kernels.rs
    #[magetypes(neon, wasm128)]
    pub fn shape(p0: Token, p1: &mut [u8]) {
        todo!()
    }
}

mod h151 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zensim/zensim-train-core/src/simd_encoder.rs
    // zen/zensim/zensim-validate/src/adam_simd.rs
    // zen/zensim/zensim/src/blur.rs
    // zen/zensim/zensim/src/color.rs
    // zen/zensim/zensim/src/simd_ops.rs
    #[magetypes(neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &mut P) {
        todo!()
    }
}

mod h152 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/zensim/zensim-train-core/src/simd_encoder.rs
    // zen/zensim/zensim/src/fused.rs
    // zen/zensim/zensim/src/simd_ops.rs
    // zen/zenwebp/src/encoder/vp8l/transforms.rs
    #[magetypes(neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &[f32], p2: &[f32]) -> f64 {
        todo!()
    }
}

mod h153 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zenmetrics/crates/gmsd/src/kernel.rs
    #[magetypes(rite, define(f32x8), v3, neon, wasm128, scalar)]
    fn shape(
        p0: Token,
        p1: &[f32],
        p2: &[f32],
        p3: &[f32],
        p4: &[f32],
        p5: &[f32],
        p6: &[f32],
        p7: &mut [f32],
    ) {
        todo!()
    }
}

mod h154 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zenmetrics/crates/gmsd/src/kernel.rs
    #[magetypes(rite, define(f32x8), v4, -scalar)]
    fn shape(
        p0: Token,
        p1: &[f32],
        p2: &[f32],
        p3: &[f32],
        p4: &[f32],
        p5: &[f32],
        p6: &[f32],
        p7: &mut [f32],
    ) {
        todo!()
    }
}

mod h155 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zenmetrics/crates/gmsd/src/mdsi.rs
    // zen/zenmetrics/crates/gmsd/src/ms_gmsd.rs
    #[magetypes(rite, define(f32x8), v4, v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &P, p2: usize, p3: f64, p4: &mut [f64]) {
        todo!()
    }
}

mod h156 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zenpipe/zenfilters/src/filters/warp_simd.rs
    // zen/zenpixels/zenpixels-convert/src/f16_scalar.rs
    #[magetypes(v3, neon, wasm128)]
    fn shape(p0: Token, p1: &[u16], p2: &mut [f32]) {
        todo!()
    }
}

mod h157 {
    use super::*;
    // pub fn(tok:Token, p) -> P
    // zen/linear-srgb/src/tokens/x4.rs
    // zen/linear-srgb/src/tokens/x8.rs
    #[magetypes(v3, neon, wasm128)]
    #[rite]
    pub fn shape(p0: Token, p1: [f32; 4]) -> [f32; 4] {
        todo!()
    }
}

mod h158 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zenraw/src/simd.rs
    #[magetypes(v3, neon, wasm128, -scalar)]
    fn shape(p0: Token, p1: &[f32], p2: f32, p3: f32, p4: &mut [f32]) {
        todo!()
    }
}

mod h159 {
    use super::*;
    // fn(tok:Token, p)
    // butteraugli/butteraugli/src/blur_iir.rs
    // zen/butteraugli/butteraugli/src/blur_iir.rs
    // zen/fast-ssim2/benchmarks/version_divergence_2026-09-09/blur_perf_bench.rs
    // zen/fast-ssim2/benchmarks/version_divergence_2026-09-09/cbrt_perf_bench.rs
    // zen/fast-ssim2/fast-ssim2/src/blur/simd_gaussian.rs
    // zen/fast-ssim2/fast-ssim2/src/simd_ops.rs
    // ... and 17 more
    #[magetypes(v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &mut [f32]) {
        todo!()
    }
}

mod h160 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/fast-ssim2/fast-ssim2/src/simd_ops.rs
    // zen/zenjpeg/zenjpeg/src/decode/idct.rs
    // zen/zenjpeg/zenjpeg/src/decode/idct_int.rs
    // zen/zenjpeg/zenjpeg/src/encode/boundary_rd.rs
    // zen/zenjpeg/zenjpeg/src/encode/dct.rs
    // zen/zenjpeg/zenjpeg/src/encode/strip/mod.rs
    // ... and 3 more
    #[magetypes(v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &P) -> P {
        todo!()
    }
}

mod h161 {
    use super::*;
    // pub fn(tok:Token, p)
    // coefficient/src/analysis/feature_extract_simd.rs
    // zen/zenjpeg/zenyuv/src/decode_generic.rs
    // zen/zenjpeg/zenyuv/src/encode_generic.rs
    #[magetypes(v3, neon, wasm128, scalar)]
    pub fn shape(p0: Token, p1: &[u8], p2: &mut [u8], p3: usize, p4: &P) {
        todo!()
    }
}

mod h162 {
    use super::*;
    // pub fn<T,const,const>(tok:Token, gen:U, gen:U, gen:U, p)
    // moxcms-safe/src/conversions/simd_interp.rs
    // moxcms-safe/src/conversions/simd_interp_double.rs
    // moxcms-safe/src/conversions/simd_interp_q0_15.rs
    // moxcms-safe/src/conversions/simd_interp_q0_15_double.rs
    #[magetypes(v3, neon, wasm128, scalar)]
    pub fn shape<U, const GRID_SIZE: usize, const BINS: usize>(
        p0: Token,
        p1: U,
        p2: U,
        p3: U,
        p4: &[P; 8],
        p5: &[P],
        p6: &mut [f32; 4],
    ) {
        todo!()
    }
}

mod h163 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zenmetrics/crates/margarine/full_malta.rs
    // zen/zensim/zensim/src/simd_ops.rs
    #[magetypes(v4, v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &[f32], p2: &[f32], p3: f32) {
        todo!()
    }
}

mod h164 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/zensim/zensim/src/feature_v2.rs
    // zen/zensim/zensim/src/simd_ops.rs
    #[magetypes(v4, v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &[f32], p2: f32, p3: &[f32], p4: &[f32]) -> f64 {
        todo!()
    }
}

mod h165 {
    use super::*;
    // fn(tok:Token, p)
    // zen/zensim/zensim/src/dvifm.rs
    // zen/zensim/zensim/src/feature_v2.rs
    #[magetypes(v4x, v4, v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &mut P, p2: &[f32], p3: &[f32]) {
        todo!()
    }
}

mod h166 {
    use super::*;
    // fn(tok:Token, p) -> P
    // zen/zensim/zensim/src/dvifm.rs
    // zen/zensim/zensim/src/feature_v2.rs
    #[magetypes(v4x, v4, v3, neon, wasm128, scalar)]
    fn shape(p0: Token, p1: &mut P) -> [f64; 8] {
        todo!()
    }
}

mod h167 {
    use super::*;
    // fn<T,T>(tok:Token, p)
    // zen/zenavif/src/yuv_convert.rs
    #[magetypes(v4x, v4, v3, neon, wasm128, scalar)]
    fn shape<S, P>(
        p0: Token,
        p1: &[S],
        p2: usize,
        p3: usize,
        p4: usize,
        p5: usize,
        p6: P,
        p7: u8,
        p8: &mut [P],
    ) {
        todo!()
    }
}

mod h168 {
    use super::*;
    // fn<T>(tok:Token, p)
    // zen/zenavif/src/yuv_convert.rs
    #[magetypes(v4x, v4, v3, neon, wasm128, scalar)]
    fn shape<P>(
        p0: Token,
        p1: &[P],
        p2: usize,
        p3: usize,
        p4: usize,
        p5: P,
        p6: P,
        p7: &mut [u8],
        p8: &mut [u8],
        p9: &mut [u8],
    ) {
        todo!()
    }
}

mod h169 {
    use super::*;
    // fn(tok:Wasm128Token, p)
    // zen/zenresize/src/simd/wasm128.rs
    #[rite(import_intrinsics)]
    fn shape(p0: Wasm128Token, p1: &[u8], p2: &mut [u8], p3: &P) {
        todo!()
    }
}

mod h170 {
    use super::*;
    // fn(tok:Wasm128Token, p) -> P
    // zen/zenresize/src/simd/wasm128.rs
    #[rite(import_intrinsics)]
    fn shape(p0: Wasm128Token, p1: &[u16; 4]) -> [f32; 4] {
        todo!()
    }
}

mod h171 {
    use super::*;
    // fn(gen:V) -> P
    // zen/rav1d-safe/src/safe_simd/itx_arm_hbd.rs
    #[rite(neon)]
    fn shape<V>(p0: V) -> V {
        todo!()
    }
}

mod h172 {
    use super::*;
    // fn(gen:V, gen:V, gen:V) -> P
    // zen/rav1d-safe/src/safe_simd/itx_arm_hbd.rs
    #[rite(neon)]
    fn shape<V>(p0: V, p1: V, p2: V) -> V {
        todo!()
    }
}

mod h173 {
    use super::*;
    // fn(gen:V, p) -> P
    // zen/rav1d-safe/src/safe_simd/itx_arm_hbd.rs
    #[rite(neon)]
    fn shape<V>(p0: V, p1: i32) -> V {
        todo!()
    }
}

mod h174 {
    use super::*;
    // fn(gen:V, p, gen:V, p) -> P
    // zen/rav1d-safe/src/safe_simd/itx_arm_hbd.rs
    #[rite(neon)]
    fn shape<V>(p0: V, p1: i32, p2: V, p3: i32) -> V {
        todo!()
    }
}

mod h175 {
    use super::*;
    // fn(p)
    // zen/rav1d-safe/src/safe_simd/cdef_arm.rs
    // zen/rav1d-safe/src/safe_simd/ipred_arm.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_16x16.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_32.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_4x4.rs
    // ... and 9 more
    #[rite(neon)]
    fn shape(p0: &mut [P]) {
        todo!()
    }
}

mod h176 {
    use super::*;
    // fn(p) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/rav1d-safe/src/safe_simd/cdef_arm.rs
    // zen/rav1d-safe/src/safe_simd/ipred_arm.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_hbd.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_16x16.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_rect_large.rs
    // ... and 3 more
    #[rite(neon)]
    fn shape(p0: P) -> P {
        todo!()
    }
}

mod h177 {
    use super::*;
    // fn(p, gen:V, gen:V)
    // zen/rav1d-safe/src/safe_simd/itx_arm_hbd.rs
    #[rite(neon)]
    fn shape<V>(p0: &mut [V; 4], p1: V, p2: V) {
        todo!()
    }
}

mod h178 {
    use super::*;
    // fn(p, gen:V, gen:V) -> P
    // zen/rav1d-safe/src/safe_simd/itx_arm_hbd.rs
    #[rite(neon)]
    fn shape<V>(p0: &[V; 8], p1: V, p2: V) -> [V; 8] {
        todo!()
    }
}

mod h179 {
    use super::*;
    // fn<const,const>(p)
    // zen/rav1d-safe/src/safe_simd/itx_arm_hbd.rs
    #[rite(neon)]
    fn shape<const W: usize, const H: usize>(
        p0: P,
        p1: P,
        p2: u32,
        p3: &mut [i32],
        p4: i32,
        p5: &mut [i32],
    ) {
        todo!()
    }
}

mod h180 {
    use super::*;
    // fn<const,const>(p) -> P
    // zen/rav1d-safe/src/safe_simd/cdef_arm.rs
    #[rite(neon)]
    fn shape<const PRI: bool, const SEC: bool>(
        p0: &[u16; 8],
        p1: usize,
        p2: P,
        p3: usize,
        p4: P,
        p5: P,
        p6: P,
        p7: P,
        p8: i16,
    ) -> P {
        todo!()
    }
}

mod h181 {
    use super::*;
    // fn<const>(p)
    // zen/rav1d-safe/src/safe_simd/loopfilter_arm.rs
    #[rite(neon)]
    fn shape<const WD: usize>(p0: &mut [P; 14], p1: P, p2: P, p3: P, p4: P, p5: P, p6: P) {
        todo!()
    }
}

mod h182 {
    use super::*;
    // fn<const>(p, gen:V, gen:V)
    // zen/rav1d-safe/src/safe_simd/itx_arm_hbd.rs
    #[rite(neon)]
    fn shape<const N: usize, V>(p0: P, p1: &mut [V; N], p2: V, p3: V) {
        todo!()
    }
}

mod h183 {
    use super::*;
    // pub fn(gen:V) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    #[rite(neon)]
    pub fn shape<V>(p0: V) -> P {
        todo!()
    }
}

mod h184 {
    use super::*;
    // pub fn(p)
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_32.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_4x4.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_64.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_8x8.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_common.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_rect.rs
    #[rite(neon)]
    pub fn shape(p0: P, p1: P, p2: P, p3: P) {
        todo!()
    }
}

mod h185 {
    use super::*;
    // pub fn(p) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_16x16.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_32.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_8x8.rs
    // zen/rav1d-safe/src/safe_simd/itx_arm_neon_rect.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    #[rite(neon)]
    pub fn shape(p0: P) -> P {
        todo!()
    }
}

mod h186 {
    use super::*;
    // pub fn(tok:NeonToken, gen:V) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    #[rite(neon)]
    pub fn shape<V>(p0: NeonToken, p1: V) -> V {
        todo!()
    }
}

mod h187 {
    use super::*;
    // pub fn(tok:NeonToken, gen:V, p) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    #[rite(neon)]
    pub fn shape<V>(p0: NeonToken, p1: V, p2: i32) -> V {
        todo!()
    }
}

mod h188 {
    use super::*;
    // pub fn(tok:NeonToken, p)
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims16.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims16.rs
    #[rite(neon)]
    pub fn shape(p0: NeonToken, p1: P, p2: &mut [u8; 16]) {
        todo!()
    }
}

mod h189 {
    use super::*;
    // pub fn(tok:NeonToken, p) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims16.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims16.rs
    #[rite(neon)]
    pub fn shape(p0: NeonToken, p1: P) -> P {
        todo!()
    }
}

mod h190 {
    use super::*;
    // pub fn(tok:NeonToken, p, gen:V, p, gen:V, p) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    #[rite(neon)]
    pub fn shape<V>(p0: NeonToken, p1: i32, p2: V, p3: i32, p4: V, p5: i32) -> V {
        todo!()
    }
}

mod h191 {
    use super::*;
    // fn(p)
    // zen/rav1d-safe/src/safe_simd/filmgrain.rs
    // zen/rav1d-safe/src/safe_simd/ipred.rs
    // zen/rav1d-safe/src/safe_simd/itx/part01_macros_and_2d_transforms.rs
    // zen/rav1d-safe/src/safe_simd/itx/part03_adst16_and_small_rect.rs
    // zen/rav1d-safe/src/safe_simd/itx/part04_rect_idtx_aspect.rs
    // zen/rav1d-safe/src/safe_simd/itx/part06_adst_flipadst_vh.rs
    // ... and 6 more
    #[rite(v3)]
    fn shape(p0: *mut u8, p1: *const u8, p2: P, p3: P, p4: P, p5: P) {
        todo!()
    }
}

mod h192 {
    use super::*;
    // fn(p) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/rav1d-safe/src/safe_simd/cdef.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    #[rite(v3)]
    fn shape(p0: P, p1: P) -> P {
        todo!()
    }
}

mod h193 {
    use super::*;
    // pub fn(gen:V) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    #[rite(v3)]
    pub fn shape<V>(p0: V) -> P {
        todo!()
    }
}

mod h194 {
    use super::*;
    // pub fn(p)
    // garb/src/deinterleave.rs
    #[rite(v3)]
    pub fn shape(p0: &[P; 8]) {
        todo!()
    }
}

mod h195 {
    use super::*;
    // pub fn(p) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    #[rite(v3)]
    pub fn shape(p0: P, p1: P) -> P {
        todo!()
    }
}

mod h196 {
    use super::*;
    // pub fn(tok:X64V3Token, gen:V) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    #[rite(v3)]
    pub fn shape<V>(p0: X64V3Token, p1: V) -> V {
        todo!()
    }
}

mod h197 {
    use super::*;
    // pub fn(tok:X64V3Token, gen:V, p) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    #[rite(v3)]
    pub fn shape<V>(p0: X64V3Token, p1: V, p2: i32) -> V {
        todo!()
    }
}

mod h198 {
    use super::*;
    // pub fn(tok:X64V3Token, p)
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims16.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims16.rs
    #[rite(v3)]
    pub fn shape(p0: X64V3Token, p1: P, p2: &mut [u8; 16]) {
        todo!()
    }
}

mod h199 {
    use super::*;
    // pub fn(tok:X64V3Token, p) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims16.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims16.rs
    #[rite(v3)]
    pub fn shape(p0: X64V3Token, p1: P) -> P {
        todo!()
    }
}

mod h200 {
    use super::*;
    // pub fn(tok:X64V3Token, p, gen:V, p, gen:V, p) -> P
    // zen/aom-rs/crates/aom-dsp/src/transform/simd/prims.rs
    // zen/zenav1-aom/crates/aom-dsp/src/transform/simd/prims.rs
    #[rite(v3)]
    pub fn shape<V>(p0: X64V3Token, p1: i32, p2: V, p3: i32, p4: V, p5: i32) -> V {
        todo!()
    }
}

mod h201 {
    use super::*;
    // unsafe fn(p)
    // zen/rav1d-safe/src/safe_simd/mc.rs
    #[rite(v3)]
    unsafe fn shape(p0: *mut u8, p1: *const u8, p2: usize, p3: usize) {
        todo!()
    }
}

mod h202 {
    use super::*;
    // fn(p)
    // zen/zenwebp/src/decoder/vp8v2/yuv_exact.rs
    // zen/zenwebp/src/decoder/yuv_fused.rs
    #[rite(v3, import_intrinsics)]
    fn shape(p0: P, p1: P, p2: P) {
        todo!()
    }
}

mod h203 {
    use super::*;
    // fn(tok:Arm64, p)
    // zen/rav1d-safe/src/safe_simd/mc_arm.rs
    #[rite]
    fn shape(p0: Arm64, p1: &mut [i16], p2: &[u8], p3: usize, p4: &[i8; 8], p5: u8) {
        todo!()
    }
}

mod h204 {
    use super::*;
    // fn(tok:Arm64, p) -> P
    // zen/rav1d-safe/src/safe_simd/looprestoration_arm.rs
    #[rite]
    fn shape(p0: Arm64, p1: P) -> P {
        todo!()
    }
}

mod h205 {
    use super::*;
    // fn(tok:Arm64V2Token, p)
    // imageflow-zencodecs-v2/imageflow_core/src/graphics/transpose.rs
    // imageflow/imageflow_core/src/graphics/transpose.rs
    #[rite]
    fn shape(
        p0: Arm64V2Token,
        p1: &[f32],
        p2: &mut [f32],
        p3: usize,
        p4: usize,
        p5: usize,
        p6: usize,
    ) {
        todo!()
    }
}

mod h206 {
    use super::*;
    // fn(tok:Desktop64, p)
    // zen/rav1d-safe/src/safe_simd/itx/part01_macros_and_2d_transforms.rs
    // zen/rav1d-safe/src/safe_simd/itx/part02_col_1d_avx512_pmaddwd.rs
    // zen/rav1d-safe/src/safe_simd/itx/part04_rect_idtx_aspect.rs
    // zen/rav1d-safe/src/safe_simd/itx/part06_adst_flipadst_vh.rs
    // zen/rav1d-safe/src/safe_simd/itx/part07_32x32_64x64_dct.rs
    // zen/rav1d-safe/src/safe_simd/looprestoration.rs
    // ... and 3 more
    #[rite]
    fn shape(p0: Desktop64, p1: &mut [P; 4], p2: P, p3: P) {
        todo!()
    }
}

mod h207 {
    use super::*;
    // fn(tok:Desktop64, p) -> P
    // zen/rav1d-safe/src/safe_simd/cdef.rs
    // zen/rav1d-safe/src/safe_simd/itx/part02_col_1d_avx512_pmaddwd.rs
    // zen/rav1d-safe/src/safe_simd/itx/part04_rect_idtx_aspect.rs
    // zen/rav1d-safe/src/safe_simd/loopfilter_packed16.rs
    // zen/rav1d-safe/src/safe_simd/loopfilter_packed6.rs
    // zen/rav1d-safe/src/safe_simd/mc.rs
    #[rite]
    fn shape(p0: Desktop64, p1: P, p2: P) -> P {
        todo!()
    }
}

mod h208 {
    use super::*;
    // fn(tok:NeonToken, p)
    // butteraugli/butteraugli/src/blur.rs
    // zen/butteraugli/butteraugli/src/blur.rs
    // zen/heic/src/hevc/transform_simd_neon.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct16.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct32.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct64.rs
    // ... and 20 more
    #[rite]
    fn shape(p0: NeonToken, p1: P, p2: P) {
        todo!()
    }
}

mod h209 {
    use super::*;
    // fn(tok:NeonToken, p) -> P
    // butteraugli/butteraugli/src/malta.rs
    // zen/BRAG/brag-art/src/neon.rs
    // zen/butteraugli/butteraugli/src/malta.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct16.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct32.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct64.rs
    // ... and 21 more
    #[rite]
    fn shape(p0: NeonToken, p1: P) -> P {
        todo!()
    }
}

mod h210 {
    use super::*;
    // fn(tok:Server64, p)
    // zen/rav1d-safe/src/safe_simd/itx/part02_col_1d_avx512_pmaddwd.rs
    // zen/rav1d-safe/src/safe_simd/looprestoration.rs
    // zen/rav1d-safe/src/safe_simd/mc.rs
    #[rite]
    fn shape(p0: Server64, p1: &mut [P; 4], p2: P, p3: P) {
        todo!()
    }
}

mod h211 {
    use super::*;
    // fn(tok:Server64, p) -> P
    // zen/rav1d-safe/src/safe_simd/cdef.rs
    // zen/rav1d-safe/src/safe_simd/itx/part02_col_1d_avx512_pmaddwd.rs
    #[rite]
    fn shape(p0: Server64, p1: P, p2: P, p3: P) -> P {
        todo!()
    }
}

mod h212 {
    use super::*;
    // fn(tok:Wasm128Token, p)
    // butteraugli/butteraugli/src/blur.rs
    // imageflow-zencodecs-v2/imageflow_core/src/graphics/transpose.rs
    // imageflow/imageflow_core/src/graphics/transpose.rs
    // zen/butteraugli/butteraugli/src/blur.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct16.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct32.rs
    // ... and 7 more
    #[rite]
    fn shape(p0: Wasm128Token, p1: &mut [f32x4; 4]) {
        todo!()
    }
}

mod h213 {
    use super::*;
    // fn(tok:Wasm128Token, p) -> P
    // butteraugli/butteraugli/src/malta.rs
    // zen/butteraugli/butteraugli/src/malta.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct16.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct32.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct64.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dequant.rs
    // ... and 7 more
    #[rite]
    fn shape(p0: Wasm128Token, p1: P, p2: P, p3: P) -> P {
        todo!()
    }
}

mod h214 {
    use super::*;
    // fn(tok:X64V1Token, p)
    // zen/zenwebp/src/decoder/lossless_transform_simd.rs
    // zen/zenwebp/src/encoder/vp8l/transforms.rs
    #[rite]
    fn shape(p0: X64V1Token, p1: &mut [u8]) {
        todo!()
    }
}

mod h215 {
    use super::*;
    // fn(tok:X64V1Token, p) -> P
    // zen/zenwebp/src/encoder/vp8l/transforms.rs
    #[rite]
    fn shape(p0: X64V1Token, p1: &[u32; 256], p2: &[u32; 256]) -> u64 {
        todo!()
    }
}

mod h216 {
    use super::*;
    // fn(tok:X64V2Token, p) -> P
    // zen/zenpng/src/simd/paeth.rs
    #[rite]
    fn shape(p0: X64V2Token, p1: P, p2: P, p3: P) -> P {
        todo!()
    }
}

mod h217 {
    use super::*;
    // fn(tok:X64V3Token, p)
    // butteraugli/butteraugli/src/blur.rs
    // hdr-research/planar-bench/src/lib.rs
    // imageflow-zencodecs-v2/imageflow_core/src/graphics/transpose.rs
    // imageflow/imageflow_core/src/graphics/transpose.rs
    // zen/butteraugli/butteraugli/src/blur.rs
    // zen/heic/src/hevc/transform_simd.rs
    // ... and 19 more
    #[rite]
    fn shape(p0: X64V3Token, p1: P, p2: P) {
        todo!()
    }
}

mod h218 {
    use super::*;
    // fn(tok:X64V3Token, p) -> P
    // butteraugli/butteraugli/src/malta.rs
    // zen/butteraugli/butteraugli/src/malta.rs
    // zen/heic/src/hevc/transform_simd.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct4.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/epf.rs
    // zen/zenjpeg/zenjpeg/src/decode/idct_int.rs
    // ... and 12 more
    #[rite]
    fn shape(p0: X64V3Token, p1: P) -> P {
        todo!()
    }
}

mod h219 {
    use super::*;
    // fn(tok:X64V4Token, p)
    // butteraugli/butteraugli/src/blur.rs
    // zen/butteraugli/butteraugli/src/blur.rs
    // zen/zenjpeg/zenjpeg/src/encode/mage_simd.rs
    // zen/zenmetrics/crates/margarine/vendor/butteraugli/blur.rs
    #[rite]
    fn shape(p0: X64V4Token, p1: &mut [P; 8]) {
        todo!()
    }
}

#[cfg(feature = "w512")]
mod h220 {
    use super::*;
    // fn(tok:X64V4Token, p) -> P
    // butteraugli/butteraugli/src/malta.rs
    // zen/butteraugli/butteraugli/src/malta.rs
    // zen/zenmetrics/crates/margarine/vendor/butteraugli/malta.rs
    #[rite]
    fn shape(p0: X64V4Token, p1: &[f32], p2: usize, p3: usize) -> f32x16 {
        todo!()
    }
}

mod h221 {
    use super::*;
    // fn<const>(tok:Arm64, p)
    // zen/rav1d-safe/src/safe_simd/looprestoration_arm.rs
    #[rite]
    fn shape<const N: usize>(
        p0: Arm64,
        p1: &[u8; N],
        p2: usize,
        p3: usize,
        p4: &mut [u16; N],
        p5: &mut [u32; N],
        p6: &mut [i16],
        p7: &mut [i32],
    ) {
        todo!()
    }
}

mod h222 {
    use super::*;
    // fn<const>(tok:Desktop64, p)
    // zen/rav1d-safe/src/safe_simd/itx/part06_adst_flipadst_vh.rs
    #[rite]
    fn shape<const FLIPPED: bool>(p0: Desktop64, p1: &[i16], p2: &mut [i32; 64]) {
        todo!()
    }
}

mod h223 {
    use super::*;
    // fn<const>(tok:Desktop64, p) -> P
    // zen/rav1d-safe/src/safe_simd/itx/part02_col_1d_avx512_pmaddwd.rs
    #[rite]
    fn shape<const SHIFT: i32>(p0: Desktop64, p1: P, p2: i32, p3: P, p4: i32, p5: i32) -> P {
        todo!()
    }
}

mod h224 {
    use super::*;
    // fn<const>(tok:Server64, p) -> P
    // zen/rav1d-safe/src/safe_simd/itx/part02_col_1d_avx512_pmaddwd.rs
    #[rite]
    fn shape<const SHIFT: u32>(p0: Server64, p1: P, p2: i32, p3: P, p4: i32, p5: i32) -> P {
        todo!()
    }
}

mod h225 {
    use super::*;
    // pub fn(tok:NeonToken, p)
    // garb/src/bytes/neon.rs
    // zen/BRAG/brag-art/src/neon.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct16.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct32.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct64.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/idct16.rs
    // ... and 5 more
    #[rite]
    pub fn shape(p0: NeonToken, p1: &mut [u8]) {
        todo!()
    }
}

mod h226 {
    use super::*;
    // pub fn(tok:NeonToken, p) -> P
    // zen/linear-srgb/src/tokens/x4.rs
    // zen/zenwebp/src/common/simd_neon.rs
    // zen/zenwebp/src/encoder/residual_cost.rs
    #[rite]
    pub fn shape(p0: NeonToken, p1: [f32; 4]) -> [f32; 4] {
        todo!()
    }
}

mod h227 {
    use super::*;
    // pub fn(tok:Wasm128Token, p)
    // garb/src/bytes/wasm.rs
    // zen/BRAG/brag-art/src/wasm.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct16.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct32.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct64.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/idct16.rs
    // ... and 6 more
    #[rite]
    pub fn shape(p0: Wasm128Token, p1: &mut [u8]) {
        todo!()
    }
}

mod h228 {
    use super::*;
    // pub fn(tok:Wasm128Token, p) -> P
    // zen/linear-srgb/src/tokens/x4.rs
    // zen/zenwebp/src/common/simd_wasm.rs
    // zen/zenwebp/src/common/transform.rs
    // zen/zenwebp/src/encoder/residual_cost.rs
    #[rite]
    pub fn shape(p0: Wasm128Token, p1: [f32; 4]) -> [f32; 4] {
        todo!()
    }
}

mod h229 {
    use super::*;
    // pub fn(tok:X64V3Token, p)
    // garb/src/bytes/avx2.rs
    // zen/BRAG/brag-art/src/x86.rs
    // zen/jxl-encoder/jxl-encoder-simd/src/dct8.rs
    // zen/linear-srgb/src/tokens/x4.rs
    // zen/linear-srgb/src/tokens/x8.rs
    // zen/zenjpeg/zenyuv/src/avx2_encode.rs
    // ... and 3 more
    #[rite]
    pub fn shape(p0: X64V3Token, p1: &mut [u8]) {
        todo!()
    }
}

mod h230 {
    use super::*;
    // pub fn(tok:X64V3Token, p) -> P
    // zen/linear-srgb/src/tokens/x4.rs
    // zen/linear-srgb/src/tokens/x8.rs
    // zen/zenjpeg/zenyuv/src/avx2_encode.rs
    // zen/zenwebp/src/common/simd_sse.rs
    // zen/zenwebp/src/common/transform.rs
    // zen/zenwebp/src/encoder/cost/distortion.rs
    // ... and 2 more
    #[rite]
    pub fn shape(p0: X64V3Token, p1: P, p2: P) -> P {
        todo!()
    }
}

mod h231 {
    use super::*;
    // pub fn(tok:X64V4Token, p)
    // zen/linear-srgb/src/tokens/x16.rs
    #[rite]
    pub fn shape(p0: X64V4Token, p1: &mut [f32]) {
        todo!()
    }
}

mod h232 {
    use super::*;
    // pub fn(tok:X64V4Token, p) -> P
    // zen/linear-srgb/src/tokens/x16.rs
    #[rite]
    pub fn shape(p0: X64V4Token, p1: [u8; 16]) -> [f32; 16] {
        todo!()
    }
}
