// @generated by xtask expand_gen
use archmage::prelude::*;
struct S { k: f32 }
impl S {
    #[arcane(in_impl)]
    fn probe(token: X64V3Token, x: f32) -> f32 { let _ = token; Self::offset() + x }
    fn offset() -> f32 { 1.0 }
}
fn main() {}
