// @generated by xtask expand_gen
use archmage::prelude::*;
struct S { k: f32 }
trait Work { fn pick<'a>(&'a self, token: X64V3Token, other: &'a f32) -> &'a f32; }
impl Work for S {
    #[arcane(in_trait, _self = S)]
    fn pick<'a>(&'a self, token: X64V3Token, other: &'a f32) -> &'a f32 { let _ = token; if self.k > *other { &self.k } else { other } }
}
fn main() {
    if let Some(token) = X64V3Token::summon() {
        let (s, t) = (S { k: 1.0 }, S { k: 2.0 });
        let _: f32 = *s.pick(token, &t.k);
    }
}
