// @generated by xtask expand_gen
use archmage::prelude::*;
struct S { k: f32 }
trait Work { fn consume(self: Box<Self>, token: X64V3Token) -> f32; }
impl Work for S {
    #[arcane(in_trait, _self = S)]
    fn consume(self: Box<Self>, token: X64V3Token) -> f32 { let _ = token; self.k }
}
fn main() {
    if let Some(token) = X64V3Token::summon() {
        let (s, t) = (S { k: 1.0 }, S { k: 2.0 });
        let _: f32 = Box::new(s).consume(token);
    }
}
