// @generated by xtask expand_gen
use archmage::prelude::*;
fn inner_scalar(_: ScalarToken, x: u32) -> u32 { x }
#[arcane]
fn outer(t: X64V3Token, x: u32) -> u32 {
    incant!(inner(t, x), [scalar])
}
fn main() {}
