// @generated by xtask expand_gen
use archmage::prelude::*;
struct S { k: f32 }
trait Work { fn merge(&self, token: X64V3Token, other: &Self) -> f32; }
impl Work for S {
    #[arcane(in_trait, _self = S)]
    fn merge(&self, token: X64V3Token, other: &Self) -> f32 { let _ = token; self.k + other.k }
}
fn main() {
    if let Some(token) = X64V3Token::summon() {
        let (s, t) = (S { k: 1.0 }, S { k: 2.0 });
        let _: f32 = s.merge(token, &t);
    }
}
