// @generated by xtask expand_gen
use archmage::prelude::*;
#[arcane]
fn inner_v3(_: X64V3Token, x: u32) -> u32 { x + 1 }
fn inner_scalar(_: ScalarToken, x: u32) -> u32 { x }
#[arcane]
fn outer(_: X64V3Token, x: u32) -> u32 {
    incant!(inner(x), [v3, scalar])
}
fn main() {}
