// @generated by xtask expand_gen
use archmage::prelude::*;
struct S { k: f32 }
impl S {
    #[arcane]
    fn probe(&self, token: X64V3Token, x: f32) -> f32 { let _ = token; self.k + x }
}
fn main() {}
