// @generated by xtask expand_gen
use archmage::prelude::*;
#[arcane]
fn probe<T: Copy>(token: T, x: f32) -> f32 where T: HasX64V4 {
    let _ = token;
    let _ = X64V3Token::from_context();
    x
}
fn main() {}
