// @generated by xtask expand_gen
use archmage::prelude::*;
// `inner_v3` exists only with the feature; the caller holds V3, so
// the direct call must be gated and fall through to scalar.
#[cfg(feature = "gated")]
#[arcane]
fn inner_v3(_: X64V3Token, x: u32) -> u32 { x + 1 }
fn inner_scalar(_: ScalarToken, x: u32) -> u32 { x }
#[arcane]
fn outer(t: X64V3Token, x: u32) -> u32 {
    incant!(inner(x), [v3(cfg(gated)), scalar])
}
fn main() {}
