// @generated by xtask expand_gen
use archmage::prelude::*;
struct S { k: f32 }
impl S { fn offset() -> f32 { 1.0 } }
trait Work { fn run(&self, token: X64V3Token, x: f32) -> f32; }
impl Work for S {
    #[arcane(_self = S)]
    fn run(&self, token: X64V3Token, x: f32) -> f32 { let _ = token; _self.k + x }
}
fn main() {}
