// @generated by xtask expand_gen
use archmage::prelude::*;
struct S { k: f32 }
trait Work { fn run(&self, token: X64V3Token, x: f32) -> f32; }
impl Work for S {
    #[arcane(in_trait, _self = S)]
    fn run(&self, token: X64V3Token, x: f32) -> f32 { let _ = token; struct Inner(f32); impl Inner { fn value(&self) -> f32 { self.0 } } self.k + Inner(x).value() }
}
fn main() {
    if let Some(token) = X64V3Token::summon() {
        let (s, t) = (S { k: 1.0 }, S { k: 2.0 });
        let _: f32 = s.run(token, t.k);
    }
}
