// @generated by xtask expand_gen
use archmage::autoversion;
struct S { k: f32 }
trait Work { fn merge(&self, other: &Self) -> f32; }
impl Work for S {
    #[autoversion(v3, scalar, in_trait, _self = S)]
    fn merge(&self, other: &Self) -> f32 { self.k + other.k }
}
fn main() { let (s, t) = (S { k: 1.0 }, S { k: 2.0 }); let _: f32 = s.merge(&t); }
