// @generated by xtask expand_gen
use archmage::autoversion;
struct S { k: f32 }
trait Work { fn run(&self, x: f32) -> f32; }
impl Work for S {
    #[autoversion(v3, scalar, in_trait, _self = S)]
    fn run(&self, x: f32) -> f32 { struct Inner(f32); impl Inner { fn value(&self) -> f32 { self.0 } } self.k + Inner(x).value() }
}
fn main() { let (s, t) = (S { k: 1.0 }, S { k: 2.0 }); let _: f32 = s.run(t.k); }
