// @generated by xtask expand_gen
use archmage::autoversion;
struct S { k: f32 }
trait Work { fn run(&self, x: f32) -> f32; }
impl Work for S {
    #[autoversion(v3, scalar, in_trait, _self = S)]
    fn run(&self, x: f32) -> f32 { self.k + x }
}
fn main() { let _ = S { k: 1.0 }.run(2.0); }
