// @generated by xtask expand_gen
use archmage::autoversion;
struct S { k: f32 }
trait Work { fn pick<'a>(&'a self, other: &'a f32) -> &'a f32; }
impl Work for S {
    #[autoversion(v3, scalar, in_trait, _self = S)]
    fn pick<'a>(&'a self, other: &'a f32) -> &'a f32 { if self.k > *other { &self.k } else { other } }
}
fn main() { let (s, t) = (S { k: 1.0 }, S { k: 2.0 }); let _: f32 = *s.pick(&t.k); }
