// @generated by xtask expand_gen
use archmage::prelude::*;
struct S { k: f32 }
impl S {
    #[magetypes(v3, scalar, in_impl)]
    fn probe(token: Token, x: f32) -> f32 { let _ = token; Self::offset() + x }
    fn offset() -> f32 { 1.0 }
}
fn main() {}
