// @generated by xtask expand_gen
use archmage::prelude::*;
struct S { k: f32 }
impl S {
    #[magetypes(v3, scalar)]
    fn probe(&self, token: Token, x: f32) -> f32 { let _ = token; self.k + x }
}
fn main() {}
