// @generated by xtask expand_gen
use archmage::prelude::*;
struct S { k: f32 }
impl S {
    #[rite]
    fn probe(&mut self, token: X64V3Token, x: f32) -> f32 { let _ = token; { self.k += x; self.k } }
}
fn main() {}
