// @generated by xtask expand_gen
use archmage::autoversion;
#[autoversion]
fn inner(data: &[f32; 4]) -> f32 { data.iter().sum() }
#[autoversion]
fn outer(data: &[f32; 4], scale: f32) -> f32 { inner(data) * scale }
fn main() {}
