// @generated by xtask expand_gen
use archmage::prelude::*;
#[magetypes(v3, neon, scalar)]
fn inner(token: Token, x: f32) -> f32 { let _ = token; x }
// autoversion variants hold their tier's token; the nested call is direct.
#[autoversion(v3, neon, scalar)]
fn outer(x: f32) -> f32 {
incant!(inner(x), [v3, neon, scalar])
}
fn main() { let _ = outer(1.0); }
