// @generated by xtask expand_gen
use archmage::prelude::*;
#[magetypes(v3, neon, wasm128, scalar)]
fn inner(token: Token, x: f32) -> f32 { let _ = token; x }
// Each outer variant calls its own tier's inner variant directly.
#[magetypes(v3, neon, wasm128, scalar)]
fn outer(token: Token, x: f32) -> f32 {
incant!(inner(x), [v3, neon, wasm128, scalar])
}
pub fn api(x: f32) -> f32 { incant!(outer(x), [v3, neon, wasm128, scalar]) }
fn main() {}
