// @generated by xtask expand_gen
use archmage::prelude::*;
#[magetypes(v3, neon, scalar)]
fn inner(token: Token, x: f32) -> f32 { let _ = token; x }
// Tokenless tiers derive the callee's token with from_context().
#[rite(v3, neon)]
fn outer(x: f32) -> f32 {
incant!(inner(x), [v3, neon, scalar])
}
fn main() {}
