// @generated by xtask expand_gen
use archmage::{arcane, X64V3Token, X64V4Token};
#[arcane]
fn v3_helper(_t: X64V3Token, x: f32) -> f32 { x }
#[arcane]
fn v4_caller(token: X64V4Token, x: f32) -> f32 {
v3_helper(token.v3(), x) + 1.0
}
fn main() {}
