// @generated by xtask expand_gen
use archmage::{arcane, SimdToken, X64V3Token, X64V4Token};
#[arcane]
fn v4_fast(_t: X64V4Token, x: f32) -> f32 { x * 4.0 }
#[arcane]
fn v3_with_upgrade(_t: X64V3Token, x: f32) -> f32 {
if let Some(v4) = X64V4Token::summon() { v4_fast(v4, x) }
else { x * 2.0 }
}
fn main() {}
