// @generated by xtask expand_gen
use archmage::prelude::*;
#[arcane]
fn helper_v3(_t: X64V3Token, x: f32) -> f32 { x }
fn helper_scalar(_t: ScalarToken, x: f32) -> f32 { x }
// Caller holds V4; the rewrite calls helper_v3(token.v3(), x) directly.
#[arcane]
fn v4_caller(token: X64V4Token, x: f32) -> f32 {
incant!(helper(x), [v3, scalar]) + 1.0
}
fn main() {}
