// @generated by xtask expand_gen
use archmage::prelude::*;
#[arcane]
fn fast_v4(_t: X64V4Token, x: f32) -> f32 { x * 4.0 }
#[arcane]
fn fast_v3(_t: X64V3Token, x: f32) -> f32 { x * 2.0 }
fn fast_scalar(_t: ScalarToken, x: f32) -> f32 { x }
// Caller holds V3: one summon arm for V4, then fast_v3(t, x) directly.
#[arcane]
fn v3_with_upgrade(t: X64V3Token, x: f32) -> f32 {
incant!(fast(x), [+v4])
}
fn main() {}
