// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
fn sum(data: &[f32; 4]) -> f32 {
    #[allow(unused_imports)]
    use archmage::SimdToken;
    #[cfg(target_arch = "x86_64")]
    {
        if let Some(__t) = archmage::X64V4Token::summon() {
            return sum_v4(__t, data);
        }
        if let Some(__t) = archmage::X64V3Token::summon() {
            return sum_v3(__t, data);
        }
    }
    #[cfg(target_arch = "aarch64")]
    {
        if let Some(__t) = archmage::NeonToken::summon() {
            return sum_neon(__t, data);
        }
    }
    #[cfg(target_arch = "wasm32")]
    {
        if let Some(__t) = archmage::Wasm128Token::summon() {
            return sum_wasm128(__t, data);
        }
    }
    sum_default(data)
}
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[allow(dead_code)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe,pclmulqdq,aes,avx512f,avx512bw,avx512cd,avx512dq,avx512vl"
)]
#[inline]
fn __arcane_sum_v4(_token: archmage::X64V4Token, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[cfg(target_arch = "x86_64")]
#[allow(dead_code)]
#[inline(always)]
fn sum_v4(_token: archmage::X64V4Token, data: &[f32; 4]) -> f32 {
    let _: () = <archmage::X64V4Token>::__ARCHMAGE_ASSERT_TIER_FE1B900C;
    unsafe { __arcane_sum_v4(_token, data) }
}
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[allow(dead_code)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn __arcane_sum_v3(_token: archmage::X64V3Token, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[cfg(target_arch = "x86_64")]
#[allow(dead_code)]
#[inline(always)]
fn sum_v3(_token: archmage::X64V3Token, data: &[f32; 4]) -> f32 {
    let _: () = <archmage::X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
    unsafe { __arcane_sum_v3(_token, data) }
}
#[cfg(target_arch = "aarch64")]
#[doc(hidden)]
#[allow(dead_code)]
#[target_feature(enable = "neon")]
#[inline]
fn __arcane_sum_neon(_token: archmage::NeonToken, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[cfg(target_arch = "aarch64")]
#[allow(dead_code)]
#[inline(always)]
fn sum_neon(_token: archmage::NeonToken, data: &[f32; 4]) -> f32 {
    let _: () = <archmage::NeonToken>::__ARCHMAGE_ASSERT_TIER_72CB52B2;
    unsafe { __arcane_sum_neon(_token, data) }
}
#[cfg(target_arch = "wasm32")]
#[target_feature(enable = "simd128")]
#[inline]
#[allow(dead_code)]
fn sum_wasm128(_token: archmage::Wasm128Token, data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
#[allow(dead_code)]
fn sum_default(data: &[f32; 4]) -> f32 {
    data.iter().sum()
}
fn main() {}
