// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
struct P {
    f: f32,
}
impl P {
    fn apply(&self, x: f32) -> f32 {
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V4Token::summon() {
                return self.apply_v4(__t, x);
            }
            if let Some(__t) = archmage::X64V3Token::summon() {
                return self.apply_v3(__t, x);
            }
        }
        #[cfg(target_arch = "aarch64")]
        {
            if let Some(__t) = archmage::NeonToken::summon() {
                return self.apply_neon(__t, x);
            }
        }
        #[cfg(target_arch = "wasm32")]
        {
            if let Some(__t) = archmage::Wasm128Token::summon() {
                return self.apply_wasm128(__t, x);
            }
        }
        self.apply_scalar(archmage::ScalarToken, x)
    }
    #[cfg(target_arch = "x86_64")]
    #[allow(dead_code)]
    #[archmage::arcane(_self = P)]
    fn apply_v4(&self, _token: archmage::X64V4Token, x: f32) -> f32 {
        x * _self.f
    }
    #[cfg(target_arch = "x86_64")]
    #[allow(dead_code)]
    #[archmage::arcane(_self = P)]
    fn apply_v3(&self, _token: archmage::X64V3Token, x: f32) -> f32 {
        x * _self.f
    }
    #[cfg(target_arch = "aarch64")]
    #[allow(dead_code)]
    #[archmage::arcane(_self = P)]
    fn apply_neon(&self, _token: archmage::NeonToken, x: f32) -> f32 {
        x * _self.f
    }
    #[cfg(target_arch = "wasm32")]
    #[allow(dead_code)]
    #[archmage::arcane(_self = P)]
    fn apply_wasm128(&self, _token: archmage::Wasm128Token, x: f32) -> f32 {
        x * _self.f
    }
    #[allow(dead_code)]
    fn apply_scalar(&self, _token: archmage::ScalarToken, x: f32) -> f32 {
        let _self = self;
        x * _self.f
    }
}
fn main() {}
