// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::autoversion;
unsafe fn process(ptr: *const f32, len: usize) -> f32 {
    #[allow(unused_imports)]
    use archmage::SimdToken;
    #[cfg(target_arch = "x86_64")]
    {
        if let Some(__t) = archmage::X64V4Token::summon() {
            return unsafe { process_v4(__t, ptr, len) };
        }
        if let Some(__t) = archmage::X64V3Token::summon() {
            return unsafe { process_v3(__t, ptr, len) };
        }
    }
    #[cfg(target_arch = "aarch64")]
    {
        if let Some(__t) = archmage::NeonToken::summon() {
            return unsafe { process_neon(__t, ptr, len) };
        }
    }
    #[cfg(target_arch = "wasm32")]
    {
        if let Some(__t) = archmage::Wasm128Token::summon() {
            return unsafe { process_wasm128(__t, ptr, len) };
        }
    }
    unsafe { process_scalar(archmage::ScalarToken, ptr, len) }
}
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[allow(dead_code)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe,pclmulqdq,aes,avx512f,avx512bw,avx512cd,avx512dq,avx512vl"
)]
#[inline]
fn __arcane_process_v4(
    _token: archmage::X64V4Token,
    ptr: *const f32,
    len: usize,
) -> f32 {
    let mut s = 0.0f32;
    for i in 0..len {
        s += unsafe { *ptr.add(i) };
    }
    s
}
#[cfg(target_arch = "x86_64")]
#[allow(dead_code)]
#[inline(always)]
unsafe fn process_v4(_token: archmage::X64V4Token, ptr: *const f32, len: usize) -> f32 {
    let _: () = <archmage::X64V4Token>::__ARCHMAGE_ASSERT_TIER_FE1B900C;
    unsafe { __arcane_process_v4(_token, ptr, len) }
}
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[allow(dead_code)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn __arcane_process_v3(
    _token: archmage::X64V3Token,
    ptr: *const f32,
    len: usize,
) -> f32 {
    let mut s = 0.0f32;
    for i in 0..len {
        s += unsafe { *ptr.add(i) };
    }
    s
}
#[cfg(target_arch = "x86_64")]
#[allow(dead_code)]
#[inline(always)]
unsafe fn process_v3(_token: archmage::X64V3Token, ptr: *const f32, len: usize) -> f32 {
    let _: () = <archmage::X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
    unsafe { __arcane_process_v3(_token, ptr, len) }
}
#[cfg(target_arch = "aarch64")]
#[doc(hidden)]
#[allow(dead_code)]
#[target_feature(enable = "neon")]
#[inline]
fn __arcane_process_neon(
    _token: archmage::NeonToken,
    ptr: *const f32,
    len: usize,
) -> f32 {
    let mut s = 0.0f32;
    for i in 0..len {
        s += unsafe { *ptr.add(i) };
    }
    s
}
#[cfg(target_arch = "aarch64")]
#[allow(dead_code)]
#[inline(always)]
unsafe fn process_neon(_token: archmage::NeonToken, ptr: *const f32, len: usize) -> f32 {
    let _: () = <archmage::NeonToken>::__ARCHMAGE_ASSERT_TIER_72CB52B2;
    unsafe { __arcane_process_neon(_token, ptr, len) }
}
#[cfg(target_arch = "wasm32")]
#[target_feature(enable = "simd128")]
#[inline]
#[allow(dead_code)]
unsafe fn process_wasm128(
    _token: archmage::Wasm128Token,
    ptr: *const f32,
    len: usize,
) -> f32 {
    let mut s = 0.0f32;
    for i in 0..len {
        s += unsafe { *ptr.add(i) };
    }
    s
}
#[allow(dead_code)]
unsafe fn process_scalar(
    _token: archmage::ScalarToken,
    ptr: *const f32,
    len: usize,
) -> f32 {
    let mut s = 0.0f32;
    for i in 0..len {
        s += unsafe { *ptr.add(i) };
    }
    s
}
fn main() {}
