//! Generate combinatorial macro expansion test files.
//!
//! Produces `tests/expand/{category}/{test_name}.rs` covering every
//! meaningful combination of macro, token position, tier relationship,
//! and function properties.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

/// A generated test file.
struct TestFile {
    /// Relative path under tests/expand/
    path: String,
    /// File content
    content: String,
}

pub fn generate_expand_tests(expand_dir: &Path) -> anyhow::Result<()> {
    let mut files = Vec::new();

    gen_arcane_tests(&mut files);
    gen_rite_tests(&mut files);
    gen_autoversion_tests(&mut files);
    gen_incant_tests(&mut files);
    gen_rewrite_tests(&mut files);
    gen_deprecated_tests(&mut files);
    gen_combination_tests(&mut files);

    // Collect existing hand-written files to avoid overwriting
    let generated_marker = "// @generated by xtask expand_gen";

    let mut written = 0;
    let mut categories: BTreeMap<String, usize> = BTreeMap::new();

    for file in &files {
        let full_path = expand_dir.join(&file.path);
        if let Some(parent) = full_path.parent() {
            fs::create_dir_all(parent)?;
        }

        let content = format!("{generated_marker}\n{}", file.content);
        fs::write(&full_path, &content)?;
        written += 1;

        let category = file.path.split('/').next().unwrap_or("root").to_string();
        *categories.entry(category).or_default() += 1;
    }

    println!("Generated {written} expand test files:");
    for (cat, count) in &categories {
        println!("  {cat}/: {count} files");
    }

    Ok(())
}

// ============================================================================
// #[arcane] tests
// ============================================================================

fn gen_arcane_tests(files: &mut Vec<TestFile>) {
    // Expansion modes
    for (mode, mode_attr, self_line, token_param) in [
        ("sibling", "#[arcane]", "", "token: X64V3Token"),
        ("nested", "#[arcane(nested)]", "", "token: X64V3Token"),
        (
            "nested_self",
            "#[arcane(_self = Processor)]",
            "struct Processor { val: f32 }\nimpl Processor {",
            "token: X64V3Token",
        ),
    ] {
        let close = if mode == "nested_self" { "\n}" } else { "" };
        let body = if mode == "nested_self" {
            "_self.val + a"
        } else {
            "a + b"
        };
        let params = if mode == "nested_self" {
            "&self, token: X64V3Token, a: f32"
        } else {
            "token: X64V3Token, a: f32, b: f32"
        };

        files.push(TestFile {
            path: format!("arcane/{mode}.rs"),
            content: format!(
                "use archmage::{{arcane, X64V3Token}};\n\
                 {self_line}\n\
                 {mode_attr}\n\
                 fn process({params}) -> f32 {{ {body} }}\n\
                 {close}\n\
                 fn main() {{}}\n"
            ),
        });
    }

    // Token types
    for (name, token_type, import) in [
        ("token_v2", "X64V2Token", "X64V2Token"),
        ("token_v3", "X64V3Token", "X64V3Token"),
        ("token_v4", "X64V4Token", "X64V4Token"),
        ("token_neon", "NeonToken", "NeonToken"),
        ("token_wasm", "Wasm128Token", "Wasm128Token"),
        ("token_trait_bound", "impl HasX64V2", "HasX64V2"),
        ("token_generic", "T", "HasX64V2"),
    ] {
        let generic = if name == "token_generic" {
            "<T: HasX64V2>"
        } else {
            ""
        };
        files.push(TestFile {
            path: format!("arcane/{name}.rs"),
            content: format!(
                "use archmage::{{arcane, {import}}};\n\
                 #[arcane]\n\
                 fn process{generic}(token: {token_type}, a: f32) -> f32 {{ a + 1.0 }}\n\
                 fn main() {{}}\n"
            ),
        });
    }

    // Token positions
    for (name, params) in [
        ("token_first", "token: X64V3Token, a: f32, b: f32"),
        ("token_middle", "a: f32, token: X64V3Token, b: f32"),
        ("token_last", "a: f32, b: f32, token: X64V3Token"),
    ] {
        files.push(TestFile {
            path: format!("arcane/{name}.rs"),
            content: format!(
                "use archmage::{{arcane, X64V3Token}};\n\
                 #[arcane]\n\
                 fn process({params}) -> f32 {{ let _ = token; a + b }}\n\
                 fn main() {{}}\n"
            ),
        });
    }

    // Unsafe fn
    files.push(TestFile {
        path: "arcane/unsafe_fn.rs".to_string(),
        content: "use archmage::{arcane, X64V3Token};\n\
                  #[arcane]\n\
                  unsafe fn process(token: X64V3Token, ptr: *const f32) -> f32 {\n\
                      unsafe { *ptr }\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // Import intrinsics
    files.push(TestFile {
        path: "arcane/import_intrinsics.rs".to_string(),
        content: "use archmage::{arcane, X64V3Token};\n\
                  #[arcane(import_intrinsics)]\n\
                  fn process(token: X64V3Token, a: &[f32; 8], b: &[f32; 8]) -> [f32; 8] {\n\
                      let va = _mm256_loadu_ps(a);\n\
                      let vb = _mm256_loadu_ps(b);\n\
                      let s = _mm256_add_ps(va, vb);\n\
                      let mut out = [0.0f32; 8];\n\
                      _mm256_storeu_ps(&mut out, s);\n\
                      out\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // Wildcard token
    files.push(TestFile {
        path: "arcane/wildcard_token.rs".to_string(),
        content: "use archmage::{arcane, X64V3Token};\n\
                  #[arcane]\n\
                  fn process(_: X64V3Token, a: f32) -> f32 { a * 2.0 }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // cfg feature
    files.push(TestFile {
        path: "arcane/cfg_feature.rs".to_string(),
        content: "use archmage::{arcane, X64V3Token};\n\
                  #[arcane(cfg(my_feature))]\n\
                  fn process(token: X64V3Token, a: f32) -> f32 { a }\n\
                  fn main() {}\n"
            .to_string(),
    });
}

// ============================================================================
// #[rite] tests
// ============================================================================

fn gen_rite_tests(files: &mut Vec<TestFile>) {
    // Single-tier with token
    files.push(TestFile {
        path: "rite/single_token.rs".to_string(),
        content: "use archmage::{rite, X64V3Token};\n\
                  #[rite]\n\
                  fn helper(token: X64V3Token, a: f32) -> f32 { a * 2.0 }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // Single-tier tokenless
    files.push(TestFile {
        path: "rite/single_tier.rs".to_string(),
        content: "use archmage::rite;\n\
                  #[rite(v3)]\n\
                  fn helper(a: f32) -> f32 { a * 2.0 }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // Multi-tier
    for (name, tiers) in [
        ("multi_v3_neon", "v3, neon"),
        ("multi_v3_v4_neon", "v3, v4, neon"),
        ("multi_with_cfg", "v3, neon, cfg(simd_opt)"),
    ] {
        files.push(TestFile {
            path: format!("rite/{name}.rs"),
            content: format!(
                "use archmage::rite;\n\
                 #[rite({tiers})]\n\
                 fn compute(data: &[f32; 4]) -> f32 {{ data.iter().sum() }}\n\
                 fn main() {{}}\n"
            ),
        });
    }

    // Trait bound
    files.push(TestFile {
        path: "rite/trait_bound.rs".to_string(),
        content: "use archmage::{rite, HasX64V2};\n\
                  #[rite]\n\
                  fn helper(token: impl HasX64V2, a: f32) -> f32 { let _ = token; a }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // Unsafe fn
    files.push(TestFile {
        path: "rite/unsafe_fn.rs".to_string(),
        content: "use archmage::{rite, X64V3Token};\n\
                  #[rite]\n\
                  unsafe fn helper(token: X64V3Token, ptr: *const f32) -> f32 {\n\
                      unsafe { *ptr }\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // Import intrinsics
    files.push(TestFile {
        path: "rite/import_intrinsics.rs".to_string(),
        content: "use archmage::{rite, X64V3Token};\n\
                  #[rite(import_intrinsics)]\n\
                  fn helper(token: X64V3Token, a: &[f32; 8], b: &[f32; 8]) -> [f32; 8] {\n\
                      let va = _mm256_loadu_ps(a);\n\
                      let vb = _mm256_loadu_ps(b);\n\
                      let s = _mm256_add_ps(va, vb);\n\
                      let mut out = [0.0f32; 8];\n\
                      _mm256_storeu_ps(&mut out, s);\n\
                      out\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });
}

// ============================================================================
// #[autoversion] tests
// ============================================================================

fn gen_autoversion_tests(files: &mut Vec<TestFile>) {
    // Basic
    files.push(TestFile {
        path: "autoversion/basic.rs".to_string(),
        content: "use archmage::autoversion;\n\
                  #[autoversion]\n\
                  fn sum(data: &[f32; 4]) -> f32 { data.iter().sum() }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // Explicit tiers
    for (name, tiers) in [
        ("explicit_v3_scalar", "v3, scalar"),
        ("explicit_v3_neon_scalar", "v3, neon, scalar"),
        ("explicit_gated", "v4(cfg(avx512)), v3, neon, scalar"),
    ] {
        files.push(TestFile {
            path: format!("autoversion/{name}.rs"),
            content: format!(
                "use archmage::autoversion;\n\
                 #[autoversion({tiers})]\n\
                 fn sum(data: &[f32; 4]) -> f32 {{ data.iter().sum() }}\n\
                 fn main() {{}}\n"
            ),
        });
    }

    // Tier modifiers
    files.push(TestFile {
        path: "autoversion/tier_modifiers.rs".to_string(),
        content: "use archmage::autoversion;\n\
                  #[autoversion(+arm_v2, -wasm128)]\n\
                  fn sum(data: &[f32; 4]) -> f32 { data.iter().sum() }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // ScalarToken
    files.push(TestFile {
        path: "autoversion/scalar_token.rs".to_string(),
        content: "use archmage::{autoversion, ScalarToken};\n\
                  #[autoversion]\n\
                  fn process(token: ScalarToken, data: &[f32; 4]) -> f32 { data.iter().sum() }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // Self types
    files.push(TestFile {
        path: "autoversion/plain_self.rs".to_string(),
        content: "use archmage::autoversion;\n\
                  struct P { f: f32 }\n\
                  impl P {\n\
                      #[autoversion]\n\
                      fn apply(&self, x: f32) -> f32 { x * self.f }\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });

    files.push(TestFile {
        path: "autoversion/self_type.rs".to_string(),
        content: "use archmage::autoversion;\n\
                  struct P { f: f32 }\n\
                  impl P {\n\
                      #[autoversion(_self = P)]\n\
                      fn apply(&self, x: f32) -> f32 { x * _self.f }\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // Unsafe
    files.push(TestFile {
        path: "autoversion/unsafe_fn.rs".to_string(),
        content: "use archmage::autoversion;\n\
                  #[autoversion]\n\
                  unsafe fn process(ptr: *const f32, len: usize) -> f32 {\n\
                      let mut s = 0.0f32;\n\
                      for i in 0..len { s += unsafe { *ptr.add(i) }; }\n\
                      s\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // cfg feature
    files.push(TestFile {
        path: "autoversion/cfg_feature.rs".to_string(),
        content: "use archmage::autoversion;\n\
                  #[autoversion(cfg(simd_opt))]\n\
                  fn sum(data: &[f32; 4]) -> f32 { data.iter().sum() }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // +default tier
    files.push(TestFile {
        path: "autoversion/default_tier.rs".to_string(),
        content: "use archmage::autoversion;\n\
                  #[autoversion(+default)]\n\
                  fn sum(data: &[f32; 4]) -> f32 { data.iter().sum() }\n\
                  fn main() {}\n"
            .to_string(),
    });
}

// ============================================================================
// incant! tests
// ============================================================================

fn gen_incant_tests(files: &mut Vec<TestFile>) {
    let callee_defs = "\
        use archmage::{arcane, incant, X64V3Token, X64V4Token, NeonToken, ScalarToken};\n\
        #[arcane] fn inner_v4(_t: X64V4Token, x: f32) -> f32 { x * 4.0 }\n\
        #[arcane] fn inner_v3(_t: X64V3Token, x: f32) -> f32 { x * 2.0 }\n\
        #[arcane] fn inner_neon(_t: NeonToken, x: f32) -> f32 { x * 2.0 }\n\
        fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }\n";

    // Token prepended (default)
    files.push(TestFile {
        path: "incant/token_prepend.rs".to_string(),
        content: format!(
            "{callee_defs}\
             fn dispatch(x: f32) -> f32 {{ incant!(inner(x), [v3, scalar]) }}\n\
             fn main() {{}}\n"
        ),
    });

    // Explicit Token marker — first
    files.push(TestFile {
        path: "incant/token_explicit_first.rs".to_string(),
        content: format!(
            "{callee_defs}\
             fn dispatch(x: f32) -> f32 {{ incant!(inner(Token, x), [v3, scalar]) }}\n\
             fn main() {{}}\n"
        ),
    });

    // Explicit Token marker — last
    let callee_defs_last = "\
        use archmage::{arcane, incant, X64V3Token, ScalarToken};\n\
        #[arcane] fn inner_v3(x: f32, _t: X64V3Token) -> f32 { x * 2.0 }\n\
        fn inner_scalar(x: f32, _t: ScalarToken) -> f32 { x }\n";

    files.push(TestFile {
        path: "incant/token_explicit_last.rs".to_string(),
        content: format!(
            "{callee_defs_last}\
             fn dispatch(x: f32) -> f32 {{ incant!(inner(x, Token), [v3, scalar]) }}\n\
             fn main() {{}}\n"
        ),
    });

    // Default tiers
    files.push(TestFile {
        path: "incant/default_tiers.rs".to_string(),
        content: format!(
            "{callee_defs}\
             fn dispatch(x: f32) -> f32 {{ incant!(inner(x)) }}\n\
             fn main() {{}}\n"
        ),
    });

    // Tier modifiers
    files.push(TestFile {
        path: "incant/tier_modifiers.rs".to_string(),
        content: format!(
            "{callee_defs}\
             fn dispatch(x: f32) -> f32 {{ incant!(inner(x), [-neon, -wasm128]) }}\n\
             fn main() {{}}\n"
        ),
    });

    // Feature-gated tier
    files.push(TestFile {
        path: "incant/feature_gated.rs".to_string(),
        content: format!(
            "{callee_defs}\
             fn dispatch(x: f32) -> f32 {{ incant!(inner(x), [v3(cfg(avx_opt)), scalar]) }}\n\
             fn main() {{}}\n"
        ),
    });
}

// ============================================================================
// Rewrite tests (incant! inside tier macros)
// ============================================================================

fn gen_rewrite_tests(files: &mut Vec<TestFile>) {
    let callee_defs = "\
        #[arcane] fn inner_v4(_t: X64V4Token, x: f32) -> f32 { x * 4.0 }\n\
        #[arcane] fn inner_v3(_t: X64V3Token, x: f32) -> f32 { x * 2.0 }\n\
        fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }\n";

    let callee_defs_last = "\
        #[arcane] fn inner_v3(x: f32, _t: X64V3Token) -> f32 { x * 2.0 }\n\
        fn inner_scalar(x: f32, _t: ScalarToken) -> f32 { x }\n";

    // Caller = arcane × tier relationship
    for (name, token_type, tier_list, desc) in [
        (
            "arcane_exact",
            "X64V3Token",
            "v3, scalar",
            "exact tier match",
        ),
        (
            "arcane_downgrade",
            "X64V4Token",
            "v3, scalar",
            "V4 caller → V3 callee",
        ),
        (
            "arcane_upgrade",
            "X64V3Token",
            "v4, v3, scalar",
            "V3 caller, V4 available",
        ),
        (
            "arcane_upgrade_gated",
            "X64V3Token",
            "v4(cfg(avx512)), v3, scalar",
            "V3 caller, V4 feature-gated",
        ),
    ] {
        files.push(TestFile {
            path: format!("rewrite/{name}.rs"),
            content: format!(
                "// Rewrite: {desc}\n\
                 use archmage::{{arcane, X64V3Token, X64V4Token, ScalarToken}};\n\
                 {callee_defs}\
                 #[arcane]\n\
                 fn outer(token: {token_type}, x: f32) -> f32 {{\n\
                     incant!(inner(x), [{tier_list}])\n\
                 }}\n\
                 fn main() {{}}\n"
            ),
        });
    }

    // Caller = arcane, explicit Token position
    files.push(TestFile {
        path: "rewrite/arcane_token_last.rs".to_string(),
        content: format!(
            "// Rewrite: explicit Token marker, token last in callee\n\
             use archmage::{{arcane, X64V3Token, ScalarToken}};\n\
             {callee_defs_last}\
             #[arcane]\n\
             fn outer(token: X64V3Token, x: f32) -> f32 {{\n\
                 incant!(inner(x, Token), [v3, scalar])\n\
             }}\n\
             fn main() {{}}\n"
        ),
    });

    // Caller = arcane, scalar fallback (cross-arch)
    files.push(TestFile {
        path: "rewrite/scalar_fallback.rs".to_string(),
        content: "// Rewrite: x86 caller, callee only has neon — scalar fallback\n\
                  use archmage::{arcane, X64V3Token, NeonToken, ScalarToken};\n\
                  #[arcane] fn inner_neon(_t: NeonToken, x: f32) -> f32 { x * 2.0 }\n\
                  fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }\n\
                  #[arcane]\n\
                  fn outer(token: X64V3Token, x: f32) -> f32 {\n\
                      incant!(inner(x), [neon, scalar])\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // Caller = autoversion × tier relationship
    for (name, tier_list, desc) in [
        ("autoversion_exact", "v3, scalar", "exact match"),
        ("autoversion_upgrade", "v4, v3, scalar", "V4 upgrade"),
        (
            "autoversion_upgrade_gated",
            "v4(cfg(avx512)), v3, scalar",
            "V4 gated upgrade",
        ),
    ] {
        files.push(TestFile {
            path: format!("rewrite/{name}.rs"),
            content: format!(
                "// Rewrite: autoversion caller, {desc}\n\
                 use archmage::{{autoversion, arcane, incant, X64V3Token, X64V4Token, ScalarToken}};\n\
                 #[arcane] fn inner_v4(_t: X64V4Token, x: f32) -> f32 {{ x * 4.0 }}\n\
                 #[arcane] fn inner_v3(_t: X64V3Token, x: f32) -> f32 {{ x * 2.0 }}\n\
                 fn inner_scalar(_t: ScalarToken, x: f32) -> f32 {{ x }}\n\
                 #[autoversion(v3, scalar)]\n\
                 fn outer(x: f32) -> f32 {{\n\
                     incant!(inner(x), [{tier_list}])\n\
                 }}\n\
                 fn main() {{}}\n"
            ),
        });
    }

    // Caller = rite with token
    files.push(TestFile {
        path: "rewrite/rite_exact.rs".to_string(),
        content: "// Rewrite: rite caller, exact match\n\
             use archmage::{rite, arcane, X64V3Token, ScalarToken};\n\
             #[arcane] fn inner_v3(_t: X64V3Token, x: f32) -> f32 { x * 2.0 }\n\
             fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }\n\
             #[rite]\n\
             fn outer(token: X64V3Token, x: f32) -> f32 {\n\
                 incant!(inner(x), [v3, scalar])\n\
             }\n\
             fn main() {}\n"
            .to_string(),
    });

    // Caller = rite multi-tier
    files.push(TestFile {
        path: "rewrite/rite_multi.rs".to_string(),
        content: "// Rewrite: rite multi-tier, per-variant rewrite\n\
                  use archmage::{rite, arcane, incant, X64V3Token, NeonToken, ScalarToken};\n\
                  #[arcane] fn inner_v3(_t: X64V3Token, x: f32) -> f32 { x * 2.0 }\n\
                  #[arcane] fn inner_neon(_t: NeonToken, x: f32) -> f32 { x * 2.0 }\n\
                  fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }\n\
                  #[rite(v3, neon)]\n\
                  fn outer(x: f32) -> f32 {\n\
                      incant!(inner(x), [v3, neon, scalar])\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // Caller = rite tokenless (should NOT rewrite)
    files.push(TestFile {
        path: "rewrite/rite_tokenless_passthrough.rs".to_string(),
        content: "// Rewrite: tokenless rite — incant! NOT rewritten (no token to pass)\n\
                  use archmage::{rite, incant, arcane, X64V3Token, ScalarToken};\n\
                  #[arcane] fn inner_v3(_t: X64V3Token, x: f32) -> f32 { x * 2.0 }\n\
                  fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }\n\
                  #[rite(v3)]\n\
                  fn outer(x: f32) -> f32 {\n\
                      incant!(inner(x), [v3, scalar])\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });
}

// ============================================================================
// Deprecated alias tests
// ============================================================================

fn gen_deprecated_tests(files: &mut Vec<TestFile>) {
    files.push(TestFile {
        path: "deprecated/simd_fn.rs".to_string(),
        content: "#[allow(deprecated)]\n\
                  use archmage::{simd_fn, X64V3Token};\n\
                  #[allow(deprecated)]\n\
                  #[simd_fn]\n\
                  fn process(token: X64V3Token, a: f32) -> f32 { a }\n\
                  fn main() {}\n"
            .to_string(),
    });

    files.push(TestFile {
        path: "deprecated/token_target_features_boundary.rs".to_string(),
        content: "use archmage::{token_target_features_boundary, X64V3Token};\n\
                  #[token_target_features_boundary]\n\
                  fn process(token: X64V3Token, a: f32) -> f32 { a }\n\
                  fn main() {}\n"
            .to_string(),
    });

    files.push(TestFile {
        path: "deprecated/token_target_features.rs".to_string(),
        content: "use archmage::{token_target_features, X64V3Token};\n\
                  #[token_target_features]\n\
                  fn process(token: X64V3Token, a: f32) -> f32 { a }\n\
                  fn main() {}\n"
            .to_string(),
    });

    files.push(TestFile {
        path: "deprecated/simd_route.rs".to_string(),
        content: "#[allow(deprecated)]\n\
                  use archmage::{arcane, simd_route, X64V3Token, ScalarToken};\n\
                  #[arcane] fn compute_v3(_t: X64V3Token, x: f32) -> f32 { x }\n\
                  fn compute_scalar(_t: ScalarToken, x: f32) -> f32 { x }\n\
                  #[allow(deprecated)]\n\
                  fn dispatch(x: f32) -> f32 { simd_route!(compute(x), [v3, scalar]) }\n\
                  fn main() {}\n"
            .to_string(),
    });

    files.push(TestFile {
        path: "deprecated/dispatch_variant.rs".to_string(),
        content: "use archmage::{arcane, dispatch_variant, X64V3Token, ScalarToken};\n\
                  #[arcane] fn compute_v3(_t: X64V3Token, x: f32) -> f32 { x }\n\
                  fn compute_scalar(_t: ScalarToken, x: f32) -> f32 { x }\n\
                  fn dispatch(x: f32) -> f32 { dispatch_variant!(compute(x), [v3, scalar]) }\n\
                  fn main() {}\n"
            .to_string(),
    });

    files.push(TestFile {
        path: "deprecated/autoversion_simdtoken.rs".to_string(),
        content: "#[allow(deprecated)]\n\
                  use archmage::{autoversion, SimdToken};\n\
                  #[allow(deprecated)]\n\
                  #[autoversion]\n\
                  fn process(_token: SimdToken, data: &[f32; 4]) -> f32 { data.iter().sum() }\n\
                  fn main() {}\n"
            .to_string(),
    });
}

// ============================================================================
// Combination tests (cross-macro patterns)
// ============================================================================

fn gen_combination_tests(files: &mut Vec<TestFile>) {
    // arcane calling rite
    files.push(TestFile {
        path: "combinations/arcane_calls_rite.rs".to_string(),
        content: "use archmage::{arcane, rite, X64V3Token};\n\
                  #[rite(v3)]\n\
                  fn normalize(v: &[f32; 4]) -> [f32; 4] {\n\
                      let mut s = 0.0f32;\n\
                      for &x in v { s += x * x; }\n\
                      let inv = 1.0 / s.sqrt();\n\
                      [v[0]*inv, v[1]*inv, v[2]*inv, v[3]*inv]\n\
                  }\n\
                  #[arcane]\n\
                  fn process(token: X64V3Token, data: &[f32; 4]) -> [f32; 4] {\n\
                      let _ = token;\n\
                      normalize(data)\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // autoversion chain
    files.push(TestFile {
        path: "combinations/autoversion_chain.rs".to_string(),
        content: "use archmage::autoversion;\n\
                  #[autoversion]\n\
                  fn inner(data: &[f32; 4]) -> f32 { data.iter().sum() }\n\
                  #[autoversion]\n\
                  fn outer(data: &[f32; 4], scale: f32) -> f32 { inner(data) * scale }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // token downgrade
    files.push(TestFile {
        path: "combinations/token_downgrade.rs".to_string(),
        content: "use archmage::{arcane, X64V3Token, X64V4Token};\n\
                  #[arcane]\n\
                  fn v3_helper(_t: X64V3Token, x: f32) -> f32 { x }\n\
                  #[arcane]\n\
                  fn v4_caller(token: X64V4Token, x: f32) -> f32 {\n\
                      v3_helper(token.v3(), x) + 1.0\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // token upgrade conditional
    files.push(TestFile {
        path: "combinations/token_upgrade.rs".to_string(),
        content: "use archmage::{arcane, SimdToken, X64V3Token, X64V4Token};\n\
                  #[arcane]\n\
                  fn v4_fast(_t: X64V4Token, x: f32) -> f32 { x * 4.0 }\n\
                  #[arcane]\n\
                  fn v3_with_upgrade(_t: X64V3Token, x: f32) -> f32 {\n\
                      if let Some(v4) = X64V4Token::summon() { v4_fast(v4, x) }\n\
                      else { x * 2.0 }\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });

    // plain token fn (no macro)
    files.push(TestFile {
        path: "combinations/plain_token_fn.rs".to_string(),
        content: "use archmage::{X64V3Token, SimdToken};\n\
                  fn uses_token(token: X64V3Token, data: &[f32; 4]) -> f32 {\n\
                      let _ = token;\n\
                      data.iter().sum()\n\
                  }\n\
                  fn dispatches() -> Option<f32> {\n\
                      let token = X64V3Token::summon()?;\n\
                      Some(uses_token(token, &[1.0, 2.0, 3.0, 4.0]))\n\
                  }\n\
                  fn main() {}\n"
            .to_string(),
    });
}
