// @generated by xtask expand_gen
// #[arcane] with associated type bound
use archmage::{arcane, X64V3Token};
#[arcane]
fn sum_iter<I>(token: X64V3Token, iter: I) -> f32
where
    I: Iterator<Item = f32>,
{
    let _ = token;
    iter.sum()
}
fn main() {}
