// @generated by xtask expand_gen
use archmage::{arcane, X64V3Token};
#[arcane(nested)]
#[track_caller]
#[expect(unused_variables)]
#[allow(clippy::too_many_arguments)]
#[must_use]
fn process(token: X64V3Token, unused: f32) -> f32 { 1.0 }
fn main() {}
