// @generated by xtask expand_gen
// #[arcane] returning Box<dyn Trait>
use archmage::{arcane, X64V3Token};
#[arcane]
fn make_adder(token: X64V3Token, offset: f32) -> Box<dyn Fn(f32) -> f32> {
    let _ = token;
    Box::new(move |x| x + offset)
}
fn main() {}
