// @generated by xtask expand_gen
// #[arcane] with closure parameter
use archmage::{arcane, X64V3Token};
#[arcane]
fn apply(token: X64V3Token, data: &[f32; 4], f: impl Fn(f32) -> f32) -> [f32; 4] {
    let _ = token;
    [f(data[0]), f(data[1]), f(data[2]), f(data[3])]
}
fn main() {}
