// @generated by xtask expand_gen
// #[arcane] with nested tuple destructuring + wildcard
use archmage::{arcane, X64V3Token};
#[arcane]
fn process(token: X64V3Token, ((x, _), z): ((f32, f32), f32)) -> f32 {
    x + z
}
fn main() {}
