// @generated by xtask expand_gen
// #[arcane] with array destructuring
use archmage::{arcane, X64V3Token};
#[arcane]
fn process(token: X64V3Token, [a, b, c, d]: [f32; 4]) -> f32 {
    a + b + c + d
}
fn main() {}
