// @generated by xtask expand_gen
// #[arcane] with tuple-destructured parameter
use archmage::{arcane, X64V3Token};
#[arcane]
fn process(token: X64V3Token, (a, b): (f32, f32)) -> f32 {
    a + b
}
fn main() {}
