// @generated by xtask expand_gen
// #[arcane] with dyn trait parameter
use archmage::{arcane, X64V3Token};
#[arcane]
fn process(token: X64V3Token, callback: &dyn Fn(f32) -> f32, x: f32) -> f32 {
    let _ = token;
    callback(x)
}
fn main() {}
