// @generated by xtask expand_gen
// #[arcane] with function pointer parameter
use archmage::{arcane, X64V3Token};
#[arcane]
fn apply_fn(token: X64V3Token, f: fn(f32) -> f32, x: f32) -> f32 {
    let _ = token;
    f(x)
}
fn main() {}
