// @generated by xtask expand_gen
// #[arcane] with lifetime + type + const generics combined
use archmage::{arcane, X64V3Token};
#[arcane]
fn first_n<'a, T: Copy, const N: usize>(
    token: X64V3Token,
    data: &'a [T; N],
) -> &'a T {
    let _ = token;
    &data[0]
}
fn main() {}
