// @generated by xtask expand_gen
// #[arcane] with multiple generic type parameters
use archmage::{arcane, X64V3Token};
use core::ops::Add;
#[arcane]
fn add_items<T: Add<Output = T> + Copy>(token: X64V3Token, a: T, b: T) -> T {
    let _ = token;
    a + b
}
fn main() {}
