// @generated by xtask expand_gen
// #[arcane] with lifetime parameter
use archmage::{arcane, X64V3Token};
#[arcane]
fn process<'a>(token: X64V3Token, data: &'a [f32]) -> &'a f32 {
    let _ = token;
    &data[0]
}
fn main() {}
