// @generated by xtask expand_gen
// #[arcane] with where clause
use archmage::{arcane, X64V3Token};
#[arcane]
fn sum_slice<T>(token: X64V3Token, data: &[T]) -> f32
where
    T: Copy + Into<f32>,
{
    let _ = token;
    let mut s = 0.0f32;
    for &x in data { s += x.into(); }
    s
}
fn main() {}
