// @generated by xtask expand_gen
// #[arcane] with const generic parameter
use archmage::{arcane, X64V3Token};
#[arcane]
fn sum_n<const N: usize>(token: X64V3Token, data: &[f32; N]) -> f32 {
    let _ = token;
    let mut s = 0.0f32;
    for &x in data { s += x; }
    s
}
fn main() {}
