// @generated by xtask expand_gen
// #[arcane] with higher-ranked trait bound (for<'a>)
use archmage::{arcane, X64V3Token};
#[arcane]
fn apply_ref<F>(token: X64V3Token, f: F, data: &[f32]) -> f32
where
    F: for<'a> Fn(&'a [f32]) -> f32,
{
    let _ = token;
    f(data)
}
fn main() {}
