// @generated by xtask expand_gen
use archmage::{arcane, X64V3Token};
#[arcane(import_intrinsics)]
fn process(token: X64V3Token, a: &[f32; 8], b: &[f32; 8]) -> [f32; 8] {
let va = _mm256_loadu_ps(a);
let vb = _mm256_loadu_ps(b);
let s = _mm256_add_ps(va, vb);
let mut out = [0.0f32; 8];
_mm256_storeu_ps(&mut out, s);
out
}
fn main() {}
