// @generated by xtask expand_gen
// #[arcane] with multiple wildcard parameters
use archmage::{arcane, X64V3Token};
#[arcane]
fn process(_: X64V3Token, _: f32, _: f32) -> f32 {
    0.0
}
fn main() {}
