// @generated by xtask expand_gen
// #[arcane] with multiple trait bounds on generic
use archmage::{arcane, X64V3Token};
use core::ops::{Add, Mul};
#[arcane]
fn fma<T>(token: X64V3Token, a: T, b: T, c: T) -> T
where
    T: Copy + Mul<Output = T> + Add<Output = T>,
{
    let _ = token;
    a * b + c
}
fn main() {}
