// @generated by xtask expand_gen
use archmage::{arcane, X64V3Token};
struct Processor { val: f32 }
impl Processor {
#[arcane(_self = Processor)]
fn process(&self, token: X64V3Token, a: f32) -> f32 { _self.val + a }

}
fn main() {}
