// @generated by xtask expand_gen
// #[arcane] with impl Trait return type
use archmage::{arcane, X64V3Token};
#[arcane]
fn make_iter(token: X64V3Token, data: &[f32]) -> impl Iterator<Item = &f32> {
    let _ = token;
    data.iter()
}
fn main() {}
