//! W128 / W256 f32 backend delegation for `X64V4Token` / `X64V4xToken` /
//! `Avx512Fp16Token`. Generated by xtask from the `F32x4Backend` and
//! `F32x8Backend` definitions; do not edit.
//!
//! ## Why this file exists
//!
//! The AVX-512 tokens advertise W512 support but have no implementations
//! of their own for the narrower [`F32x4Backend`] / [`F32x8Backend`]
//! traits. Without these, generic code parameterized on `T: F32x8Backend`
//! cannot accept a V4 token, and the cross-width
//! [`F32x16FromHalves`](crate::simd::generic::F32x16FromHalves) primitive
//! cannot either, though V4's native `_mm512_insertf32x8` is its best path.
//!
//! ## Deductive safety proof
//!
//! `X64V3Token`'s feature set is a strict subset of `X64V4Token`'s (the
//! registry adds AVX-512 F/BW/CD/DQ/VL, PCLMULQDQ and AES on top of V3), so
//! every instruction that is safe to execute under V3's proof is safe under
//! V4's. [`F32x4Backend`] / [`F32x8Backend`] for `X64V3Token` use only V3
//! intrinsics, so forwarding V4's methods to them is sound; `Self::Repr`
//! stays `__m128` / `__m256`, so callers see no representation change.
//! Each method forwards with the `.v3()` extractor, so the proof chain is
//! explicit at every call. `X64V4xToken` and `Avx512Fp16Token` are V4 plus
//! further AVX-512 sub-features, supersets of V3 by the same argument.
//!
//! ## The exception: pixel packing
//!
//! `to_u8_bytes` (both widths) and `f32x4::store_rgba_bytes` call the
//! hand-written AVX-512VL helpers in `x86_v4_f32_overrides.rs`, which take
//! a concrete `X64V4Token` (`self` for V4, `self.v4()` for V4x and FP16).

#![cfg(all(target_arch = "x86_64", feature = "avx512"))]

use super::x86_v4_f32_overrides as overrides;
use crate::simd::backends::{F32x4Backend, F32x8Backend};

impl F32x4Backend for archmage::X64V4Token {
    type Repr = <archmage::X64V3Token as F32x4Backend>::Repr;
    #[inline(always)]
    fn splat(self, v: f32) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::splat(self.v3(), v)
    }
    #[inline(always)]
    fn zero(self) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::zero(self.v3())
    }
    #[inline(always)]
    fn load(self, data: &[f32; 4]) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::load(self.v3(), data)
    }
    #[inline(always)]
    fn from_array(self, arr: [f32; 4]) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::from_array(self.v3(), arr)
    }
    #[inline(always)]
    fn store(self, repr: Self::Repr, out: &mut [f32; 4]) {
        <archmage::X64V3Token as F32x4Backend>::store(self.v3(), repr, out)
    }
    #[inline(always)]
    fn to_array(self, repr: Self::Repr) -> [f32; 4] {
        <archmage::X64V3Token as F32x4Backend>::to_array(self.v3(), repr)
    }
    #[inline(always)]
    fn add(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::add(self.v3(), a, b)
    }
    #[inline(always)]
    fn sub(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::sub(self.v3(), a, b)
    }
    #[inline(always)]
    fn mul(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul(self.v3(), a, b)
    }
    #[inline(always)]
    fn div(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::div(self.v3(), a, b)
    }
    #[inline(always)]
    fn neg(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::neg(self.v3(), a)
    }
    #[inline(always)]
    fn min(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::min(self.v3(), a, b)
    }
    #[inline(always)]
    fn max(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::max(self.v3(), a, b)
    }
    #[inline(always)]
    fn sqrt(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::sqrt(self.v3(), a)
    }
    #[inline(always)]
    fn abs(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::abs(self.v3(), a)
    }
    #[inline(always)]
    fn floor(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::floor(self.v3(), a)
    }
    #[inline(always)]
    fn ceil(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::ceil(self.v3(), a)
    }
    #[inline(always)]
    fn round(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::round(self.v3(), a)
    }
    #[inline(always)]
    fn mul_add(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul_add(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_sub(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul_sub(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_add_portable(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul_add_portable(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_sub_portable(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul_sub_portable(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn simd_eq(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_eq(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_ne(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_ne(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_lt(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_lt(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_le(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_le(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_gt(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_gt(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_ge(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_ge(self.v3(), a, b)
    }
    #[inline(always)]
    fn blend(self, mask: Self::Repr, if_true: Self::Repr, if_false: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::blend(self.v3(), mask, if_true, if_false)
    }
    #[inline(always)]
    fn reduce_add(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x4Backend>::reduce_add(self.v3(), a)
    }
    #[inline(always)]
    fn reduce_min(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x4Backend>::reduce_min(self.v3(), a)
    }
    #[inline(always)]
    fn reduce_max(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x4Backend>::reduce_max(self.v3(), a)
    }
    #[inline(always)]
    fn rcp_approx(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::rcp_approx(self.v3(), a)
    }
    #[inline(always)]
    fn rsqrt_approx(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::rsqrt_approx(self.v3(), a)
    }
    #[inline(always)]
    fn not(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::not(self.v3(), a)
    }
    #[inline(always)]
    fn bitand(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::bitand(self.v3(), a, b)
    }
    #[inline(always)]
    fn bitor(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::bitor(self.v3(), a, b)
    }
    #[inline(always)]
    fn bitxor(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::bitxor(self.v3(), a, b)
    }
    #[inline(always)]
    fn clamp(self, a: Self::Repr, lo: Self::Repr, hi: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::clamp(self.v3(), a, lo, hi)
    }
    #[inline(always)]
    fn recip(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::recip(self.v3(), a)
    }
    #[inline(always)]
    fn rsqrt(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::rsqrt(self.v3(), a)
    }
    #[inline(always)]
    fn to_u8_bytes(self, a: Self::Repr) -> [u8; 4] {
        overrides::to_u8_bytes_x4_v4(self, a)
    }
    #[inline(always)]
    fn store_rgba_bytes(
        self,
        r: Self::Repr,
        g: Self::Repr,
        b: Self::Repr,
        a: Self::Repr,
    ) -> [u8; 16] {
        overrides::store_rgba_bytes_x4_v4(self, r, g, b, a)
    }
}

impl F32x4Backend for archmage::X64V4xToken {
    type Repr = <archmage::X64V3Token as F32x4Backend>::Repr;
    #[inline(always)]
    fn splat(self, v: f32) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::splat(self.v3(), v)
    }
    #[inline(always)]
    fn zero(self) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::zero(self.v3())
    }
    #[inline(always)]
    fn load(self, data: &[f32; 4]) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::load(self.v3(), data)
    }
    #[inline(always)]
    fn from_array(self, arr: [f32; 4]) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::from_array(self.v3(), arr)
    }
    #[inline(always)]
    fn store(self, repr: Self::Repr, out: &mut [f32; 4]) {
        <archmage::X64V3Token as F32x4Backend>::store(self.v3(), repr, out)
    }
    #[inline(always)]
    fn to_array(self, repr: Self::Repr) -> [f32; 4] {
        <archmage::X64V3Token as F32x4Backend>::to_array(self.v3(), repr)
    }
    #[inline(always)]
    fn add(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::add(self.v3(), a, b)
    }
    #[inline(always)]
    fn sub(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::sub(self.v3(), a, b)
    }
    #[inline(always)]
    fn mul(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul(self.v3(), a, b)
    }
    #[inline(always)]
    fn div(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::div(self.v3(), a, b)
    }
    #[inline(always)]
    fn neg(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::neg(self.v3(), a)
    }
    #[inline(always)]
    fn min(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::min(self.v3(), a, b)
    }
    #[inline(always)]
    fn max(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::max(self.v3(), a, b)
    }
    #[inline(always)]
    fn sqrt(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::sqrt(self.v3(), a)
    }
    #[inline(always)]
    fn abs(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::abs(self.v3(), a)
    }
    #[inline(always)]
    fn floor(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::floor(self.v3(), a)
    }
    #[inline(always)]
    fn ceil(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::ceil(self.v3(), a)
    }
    #[inline(always)]
    fn round(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::round(self.v3(), a)
    }
    #[inline(always)]
    fn mul_add(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul_add(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_sub(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul_sub(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_add_portable(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul_add_portable(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_sub_portable(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul_sub_portable(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn simd_eq(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_eq(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_ne(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_ne(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_lt(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_lt(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_le(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_le(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_gt(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_gt(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_ge(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_ge(self.v3(), a, b)
    }
    #[inline(always)]
    fn blend(self, mask: Self::Repr, if_true: Self::Repr, if_false: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::blend(self.v3(), mask, if_true, if_false)
    }
    #[inline(always)]
    fn reduce_add(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x4Backend>::reduce_add(self.v3(), a)
    }
    #[inline(always)]
    fn reduce_min(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x4Backend>::reduce_min(self.v3(), a)
    }
    #[inline(always)]
    fn reduce_max(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x4Backend>::reduce_max(self.v3(), a)
    }
    #[inline(always)]
    fn rcp_approx(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::rcp_approx(self.v3(), a)
    }
    #[inline(always)]
    fn rsqrt_approx(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::rsqrt_approx(self.v3(), a)
    }
    #[inline(always)]
    fn not(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::not(self.v3(), a)
    }
    #[inline(always)]
    fn bitand(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::bitand(self.v3(), a, b)
    }
    #[inline(always)]
    fn bitor(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::bitor(self.v3(), a, b)
    }
    #[inline(always)]
    fn bitxor(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::bitxor(self.v3(), a, b)
    }
    #[inline(always)]
    fn clamp(self, a: Self::Repr, lo: Self::Repr, hi: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::clamp(self.v3(), a, lo, hi)
    }
    #[inline(always)]
    fn recip(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::recip(self.v3(), a)
    }
    #[inline(always)]
    fn rsqrt(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::rsqrt(self.v3(), a)
    }
    #[inline(always)]
    fn to_u8_bytes(self, a: Self::Repr) -> [u8; 4] {
        overrides::to_u8_bytes_x4_v4(self.v4(), a)
    }
    #[inline(always)]
    fn store_rgba_bytes(
        self,
        r: Self::Repr,
        g: Self::Repr,
        b: Self::Repr,
        a: Self::Repr,
    ) -> [u8; 16] {
        overrides::store_rgba_bytes_x4_v4(self.v4(), r, g, b, a)
    }
}

impl F32x4Backend for archmage::Avx512Fp16Token {
    type Repr = <archmage::X64V3Token as F32x4Backend>::Repr;
    #[inline(always)]
    fn splat(self, v: f32) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::splat(self.v3(), v)
    }
    #[inline(always)]
    fn zero(self) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::zero(self.v3())
    }
    #[inline(always)]
    fn load(self, data: &[f32; 4]) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::load(self.v3(), data)
    }
    #[inline(always)]
    fn from_array(self, arr: [f32; 4]) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::from_array(self.v3(), arr)
    }
    #[inline(always)]
    fn store(self, repr: Self::Repr, out: &mut [f32; 4]) {
        <archmage::X64V3Token as F32x4Backend>::store(self.v3(), repr, out)
    }
    #[inline(always)]
    fn to_array(self, repr: Self::Repr) -> [f32; 4] {
        <archmage::X64V3Token as F32x4Backend>::to_array(self.v3(), repr)
    }
    #[inline(always)]
    fn add(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::add(self.v3(), a, b)
    }
    #[inline(always)]
    fn sub(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::sub(self.v3(), a, b)
    }
    #[inline(always)]
    fn mul(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul(self.v3(), a, b)
    }
    #[inline(always)]
    fn div(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::div(self.v3(), a, b)
    }
    #[inline(always)]
    fn neg(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::neg(self.v3(), a)
    }
    #[inline(always)]
    fn min(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::min(self.v3(), a, b)
    }
    #[inline(always)]
    fn max(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::max(self.v3(), a, b)
    }
    #[inline(always)]
    fn sqrt(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::sqrt(self.v3(), a)
    }
    #[inline(always)]
    fn abs(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::abs(self.v3(), a)
    }
    #[inline(always)]
    fn floor(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::floor(self.v3(), a)
    }
    #[inline(always)]
    fn ceil(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::ceil(self.v3(), a)
    }
    #[inline(always)]
    fn round(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::round(self.v3(), a)
    }
    #[inline(always)]
    fn mul_add(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul_add(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_sub(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul_sub(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_add_portable(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul_add_portable(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_sub_portable(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::mul_sub_portable(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn simd_eq(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_eq(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_ne(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_ne(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_lt(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_lt(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_le(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_le(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_gt(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_gt(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_ge(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::simd_ge(self.v3(), a, b)
    }
    #[inline(always)]
    fn blend(self, mask: Self::Repr, if_true: Self::Repr, if_false: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::blend(self.v3(), mask, if_true, if_false)
    }
    #[inline(always)]
    fn reduce_add(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x4Backend>::reduce_add(self.v3(), a)
    }
    #[inline(always)]
    fn reduce_min(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x4Backend>::reduce_min(self.v3(), a)
    }
    #[inline(always)]
    fn reduce_max(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x4Backend>::reduce_max(self.v3(), a)
    }
    #[inline(always)]
    fn rcp_approx(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::rcp_approx(self.v3(), a)
    }
    #[inline(always)]
    fn rsqrt_approx(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::rsqrt_approx(self.v3(), a)
    }
    #[inline(always)]
    fn not(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::not(self.v3(), a)
    }
    #[inline(always)]
    fn bitand(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::bitand(self.v3(), a, b)
    }
    #[inline(always)]
    fn bitor(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::bitor(self.v3(), a, b)
    }
    #[inline(always)]
    fn bitxor(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::bitxor(self.v3(), a, b)
    }
    #[inline(always)]
    fn clamp(self, a: Self::Repr, lo: Self::Repr, hi: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::clamp(self.v3(), a, lo, hi)
    }
    #[inline(always)]
    fn recip(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::recip(self.v3(), a)
    }
    #[inline(always)]
    fn rsqrt(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x4Backend>::rsqrt(self.v3(), a)
    }
    #[inline(always)]
    fn to_u8_bytes(self, a: Self::Repr) -> [u8; 4] {
        overrides::to_u8_bytes_x4_v4(self.v4(), a)
    }
    #[inline(always)]
    fn store_rgba_bytes(
        self,
        r: Self::Repr,
        g: Self::Repr,
        b: Self::Repr,
        a: Self::Repr,
    ) -> [u8; 16] {
        overrides::store_rgba_bytes_x4_v4(self.v4(), r, g, b, a)
    }
}

impl F32x8Backend for archmage::X64V4Token {
    type Repr = <archmage::X64V3Token as F32x8Backend>::Repr;
    #[inline(always)]
    fn splat(self, v: f32) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::splat(self.v3(), v)
    }
    #[inline(always)]
    fn zero(self) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::zero(self.v3())
    }
    #[inline(always)]
    fn load(self, data: &[f32; 8]) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::load(self.v3(), data)
    }
    #[inline(always)]
    fn from_array(self, arr: [f32; 8]) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::from_array(self.v3(), arr)
    }
    #[inline(always)]
    fn store(self, repr: Self::Repr, out: &mut [f32; 8]) {
        <archmage::X64V3Token as F32x8Backend>::store(self.v3(), repr, out)
    }
    #[inline(always)]
    fn to_array(self, repr: Self::Repr) -> [f32; 8] {
        <archmage::X64V3Token as F32x8Backend>::to_array(self.v3(), repr)
    }
    #[inline(always)]
    fn add(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::add(self.v3(), a, b)
    }
    #[inline(always)]
    fn sub(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::sub(self.v3(), a, b)
    }
    #[inline(always)]
    fn mul(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul(self.v3(), a, b)
    }
    #[inline(always)]
    fn div(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::div(self.v3(), a, b)
    }
    #[inline(always)]
    fn neg(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::neg(self.v3(), a)
    }
    #[inline(always)]
    fn min(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::min(self.v3(), a, b)
    }
    #[inline(always)]
    fn max(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::max(self.v3(), a, b)
    }
    #[inline(always)]
    fn sqrt(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::sqrt(self.v3(), a)
    }
    #[inline(always)]
    fn abs(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::abs(self.v3(), a)
    }
    #[inline(always)]
    fn floor(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::floor(self.v3(), a)
    }
    #[inline(always)]
    fn ceil(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::ceil(self.v3(), a)
    }
    #[inline(always)]
    fn round(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::round(self.v3(), a)
    }
    #[inline(always)]
    fn mul_add(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul_add(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_sub(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul_sub(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_add_portable(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul_add_portable(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_sub_portable(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul_sub_portable(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn simd_eq(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_eq(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_ne(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_ne(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_lt(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_lt(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_le(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_le(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_gt(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_gt(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_ge(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_ge(self.v3(), a, b)
    }
    #[inline(always)]
    fn blend(self, mask: Self::Repr, if_true: Self::Repr, if_false: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::blend(self.v3(), mask, if_true, if_false)
    }
    #[inline(always)]
    fn reduce_add(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x8Backend>::reduce_add(self.v3(), a)
    }
    #[inline(always)]
    fn reduce_min(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x8Backend>::reduce_min(self.v3(), a)
    }
    #[inline(always)]
    fn reduce_max(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x8Backend>::reduce_max(self.v3(), a)
    }
    #[inline(always)]
    fn rcp_approx(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::rcp_approx(self.v3(), a)
    }
    #[inline(always)]
    fn rsqrt_approx(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::rsqrt_approx(self.v3(), a)
    }
    #[inline(always)]
    fn not(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::not(self.v3(), a)
    }
    #[inline(always)]
    fn bitand(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::bitand(self.v3(), a, b)
    }
    #[inline(always)]
    fn bitor(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::bitor(self.v3(), a, b)
    }
    #[inline(always)]
    fn bitxor(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::bitxor(self.v3(), a, b)
    }
    #[inline(always)]
    fn clamp(self, a: Self::Repr, lo: Self::Repr, hi: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::clamp(self.v3(), a, lo, hi)
    }
    #[inline(always)]
    fn recip(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::recip(self.v3(), a)
    }
    #[inline(always)]
    fn rsqrt(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::rsqrt(self.v3(), a)
    }
    #[inline(always)]
    fn to_u8_bytes(self, a: Self::Repr) -> [u8; 8] {
        overrides::to_u8_bytes_x8_v4(self, a)
    }
    #[inline(always)]
    fn store_rgba_bytes(
        self,
        r: Self::Repr,
        g: Self::Repr,
        b: Self::Repr,
        a: Self::Repr,
    ) -> [u8; 32] {
        <archmage::X64V3Token as F32x8Backend>::store_rgba_bytes(self.v3(), r, g, b, a)
    }
    #[inline(always)]
    fn transpose_8x8_repr(self, rows: [Self::Repr; 8]) -> [Self::Repr; 8] {
        <archmage::X64V3Token as F32x8Backend>::transpose_8x8_repr(self.v3(), rows)
    }
}

impl F32x8Backend for archmage::X64V4xToken {
    type Repr = <archmage::X64V3Token as F32x8Backend>::Repr;
    #[inline(always)]
    fn splat(self, v: f32) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::splat(self.v3(), v)
    }
    #[inline(always)]
    fn zero(self) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::zero(self.v3())
    }
    #[inline(always)]
    fn load(self, data: &[f32; 8]) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::load(self.v3(), data)
    }
    #[inline(always)]
    fn from_array(self, arr: [f32; 8]) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::from_array(self.v3(), arr)
    }
    #[inline(always)]
    fn store(self, repr: Self::Repr, out: &mut [f32; 8]) {
        <archmage::X64V3Token as F32x8Backend>::store(self.v3(), repr, out)
    }
    #[inline(always)]
    fn to_array(self, repr: Self::Repr) -> [f32; 8] {
        <archmage::X64V3Token as F32x8Backend>::to_array(self.v3(), repr)
    }
    #[inline(always)]
    fn add(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::add(self.v3(), a, b)
    }
    #[inline(always)]
    fn sub(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::sub(self.v3(), a, b)
    }
    #[inline(always)]
    fn mul(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul(self.v3(), a, b)
    }
    #[inline(always)]
    fn div(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::div(self.v3(), a, b)
    }
    #[inline(always)]
    fn neg(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::neg(self.v3(), a)
    }
    #[inline(always)]
    fn min(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::min(self.v3(), a, b)
    }
    #[inline(always)]
    fn max(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::max(self.v3(), a, b)
    }
    #[inline(always)]
    fn sqrt(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::sqrt(self.v3(), a)
    }
    #[inline(always)]
    fn abs(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::abs(self.v3(), a)
    }
    #[inline(always)]
    fn floor(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::floor(self.v3(), a)
    }
    #[inline(always)]
    fn ceil(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::ceil(self.v3(), a)
    }
    #[inline(always)]
    fn round(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::round(self.v3(), a)
    }
    #[inline(always)]
    fn mul_add(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul_add(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_sub(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul_sub(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_add_portable(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul_add_portable(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_sub_portable(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul_sub_portable(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn simd_eq(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_eq(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_ne(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_ne(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_lt(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_lt(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_le(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_le(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_gt(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_gt(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_ge(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_ge(self.v3(), a, b)
    }
    #[inline(always)]
    fn blend(self, mask: Self::Repr, if_true: Self::Repr, if_false: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::blend(self.v3(), mask, if_true, if_false)
    }
    #[inline(always)]
    fn reduce_add(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x8Backend>::reduce_add(self.v3(), a)
    }
    #[inline(always)]
    fn reduce_min(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x8Backend>::reduce_min(self.v3(), a)
    }
    #[inline(always)]
    fn reduce_max(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x8Backend>::reduce_max(self.v3(), a)
    }
    #[inline(always)]
    fn rcp_approx(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::rcp_approx(self.v3(), a)
    }
    #[inline(always)]
    fn rsqrt_approx(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::rsqrt_approx(self.v3(), a)
    }
    #[inline(always)]
    fn not(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::not(self.v3(), a)
    }
    #[inline(always)]
    fn bitand(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::bitand(self.v3(), a, b)
    }
    #[inline(always)]
    fn bitor(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::bitor(self.v3(), a, b)
    }
    #[inline(always)]
    fn bitxor(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::bitxor(self.v3(), a, b)
    }
    #[inline(always)]
    fn clamp(self, a: Self::Repr, lo: Self::Repr, hi: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::clamp(self.v3(), a, lo, hi)
    }
    #[inline(always)]
    fn recip(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::recip(self.v3(), a)
    }
    #[inline(always)]
    fn rsqrt(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::rsqrt(self.v3(), a)
    }
    #[inline(always)]
    fn to_u8_bytes(self, a: Self::Repr) -> [u8; 8] {
        overrides::to_u8_bytes_x8_v4(self.v4(), a)
    }
    #[inline(always)]
    fn store_rgba_bytes(
        self,
        r: Self::Repr,
        g: Self::Repr,
        b: Self::Repr,
        a: Self::Repr,
    ) -> [u8; 32] {
        <archmage::X64V3Token as F32x8Backend>::store_rgba_bytes(self.v3(), r, g, b, a)
    }
    #[inline(always)]
    fn transpose_8x8_repr(self, rows: [Self::Repr; 8]) -> [Self::Repr; 8] {
        <archmage::X64V3Token as F32x8Backend>::transpose_8x8_repr(self.v3(), rows)
    }
}

impl F32x8Backend for archmage::Avx512Fp16Token {
    type Repr = <archmage::X64V3Token as F32x8Backend>::Repr;
    #[inline(always)]
    fn splat(self, v: f32) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::splat(self.v3(), v)
    }
    #[inline(always)]
    fn zero(self) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::zero(self.v3())
    }
    #[inline(always)]
    fn load(self, data: &[f32; 8]) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::load(self.v3(), data)
    }
    #[inline(always)]
    fn from_array(self, arr: [f32; 8]) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::from_array(self.v3(), arr)
    }
    #[inline(always)]
    fn store(self, repr: Self::Repr, out: &mut [f32; 8]) {
        <archmage::X64V3Token as F32x8Backend>::store(self.v3(), repr, out)
    }
    #[inline(always)]
    fn to_array(self, repr: Self::Repr) -> [f32; 8] {
        <archmage::X64V3Token as F32x8Backend>::to_array(self.v3(), repr)
    }
    #[inline(always)]
    fn add(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::add(self.v3(), a, b)
    }
    #[inline(always)]
    fn sub(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::sub(self.v3(), a, b)
    }
    #[inline(always)]
    fn mul(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul(self.v3(), a, b)
    }
    #[inline(always)]
    fn div(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::div(self.v3(), a, b)
    }
    #[inline(always)]
    fn neg(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::neg(self.v3(), a)
    }
    #[inline(always)]
    fn min(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::min(self.v3(), a, b)
    }
    #[inline(always)]
    fn max(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::max(self.v3(), a, b)
    }
    #[inline(always)]
    fn sqrt(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::sqrt(self.v3(), a)
    }
    #[inline(always)]
    fn abs(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::abs(self.v3(), a)
    }
    #[inline(always)]
    fn floor(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::floor(self.v3(), a)
    }
    #[inline(always)]
    fn ceil(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::ceil(self.v3(), a)
    }
    #[inline(always)]
    fn round(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::round(self.v3(), a)
    }
    #[inline(always)]
    fn mul_add(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul_add(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_sub(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul_sub(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_add_portable(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul_add_portable(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn mul_sub_portable(self, a: Self::Repr, b: Self::Repr, c: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::mul_sub_portable(self.v3(), a, b, c)
    }
    #[inline(always)]
    fn simd_eq(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_eq(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_ne(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_ne(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_lt(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_lt(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_le(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_le(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_gt(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_gt(self.v3(), a, b)
    }
    #[inline(always)]
    fn simd_ge(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::simd_ge(self.v3(), a, b)
    }
    #[inline(always)]
    fn blend(self, mask: Self::Repr, if_true: Self::Repr, if_false: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::blend(self.v3(), mask, if_true, if_false)
    }
    #[inline(always)]
    fn reduce_add(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x8Backend>::reduce_add(self.v3(), a)
    }
    #[inline(always)]
    fn reduce_min(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x8Backend>::reduce_min(self.v3(), a)
    }
    #[inline(always)]
    fn reduce_max(self, a: Self::Repr) -> f32 {
        <archmage::X64V3Token as F32x8Backend>::reduce_max(self.v3(), a)
    }
    #[inline(always)]
    fn rcp_approx(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::rcp_approx(self.v3(), a)
    }
    #[inline(always)]
    fn rsqrt_approx(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::rsqrt_approx(self.v3(), a)
    }
    #[inline(always)]
    fn not(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::not(self.v3(), a)
    }
    #[inline(always)]
    fn bitand(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::bitand(self.v3(), a, b)
    }
    #[inline(always)]
    fn bitor(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::bitor(self.v3(), a, b)
    }
    #[inline(always)]
    fn bitxor(self, a: Self::Repr, b: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::bitxor(self.v3(), a, b)
    }
    #[inline(always)]
    fn clamp(self, a: Self::Repr, lo: Self::Repr, hi: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::clamp(self.v3(), a, lo, hi)
    }
    #[inline(always)]
    fn recip(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::recip(self.v3(), a)
    }
    #[inline(always)]
    fn rsqrt(self, a: Self::Repr) -> Self::Repr {
        <archmage::X64V3Token as F32x8Backend>::rsqrt(self.v3(), a)
    }
    #[inline(always)]
    fn to_u8_bytes(self, a: Self::Repr) -> [u8; 8] {
        overrides::to_u8_bytes_x8_v4(self.v4(), a)
    }
    #[inline(always)]
    fn store_rgba_bytes(
        self,
        r: Self::Repr,
        g: Self::Repr,
        b: Self::Repr,
        a: Self::Repr,
    ) -> [u8; 32] {
        <archmage::X64V3Token as F32x8Backend>::store_rgba_bytes(self.v3(), r, g, b, a)
    }
    #[inline(always)]
    fn transpose_8x8_repr(self, rows: [Self::Repr; 8]) -> [Self::Repr; 8] {
        <archmage::X64V3Token as F32x8Backend>::transpose_8x8_repr(self.v3(), rows)
    }
}
