// @generated by xtask expand_gen
#[allow(deprecated)]
use archmage::{autoversion, SimdToken};
#[allow(deprecated)]
#[autoversion]
fn process(_token: SimdToken, data: &[f32; 4]) -> f32 { data.iter().sum() }
fn main() {}
