// @generated by xtask expand_gen
use archmage::{arcane, dispatch_variant, X64V3Token, ScalarToken};
#[arcane] fn compute_v3(_t: X64V3Token, x: f32) -> f32 { x }
fn compute_scalar(_t: ScalarToken, x: f32) -> f32 { x }
fn dispatch(x: f32) -> f32 { dispatch_variant!(compute(x), [v3, scalar]) }
fn main() {}
