// @generated by xtask expand_gen
#[allow(deprecated)]
use archmage::{arcane, simd_route, X64V3Token, ScalarToken};
#[arcane] fn compute_v3(_t: X64V3Token, x: f32) -> f32 { x }
fn compute_scalar(_t: ScalarToken, x: f32) -> f32 { x }
#[allow(deprecated)]
fn dispatch(x: f32) -> f32 { simd_route!(compute(x), [v3, scalar]) }
fn main() {}
