// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::prelude::*;
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn __arcane_inner_v3(token: archmage::X64V3Token, x: f32) -> f32 {
    let _ = token;
    x
}
#[cfg(target_arch = "x86_64")]
#[inline(always)]
fn inner_v3(token: archmage::X64V3Token, x: f32) -> f32 {
    let _: () = <archmage::X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
    unsafe { __arcane_inner_v3(token, x) }
}
#[cfg(target_arch = "aarch64")]
#[doc(hidden)]
#[target_feature(enable = "neon")]
#[inline]
fn __arcane_inner_neon(token: archmage::NeonToken, x: f32) -> f32 {
    let _ = token;
    x
}
#[cfg(target_arch = "aarch64")]
#[inline(always)]
fn inner_neon(token: archmage::NeonToken, x: f32) -> f32 {
    let _: () = <archmage::NeonToken>::__ARCHMAGE_ASSERT_TIER_72CB52B2;
    unsafe { __arcane_inner_neon(token, x) }
}
#[cfg(target_arch = "wasm32")]
#[target_feature(enable = "simd128")]
#[inline]
fn inner_wasm128(token: archmage::Wasm128Token, x: f32) -> f32 {
    let _ = token;
    x
}
fn inner_scalar(token: archmage::ScalarToken, x: f32) -> f32 {
    let _ = token;
    x
}
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn __arcane_outer_v3(token: archmage::X64V3Token, x: f32) -> f32 {
    inner_v3(token, x)
}
#[cfg(target_arch = "x86_64")]
#[inline(always)]
fn outer_v3(token: archmage::X64V3Token, x: f32) -> f32 {
    let _: () = <archmage::X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
    unsafe { __arcane_outer_v3(token, x) }
}
#[cfg(target_arch = "aarch64")]
#[doc(hidden)]
#[target_feature(enable = "neon")]
#[inline]
fn __arcane_outer_neon(token: archmage::NeonToken, x: f32) -> f32 {
    inner_neon(token, x)
}
#[cfg(target_arch = "aarch64")]
#[inline(always)]
fn outer_neon(token: archmage::NeonToken, x: f32) -> f32 {
    let _: () = <archmage::NeonToken>::__ARCHMAGE_ASSERT_TIER_72CB52B2;
    unsafe { __arcane_outer_neon(token, x) }
}
#[cfg(target_arch = "wasm32")]
#[target_feature(enable = "simd128")]
#[inline]
fn outer_wasm128(token: archmage::Wasm128Token, x: f32) -> f32 {
    inner_wasm128(token, x)
}
fn outer_scalar(token: archmage::ScalarToken, x: f32) -> f32 {
    '__incant: {
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V3Token::summon() {
                break '__incant inner_v3(__t, x);
            }
        }
        #[cfg(target_arch = "aarch64")]
        {
            if let Some(__t) = archmage::NeonToken::summon() {
                break '__incant inner_neon(__t, x);
            }
        }
        #[cfg(target_arch = "wasm32")]
        {
            if let Some(__t) = archmage::Wasm128Token::summon() {
                break '__incant inner_wasm128(__t, x);
            }
        }
        inner_scalar(archmage::ScalarToken, x)
    }
}
pub fn api(x: f32) -> f32 {
    '__incant: {
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            if let Some(__t) = archmage::X64V3Token::summon() {
                break '__incant outer_v3(__t, x);
            }
        }
        #[cfg(target_arch = "aarch64")]
        {
            if let Some(__t) = archmage::NeonToken::summon() {
                break '__incant outer_neon(__t, x);
            }
        }
        #[cfg(target_arch = "wasm32")]
        {
            if let Some(__t) = archmage::Wasm128Token::summon() {
                break '__incant outer_wasm128(__t, x);
            }
        }
        outer_scalar(archmage::ScalarToken, x)
    }
}
fn main() {}
