// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::prelude::*;
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn __arcane_inner_v3(token: archmage::X64V3Token, x: f32) -> f32 {
    let _ = token;
    x
}
#[cfg(target_arch = "x86_64")]
#[inline(always)]
fn inner_v3(token: archmage::X64V3Token, x: f32) -> f32 {
    let _: () = <archmage::X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
    unsafe { __arcane_inner_v3(token, x) }
}
#[cfg(target_arch = "aarch64")]
#[doc(hidden)]
#[target_feature(enable = "neon")]
#[inline]
fn __arcane_inner_neon(token: archmage::NeonToken, x: f32) -> f32 {
    let _ = token;
    x
}
#[cfg(target_arch = "aarch64")]
#[inline(always)]
fn inner_neon(token: archmage::NeonToken, x: f32) -> f32 {
    let _: () = <archmage::NeonToken>::__ARCHMAGE_ASSERT_TIER_72CB52B2;
    unsafe { __arcane_inner_neon(token, x) }
}
fn inner_scalar(token: archmage::ScalarToken, x: f32) -> f32 {
    let _ = token;
    x
}
#[cfg(target_arch = "x86_64")]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn outer_v3(x: f32) -> f32 {
    inner_v3(archmage::X64V3Token::from_context(), x)
}
#[cfg(target_arch = "aarch64")]
#[target_feature(enable = "neon")]
#[inline]
fn outer_neon(x: f32) -> f32 {
    inner_neon(archmage::NeonToken::from_context(), x)
}
fn main() {}
