// @generated by xtask expand_gen
// Rewrite: caller passes their token variable by name in incant! args
use archmage::{arcane, X64V3Token, ScalarToken};
#[arcane] fn inner_v3(_t: X64V3Token, x: f32) -> f32 { x * 2.0 }
fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }
#[arcane]
fn outer(alligator: X64V3Token, x: f32) -> f32 {
    // `alligator` is recognized as the token variable by name match
    incant!(inner(alligator, x), [v3, scalar])
}
fn main() {}
