// @generated by xtask expand_gen
// Rewrite: V3 caller, V4 available
use archmage::{arcane, X64V3Token, X64V4Token, ScalarToken};
#[arcane] fn inner_v4(_t: X64V4Token, x: f32) -> f32 { x * 4.0 }
#[arcane] fn inner_v3(_t: X64V3Token, x: f32) -> f32 { x * 2.0 }
fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }
#[arcane]
fn outer(token: X64V3Token, x: f32) -> f32 {
incant!(inner(x), [v4, v3, scalar])
}
fn main() {}
