// @generated by xtask expand_gen
// Rewrite: autoversion caller, V4 gated upgrade
use archmage::{autoversion, arcane, incant, X64V3Token, X64V4Token, ScalarToken};
#[arcane] fn inner_v4(_t: X64V4Token, x: f32) -> f32 { x * 4.0 }
#[arcane] fn inner_v3(_t: X64V3Token, x: f32) -> f32 { x * 2.0 }
fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }
#[autoversion(v3, scalar)]
fn outer(x: f32) -> f32 {
incant!(inner(x), [v4(cfg(avx512)), v3, scalar])
}
fn main() {}
