// @generated by xtask expand_gen
// Rewrite: V4 caller, callee has v3_crypto — cross-branch, V4 can't downgrade to v3_crypto
// V4 must summon v3_crypto (upgrade from V4's perspective, even though v3_crypto has lower priority)
use archmage::{arcane, X64V3CryptoToken, X64V4Token, ScalarToken};
#[arcane] fn inner_v3_crypto(_t: X64V3CryptoToken, x: f32) -> f32 { x * 3.0 }
fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }
#[arcane]
fn outer(token: X64V4Token, x: f32) -> f32 {
    incant!(inner(x), [v3_crypto, scalar])
}
fn main() {}
