// @generated by xtask expand_gen
// Rewrite: rite caller, exact match
use archmage::{rite, arcane, X64V3Token, ScalarToken};
#[arcane] fn inner_v3(_t: X64V3Token, x: f32) -> f32 { x * 2.0 }
fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }
#[rite]
fn outer(token: X64V3Token, x: f32) -> f32 {
incant!(inner(x), [v3, scalar])
}
fn main() {}
