// @generated by xtask expand_gen
// Rewrite: rite multi-tier, per-variant rewrite
use archmage::{rite, arcane, incant, X64V3Token, NeonToken, ScalarToken};
#[arcane] fn inner_v3(_t: X64V3Token, x: f32) -> f32 { x * 2.0 }
#[arcane] fn inner_neon(_t: NeonToken, x: f32) -> f32 { x * 2.0 }
fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }
#[rite(v3, neon)]
fn outer(x: f32) -> f32 {
incant!(inner(x), [v3, neon, scalar])
}
fn main() {}
