// @generated by xtask expand_gen
// Rewrite: x86 caller, callee only has neon — scalar fallback
use archmage::{arcane, X64V3Token, NeonToken, ScalarToken};
#[arcane] fn inner_neon(_t: NeonToken, x: f32) -> f32 { x * 2.0 }
fn inner_scalar(_t: ScalarToken, x: f32) -> f32 { x }
#[arcane]
fn outer(token: X64V3Token, x: f32) -> f32 {
incant!(inner(x), [neon, scalar])
}
fn main() {}
