// @generated by xtask expand_gen
// Rewrite: `without token` from a tokened #[arcane] body
use archmage::{rite, arcane, incant, X64V3Token};
#[rite(v3, neon)] fn helper(x: f32) -> f32 { x * 2.0 }
#[arcane]
fn outer(token: X64V3Token, x: f32) -> f32 {
let _ = token;
incant!(helper(x) without token) + 1.0
}
fn main() {}
