// @generated by xtask expand_gen
// Rewrite: `without token` — tokenless variant call, no token, no summon
use archmage::{rite, incant};
#[rite(v3, neon)] fn helper(x: f32) -> f32 { x * 2.0 }
#[rite(v3, neon)]
fn outer(x: f32) -> f32 {
incant!(helper(x) without token) + 1.0
}
fn main() {}
