// @generated by archmage-macros/src/raw_snapshots.rs: the macro output before cfg evaluation.
use archmage::{arcane, incant, X64V3Token, X64V4Token, NeonToken, ScalarToken};
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe,pclmulqdq,aes,avx512f,avx512bw,avx512cd,avx512dq,avx512vl"
)]
#[inline]
fn __arcane_inner_v4(_t: X64V4Token, x: f32) -> f32 {
    x * 4.0
}
#[cfg(target_arch = "x86_64")]
#[inline(always)]
fn inner_v4(_t: X64V4Token, x: f32) -> f32 {
    let _: () = <X64V4Token>::__ARCHMAGE_ASSERT_TIER_FE1B900C;
    unsafe { __arcane_inner_v4(_t, x) }
}
#[cfg(target_arch = "x86_64")]
#[doc(hidden)]
#[target_feature(
    enable = "sse,sse2,sse3,ssse3,sse4.1,sse4.2,popcnt,cmpxchg16b,avx,avx2,fma,bmi1,bmi2,f16c,lzcnt,movbe"
)]
#[inline]
fn __arcane_inner_v3(_t: X64V3Token, x: f32) -> f32 {
    x * 2.0
}
#[cfg(target_arch = "x86_64")]
#[inline(always)]
fn inner_v3(_t: X64V3Token, x: f32) -> f32 {
    let _: () = <X64V3Token>::__ARCHMAGE_ASSERT_TIER_F38B284B;
    unsafe { __arcane_inner_v3(_t, x) }
}
#[cfg(target_arch = "aarch64")]
#[doc(hidden)]
#[target_feature(enable = "neon")]
#[inline]
fn __arcane_inner_neon(_t: NeonToken, x: f32) -> f32 {
    x * 2.0
}
#[cfg(target_arch = "aarch64")]
#[inline(always)]
fn inner_neon(_t: NeonToken, x: f32) -> f32 {
    let _: () = <NeonToken>::__ARCHMAGE_ASSERT_TIER_72CB52B2;
    unsafe { __arcane_inner_neon(_t, x) }
}
fn inner_scalar(_t: ScalarToken, x: f32) -> f32 {
    x
}
fn dispatch(x: f32) -> f32 {
    '__incant: {
        #[allow(unused_imports)]
        use archmage::SimdToken;
        #[cfg(target_arch = "x86_64")]
        {
            #[allow(unexpected_cfgs)] #[cfg(feature = "avx512")]
            {
                if let Some(__t) = archmage::X64V4Token::summon() {
                    break '__incant inner_v4(__t, x);
                }
            }
            if let Some(__t) = archmage::X64V3Token::summon() {
                break '__incant inner_v3(__t, x);
            }
        }
        #[cfg(target_arch = "aarch64")]
        {
            if let Some(__t) = archmage::NeonToken::summon() {
                break '__incant inner_neon(__t, x);
            }
        }
        #[cfg(target_arch = "wasm32")]
        {
            if let Some(__t) = archmage::Wasm128Token::summon() {
                break '__incant inner_wasm128(__t, x);
            }
        }
        inner_scalar(archmage::ScalarToken, x)
    }
}
fn main() {}
